### ISSUE TITLE
Gsconnect not working but KDE Connect working fine

### ISSUE THREAD

**Issue by 1orZero** [GSConnect/gnome-shell-extension-gsconnect#1083] opened 2021-03-28 14:00 UTC
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

I currently switching from KDE plasma to GNOME, so I am trying to get my phone working with the GNOME DE.

I have tried reinstall **KDE connect** again and it was able to connect to my phone. 
But when I trying using **gsconnect** my device not even show up on the list. 

I have removed kde connect using the command below. (The plasma and KDE applications have been removed too)

```
sudo pacman -Rns kdeconnect 
```

**Steps To Reproduce:**

1. Go to 'Gnome Tweak'
2. Click on the setting icon of Gsconnect
3. Click the top left corner 'search icon'

**Expected behavior**

Seeing My android device on the Device list

**Screenshots**
![image](https://user-images.githubusercontent.com/53516684/112754665-b590b180-900f-11eb-884a-96498f036ed2.png)

I tried to ping my phone to make sure my pc and my phone in the same network.
![image](https://user-images.githubusercontent.com/53516684/112754691-d35e1680-900f-11eb-9c39-6dedde329970.png)

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

GSConnect: 44 (user)
GJS:       16800
Session:   x11
OS:        Arch Linux
--------------------------------------------------------------------------------
-- Journal begins at Sun 2021-01-31 06:19:21 CST, ends at Sun 2021-03-28 21:53:24 CST. --
Mar 28 21:53:10 audit[6401]: ANOM_ABEND auid=1000 uid=1000 gid=985 ses=4 pid=6401 comm="gjs" exe="/usr/bin/gjs-console" sig=5 res=1
Mar 28 21:53:10 gjs[6401]: Finalizing wrapper for an already freed object of type: Gtk.Button
Mar 28 21:53:10 kernel: traps: gjs[6401] trap int3 ip:7f9eb96a9b18 sp:7ffdc9569550 error:0 in libglib-2.0.so.0.6800.0[7f9eb966c000+8c000]
Mar 28 21:53:10 kernel: audit: type=1701 audit(1616939590.694:147): auid=1000 uid=1000 gid=985 ses=4 pid=6401 comm="gjs" exe="/usr/bin/gjs-console" sig=5 res=1
Mar 28 21:53:10 audit: BPF prog-id=39 op=LOAD
Mar 28 21:53:10 audit: BPF prog-id=40 op=LOAD
Mar 28 21:53:10 systemd[1]: Started Process Core Dump (PID 7117/UID 0).
Mar 28 21:53:10 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@2-7117-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 28 21:53:10 kernel: audit: type=1334 audit(1616939590.704:148): prog-id=39 op=LOAD
Mar 28 21:53:10 kernel: audit: type=1334 audit(1616939590.704:149): prog-id=40 op=LOAD
Mar 28 21:53:10 kernel: audit: type=1130 audit(1616939590.704:150): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@2-7117-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 28 21:53:10 systemd-coredump[7118]: Process 6401 (gjs) of user 1000 dumped core.
                                        
                                        Stack trace of thread 6401:
                                        #0  0x00007f9eb96a9b18 g_log_structured_array (libglib-2.0.so.0 + 0x5ab18)
                                        #1  0x00007f9eb96a9de6 g_log_default_handler (libglib-2.0.so.0 + 0x5ade6)
                                        #2  0x00007f9eb96ab229 g_logv (libglib-2.0.so.0 + 0x5c229)
                                        #3  0x00007f9eb96ab4d0 g_log (libglib-2.0.so.0 + 0x5c4d0)
                                        #4  0x00007f9eb97d7c52 n/a (libgjs.so.0 + 0x53c52)
                                        #5  0x00007f9eb7a4c4b2 n/a (libmozjs-78.so + 0x7324b2)
                                        #6  0x00007f9eb7a49316 n/a (libmozjs-78.so + 0x72f316)
                                        #7  0x00007f9eb7ecbdf8 n/a (libmozjs-78.so + 0xbb1df8)
                                        #8  0x00007f9eb825c625 n/a (libmozjs-78.so + 0xf42625)
                                        #9  0x00007f9eb825c9dc n/a (libmozjs-78.so + 0xf429dc)
                                        #10 0x00007f9eb825c45d n/a (libmozjs-78.so + 0xf4245d)
                                        #11 0x00007f9eb825c9dc n/a (libmozjs-78.so + 0xf429dc)
                                        #12 0x00007f9eb7ed0de5 n/a (libmozjs-78.so + 0xbb6de5)
                                        #13 0x00007f9eb772d624 n/a (libmozjs-78.so + 0x413624)
                                        #14 0x00007f9eb772a3a6 n/a (libmozjs-78.so + 0x4103a6)
                                        #15 0x00007f9eb7c019b4 n/a (libmozjs-78.so + 0x8e79b4)
                                        #16 0x00007f9eb97e48ec n/a (libgjs.so.0 + 0x608ec)
                                        #17 0x00007f9eb9614785 g_object_unref (libgobject-2.0.so.0 + 0x1f785)
                                        #18 0x00005593849cba42 n/a (gjs-console + 0x2a42)
                                        #19 0x00007f9eb9099b25 __libc_start_main (libc.so.6 + 0x27b25)
                                        #20 0x00005593849cbe5e n/a (gjs-console + 0x2e5e)
                                        
                                        Stack trace of thread 6404:
                                        #0  0x00007f9eb916637f __poll (libc.so.6 + 0xf437f)
                                        #1  0x00007f9eb96f69d8 n/a (libglib-2.0.so.0 + 0xa79d8)
                                        #2  0x00007f9eb96a2503 g_main_loop_run (libglib-2.0.so.0 + 0x53503)
                                        #3  0x00007f9eb953a558 n/a (libgio-2.0.so.0 + 0x102558)
                                        #4  0x00007f9eb96d0fb1 n/a (libglib-2.0.so.0 + 0x81fb1)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
                                        
                                        Stack trace of thread 6410:
                                        #0  0x00007f9eb704a9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                        #1  0x00007f9eb7044260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                        #2  0x00007f9eb7a8bafc _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so + 0x771afc)
                                        #3  0x00007f9eb7a8b5f1 n/a (libmozjs-78.so + 0x7715f1)
                                        #4  0x00007f9eb7d181bb n/a (libmozjs-78.so + 0x9fe1bb)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
                                        
                                        Stack trace of thread 6409:
                                        #0  0x00007f9eb704a9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                        #1  0x00007f9eb7044260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                        #2  0x00007f9eb7a8bafc _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so + 0x771afc)
                                        #3  0x00007f9eb7a8b5f1 n/a (libmozjs-78.so + 0x7715f1)
                                        #4  0x00007f9eb7d181bb n/a (libmozjs-78.so + 0x9fe1bb)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
                                        
                                        Stack trace of thread 6407:
                                        #0  0x00007f9eb704a9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                        #1  0x00007f9eb7044260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                        #2  0x00007f9eb7a8bafc _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so + 0x771afc)
                                        #3  0x00007f9eb7a8b5f1 n/a (libmozjs-78.so + 0x7715f1)
                                        #4  0x00007f9eb7d181bb n/a (libmozjs-78.so + 0x9fe1bb)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
                                        
                                        Stack trace of thread 6411:
                                        #0  0x00007f9eb704a9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                        #1  0x00007f9eb7044260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                        #2  0x00007f9eb7a8bafc _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so + 0x771afc)
                                        #3  0x00007f9eb7a8b5f1 n/a (libmozjs-78.so + 0x7715f1)
                                        #4  0x00007f9eb7d181bb n/a (libmozjs-78.so + 0x9fe1bb)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
                                        
                                        Stack trace of thread 6405:
                                        #0  0x00007f9eb704a9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                        #1  0x00007f9eb7044260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                        #2  0x00007f9eb7a8bafc _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so + 0x771afc)
                                        #3  0x00007f9eb7a8b5f1 n/a (libmozjs-78.so + 0x7715f1)
                                        #4  0x00007f9eb7d181bb n/a (libmozjs-78.so + 0x9fe1bb)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
                                        
                                        Stack trace of thread 6412:
                                        #0  0x00007f9eb704a9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                        #1  0x00007f9eb7044260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                        #2  0x00007f9eb7a8bafc _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so + 0x771afc)
                                        #3  0x00007f9eb7a8b5f1 n/a (libmozjs-78.so + 0x7715f1)
                                        #4  0x00007f9eb7d181bb n/a (libmozjs-78.so + 0x9fe1bb)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
                                        
                                        Stack trace of thread 6403:
                                        #0  0x00007f9eb916637f __poll (libc.so.6 + 0xf437f)
                                        #1  0x00007f9eb96f69d8 n/a (libglib-2.0.so.0 + 0xa79d8)
                                        #2  0x00007f9eb96a06f1 g_main_context_iteration (libglib-2.0.so.0 + 0x516f1)
                                        #3  0x00007f9eb96a0742 n/a (libglib-2.0.so.0 + 0x51742)
                                        #4  0x00007f9eb96d0fb1 n/a (libglib-2.0.so.0 + 0x81fb1)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
                                        
                                        Stack trace of thread 6406:
                                        #0  0x00007f9eb704a9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                        #1  0x00007f9eb7044260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                        #2  0x00007f9eb7a8bafc _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so + 0x771afc)
                                        #3  0x00007f9eb7a8b5f1 n/a (libmozjs-78.so + 0x7715f1)
                                        #4  0x00007f9eb7d181bb n/a (libmozjs-78.so + 0x9fe1bb)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
                                        
                                        Stack trace of thread 6408:
                                        #0  0x00007f9eb704a9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                                        #1  0x00007f9eb7044260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                                        #2  0x00007f9eb7a8bafc _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so + 0x771afc)
                                        #3  0x00007f9eb7a8b5f1 n/a (libmozjs-78.so + 0x7715f1)
                                        #4  0x00007f9eb7d181bb n/a (libmozjs-78.so + 0x9fe1bb)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
                                        
                                        Stack trace of thread 7116:
                                        #0  0x00007f9eb916ba9d syscall (libc.so.6 + 0xf9a9d)
                                        #1  0x00007f9eb96f0f5b g_cond_wait_until (libglib-2.0.so.0 + 0xa1f5b)
                                        #2  0x00007f9eb96728b3 n/a (libglib-2.0.so.0 + 0x238b3)
                                        #3  0x00007f9eb96d3ccb n/a (libglib-2.0.so.0 + 0x84ccb)
                                        #4  0x00007f9eb96d0fb1 n/a (libglib-2.0.so.0 + 0x81fb1)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
                                        
                                        Stack trace of thread 6414:
                                        #0  0x00007f9eb916637f __poll (libc.so.6 + 0xf437f)
                                        #1  0x00007f9eb96f69d8 n/a (libglib-2.0.so.0 + 0xa79d8)
                                        #2  0x00007f9eb96a06f1 g_main_context_iteration (libglib-2.0.so.0 + 0x516f1)
                                        #3  0x00007f9e972c8ebe n/a (libdconfsettings.so + 0x5ebe)
                                        #4  0x00007f9eb96d0fb1 n/a (libglib-2.0.so.0 + 0x81fb1)
                                        #5  0x00007f9eb703e299 start_thread (libpthread.so.0 + 0x9299)
                                        #6  0x00007f9eb9171053 __clone (libc.so.6 + 0xff053)
Mar 28 21:53:10 systemd[1]: systemd-coredump@2-7117-0.service: Succeeded.
Mar 28 21:53:10 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@2-7117-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 28 21:53:11 kernel: audit: type=1131 audit(1616939590.994:151): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@2-7117-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 28 21:53:11 audit: BPF prog-id=40 op=UNLOAD
Mar 28 21:53:11 audit: BPF prog-id=39 op=UNLOAD
Mar 28 21:53:11 kernel: audit: type=1334 audit(1616939591.354:152): prog-id=40 op=UNLOAD
Mar 28 21:53:11 kernel: audit: type=1334 audit(1616939591.354:153): prog-id=39 op=UNLOAD
Mar 28 21:53:13 org.gnome.tweaks.desktop[7127]: gnome-shell-extension-prefs is deprecated
Mar 28 21:53:13 org.gnome.tweaks.desktop[7127]: Install https://flathub.org/apps/details/org.gnome.Extensions for extension
Mar 28 21:53:13 org.gnome.tweaks.desktop[7127]: management, or use the gnome-extensions command line tool.
Mar 28 21:53:13 org.gnome.tweaks.desktop[7127]: Extensions can use the ExtensionUtils.openPrefs() method.
Mar 28 21:53:13 dbus-daemon[932]: [session uid=1000 pid=932] Activating service name='org.gnome.Shell.Extensions' requested by ':1.301' (uid=1000 pid=7129 comm="gnome-extensions prefs gsconnect@andyholmes.github")
Mar 28 21:53:13 dbus-daemon[932]: [session uid=1000 pid=932] Successfully activated service 'org.gnome.Shell.Extensions'
Mar 28 21:53:13 org.gnome.Shell.Extensions[7133]: Fontconfig error: "/etc/fonts/local.conf", line 2: XML or text declaration not at start of entity
Mar 28 21:53:13 dbus-daemon[932]: [session uid=1000 pid=932] Reloaded configuration
Mar 28 21:53:13 org.gnome.Shell.Extensions[7148]: Fontconfig error: "/etc/fonts/local.conf", line 2: XML or text declaration not at start of entity
Mar 28 21:53:13 dbus-daemon[932]: [session uid=1000 pid=932] Activating via systemd: service name='org.freedesktop.Tracker3.Miner.Extract' unit='tracker-extract-3.service' requested by ':1.93' (uid=1000 pid=1924 comm="/usr/lib/tracker-miner-fs-3 ")
Mar 28 21:53:13 systemd[897]: Starting Tracker metadata extractor...
Mar 28 21:53:13 tracker-extract[7168]: tracker-extract-3 running as org.freedesktop.Tracker3.Miner.Extract. The service will exit when org.freedesktop.Tracker3.Miner.Files disappears from the bus.
Mar 28 21:53:13 dbus-daemon[932]: [session uid=1000 pid=932] Successfully activated service 'org.freedesktop.Tracker3.Miner.Extract'
Mar 28 21:53:13 systemd[897]: Started Tracker metadata extractor.
Mar 28 21:53:17 gjs[2775]: JS ERROR: Gio.TlsError: Error performing TLS handshake: No supported cipher suites have been found.
                           _handshake/</<@/home/ka/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:595:44
                           @/home/ka/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 28 21:53:18 gjs[2775]: JS ERROR: Gio.TlsError: Error performing TLS handshake: No supported cipher suites have been found.
                           _handshake/</<@/home/ka/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:595:44
                           @/home/ka/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 28 21:53:21 gjs[2775]: JS ERROR: Gio.TlsError: Error performing TLS handshake: No supported cipher suites have been found.
                           _handshake/</<@/home/ka/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:595:44
                           @/home/ka/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 28 21:53:24 systemd[897]: tracker-extract-3.service: Succeeded.

```

**System Details (please complete the following information):**

 - **GSConnect version:** 44
   - **Installed from:** GNOME Extensions Website via Firefox & Chrome (tried both, now stick with Firefox's)
 - **GNOME/Shell version:** GNOME 3.38.4 
 - **Distro/Release:** Arch Linux x86_64 

**GSConnect environment (if applicable):**
 - **Paired Device(s):**  Oneplus 8 Pro
 - **KDE Connect app version:**  KDE Connect 1.16
 - **Plugin(s):** I have only Gsconnect enabled

**Additional Notes:**

x

Let me know if you need more information. Thank you

**Comment by sonnyp** [comment] 2021-03-28 14:06
Many thanks for the detailed report.

Closing as duplicate of #1082

**Closed by sonnyp** 2021-03-28 14:06 UTC
