### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by 2dbrose** [GSConnect/gnome-shell-extension-gsconnect#1435] opened 2022-08-05 18:03 UTC
```
GSConnect: 51 (user)
GJS:       17200
Session:   wayland
OS:        PureOS

_loadBackends@/home/donb/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/donb/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/donb/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/donb/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/donb/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-08-06 03:28
Duplicate of #1256

**Closed by andyholmes** 2022-08-06 03:28 UTC
Labels: duplicate
