### ISSUE TITLE
GSConnect displays “4G” icon even if connected via 5G

### ISSUE THREAD

**Issue by schuelermine** [GSConnect/gnome-shell-extension-gsconnect#1348] opened 2022-05-07 20:58 UTC
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

When a phone is connected via KDE Connect and connected to a 5G network, the menu item still displays a “4G” icon

**Steps To Reproduce:**

1. Connect to a 5G network

**Expected behavior**

A “5G” icon appears

**Screenshots**

![Screenshot from 2022-05-07 22-53-47](https://user-images.githubusercontent.com/48802534/167271409-f41de18a-5467-4d47-bc8a-820e9d5cef33.png)

**System Details (please complete the following information):**

 - **GSConnect version:** 50
   - **Installed from:** via home-manager, via Nix, from nixpkgs rev. c777cdf5c564015d5f63b09cc93bef4178b19b01
 - **GNOME/Shell version:** 42.0
 - **Distro/Release:** 22.05.20220505.c777cdf (Quokka)

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Google Pixel 6
 - **KDE Connect app version:** 1.19.1

**Comment by andyholmes** [comment] 2022-05-18 21:35
Can you provide logs detailing what the device is sending?

**Comment by ferdnyc** [comment] 2022-05-21 00:08
I was looking at this one myself. In my device's case, the response being sent back indicates that the device is connected via ``TelephonyManager.NETWORK_TYPE_LTE`, which is true. Currently 5G is mapped only to `NETWORK_TYPE_NG`, but that [doesn't appear to be](https://developer.android.com/training/connectivity/5g/enhance-with-5g#indicator), strictly speaking, entirely correct. [5G detection](https://developer.android.com/about/versions/11/features/5g#detection) is more complicated than that.

This will probably require changes on the KDE Connect app side, since they're not currently sending along the additional telephony information (the "override network type") that would be required to fully report all forms of 5G connectivity.

**Comment by ferdnyc** [comment] 2022-05-21 00:12
(Also, Adwaita [has had a 5G icon for like a year now](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/06bc90112d1d5e064528d6106e462ca9e3b829a1), so we can probably update this to use `network-cellular-5g-symbolic` for at least the cases that _are_ detected):

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/29456f27391fa61493121a53d82ba50bcf535e04/src/service/plugins/connectivity_report.js#L93-L96

**Comment by ferdnyc** [comment] 2022-05-21 00:27
Pooted upstream: https://bugs.kde.org/show_bug.cgi?id=454120

**Comment by andyholmes** [comment] 2022-08-02 23:50
Fixed in #1359, so closing now.

**Closed by andyholmes** 2022-08-02 23:50 UTC
Labels: help wanted, upstream, UX

**Comment by Strykar** [comment] 2025-02-22 20:07
Is this fixed? I still see 4G when my Poco X6Pro is on sub-6 5G.

**Comment by andyholmes** [comment] 2025-02-23 04:57
I believe this particular issue is fixed, since the cause was that Adwaita simply didn't have an icon for 5G. The 4G icon should only be shown if the device reports `LTE`:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/73cc6b66ad97a2ee114ba722972c5756c0ca5c61/src/service/plugins/connectivity_report.js#L87-L88

Either `LTE` shouldn't be reported as 4G, or perhaps the Android app (or Android) is mis-reporting the device's network type.

**Comment by Strykar** [comment] 2025-03-14 19:31
LTE should be reported as 4G, how do I troubleshoot this to figure out what is misreporting?

**Comment by andyholmes** [comment] 2025-03-15 05:33
For issues with Android app, you can report a bug upstream at https://bugs.kde.org
