### ISSUE TITLE
Device is not mounting.

### ISSUE THREAD

**Issue by hammadbawara** [GSConnect/gnome-shell-extension-gsconnect#1535] opened 2022-11-29 14:07 UTC
### Describe the bug

**Problem**
My Android Device is not not mounting.

### GSConnect version

54

### Installed from

Extension Manager

### GNOME Shell version

43

### Linux distribution/release

Ubuntu 22.10

### Paired device(s)

Huawei Y9 (2019)

### KDE Connect app version

1.19.1

### Support log

```plain text
GSConnect: 54 (user)
GJS:       17400
Session:   wayland
OS:        Ubuntu 22.10
--------------------------------------------------------------------------------
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Connection failed
                            _handleMount/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Nov 29 19:06:11 gjs[13430]: JS ERROR: hammad-mobile: Gio.IOErrorEnum: Unknown error 255
                            Cannot stat /home/hammad/.ssh/known_hosts: No such file or directory
                            _removeHostKey/</<@/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                            @/home/hammad/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

### Notes

I can send file to mobile from nautilus and I can also receive files. Other features are also working fine. Only problem I am facing is mobile is not mounting.

**Comment by andyholmes** [comment] 2023-01-03 01:11
Assuming this is a duplicate of #1203 and closing.

**Closed by andyholmes** 2023-01-03 01:11 UTC
Labels: duplicate
