### ISSUE TITLE
File received from phone deleted immediately

### ISSUE THREAD

**Issue by mgrewe** [GSConnect/gnome-shell-extension-gsconnect#1157] opened 2021-08-22 12:08 UTC
When I send files from my phone to my laptop (Arch, Gnome 40.4.0, GSConnect 47), the file is received and briefly shown in nautilus but then immediately deleted. No error is displayed on the phone. Laptop says: "Transfer Failed. Failed to receive ... from ...". For me, the problem already exists for a couple of month. Please also see the log:

```
GSConnect: 47 (user)
GJS:       16803
Session:   wayland
OS:        Arch Linux
--------------------------------------------------------------------------------
-- Journal begins at Sun 2020-11-15 11:04:22 CET, ends at Sun 2021-08-22 13:58:20 CEST. --
Aug 22 13:58:10 org.gnome.Shell.Extensions.GSConnect[112166]: [/service/device.js:_readLoop:338]: DEVNAME: {
                                                                "id": 1629633365136,
                                                                "type": "kdeconnect.connectivity_report",
                                                                "body": {
                                                                  "signalStrengths": {
                                                                    "2": {
                                                                      "networkType": "LTE",
                                                                      "signalStrength": 2
                                                                    }
                                                                  }
                                                                }
                                                              }
Aug 22 13:58:13 org.gnome.Shell.Extensions.GSConnect[112166]: [/service/backends/lan.js:_onIdentity:343]: {
                                                                "id": 1629633490031,
                                                                "type": "kdeconnect.identity",
                                                                "body": {
                                                                  "deviceId": "a14a1afa624623b6",
                                                                  "deviceName": "DEVNAME",
                                                                  "protocolVersion": 7,
                                                                  "deviceType": "phone",
                                                                  "incomingCapabilities": [
                                                                    "kdeconnect.telephony.request_mute",
                                                                    "kdeconnect.notification",
                                                                    "kdeconnect.ping",
                                                                    "kdeconnect.notification.reply",
                                                                    "kdeconnect.notification.action",
                                                                    "kdeconnect.share.request",
                                                                    "kdeconnect.bigscreen.stt",
                                                                    "kdeconnect.clipboard.connect",
                                                                    "kdeconnect.runcommand",
                                                                    "kdeconnect.connectivity_report.request",
                                                                    "kdeconnect.contacts.request_all_uids_timestamps",
                                                                    "kdeconnect.sms.request_conversations",
                                                                    "kdeconnect.telephony.request",
                                                                    "kdeconnect.mpris",
                                                                    "kdeconnect.sms.request_conversation",
                                                                    "kdeconnect.findmyphone.request",
                                                                    "kdeconnect.sms.request_attachment",
                                                                    "kdeconnect.systemvolume",
                                                                    "kdeconnect.mousepad.keyboardstate",
                                                                    "kdeconnect.sftp.request",
                                                                    "kdeconnect.share.request.update",
                                                                    "kdeconnect.notification.request",
                                                                    "kdeconnect.mousepad.request",
                                                                    "kdeconnect.photo.request",
                                                                    "kdeconnect.sms.request",
                                                                    "kdeconnect.contacts.request_vcards_by_uid",
                                                                    "kdeconnect.mpris.request",
                                                                    "kdeconnect.battery.request",
                                                                    "kdeconnect.clipboard"
                                                                  ],
                                                                  "outgoingCapabilities": [
                                                                    "kdeconnect.telephony",
                                                                    "kdeconnect.notification",
                                                                    "kdeconnect.contacts.response_uids_timestamps",
                                                                    "kdeconnect.ping",
                                                                    "kdeconnect.share.request",
                                                                    "kdeconnect.bigscreen.stt",
                                                                    "kdeconnect.clipboard.connect",
                                                                    "kdeconnect.connectivity_report",
                                                                    "kdeconnect.sftp",
                                                                    "kdeconnect.sms.attachment_file",
                                                                    "kdeconnect.systemvolume.request",
                                                                    "kdeconnect.sms.messages",
                                                                    "kdeconnect.mpris",
                                                                    "kdeconnect.findmyphone.request",
                                                                    "kdeconnect.mousepad.keyboardstate",
                                                                    "kdeconnect.contacts.response_vcards",
                                                                    "kdeconnect.notification.request",
                                                                    "kdeconnect.mousepad.echo",
                                                                    "kdeconnect.mousepad.request",
                                                                    "kdeconnect.presenter",
                                                                    "kdeconnect.photo",
                                                                    "kdeconnect.runcommand.request",
                                                                    "kdeconnect.mpris.request",
                                                                    "kdeconnect.battery",
                                                                    "kdeconnect.clipboard"
                                                                  ],
                                                                  "tcpPort": 1716,
                                                                  "tcpHost": "192.168.178.106"
                                                                }
                                                              }
Aug 22 13:58:13 org.gnome.Shell.Extensions.GSConnect[112166]: [/service/device.js:_readLoop:338]: DEVNAME: {
                                                                "id": 1629633365136,
                                                                "type": "kdeconnect.connectivity_report",
                                                                "body": {
                                                                  "signalStrengths": {
                                                                    "2": {
                                                                      "networkType": "LTE",
                                                                      "signalStrength": 3
                                                                    }
                                                                  }
                                                                }
                                                              }
Aug 22 13:58:17 org.gnome.Shell.Extensions.GSConnect[112166]: [/service/device.js:_readLoop:338]: DEVNAME: {
                                                                "id": 1629633365136,
                                                                "type": "kdeconnect.connectivity_report",
                                                                "body": {
                                                                  "signalStrengths": {
                                                                    "2": {
                                                                      "networkType": "LTE",
                                                                      "signalStrength": 2
                                                                    }
                                                                  }
                                                                }
                                                              }
Aug 22 13:58:17 org.gnome.Shell.Extensions.GSConnect[112166]: [/service/device.js:_readLoop:338]: DEVNAME: {
                                                                "id": 1629633496668,
                                                                "type": "kdeconnect.share.request",
                                                                "body": {
                                                                  "filename": "IMG.jpg",
                                                                  "lastModified": 1629631938000,
                                                                  "numberOfFiles": 1,
                                                                  "totalPayloadSize": 7172396
                                                                },
                                                                "payloadSize": 7172396,
                                                                "payloadTransferInfo": {
                                                                  "port": 1740
                                                                }
                                                              }
Aug 22 13:58:20 org.gnome.Shell.Extensions.GSConnect[112166]: [/service/device.js:_readLoop:338]: DEVNAME: {
                                                                "id": 1629633365136,
                                                                "type": "kdeconnect.connectivity_report",
                                                                "body": {
                                                                  "signalStrengths": {
                                                                    "2": {
                                                                      "networkType": "LTE",
                                                                      "signalStrength": 3
                                                                    }
                                                                  }
                                                                }
                                                              }
```

**Comment by andyholmes** [comment] 2021-08-22 20:54
Are there no errors in the log for the failed transfer? Without some error there's not much to help with here :/

**Comment by mgrewe** [comment] 2021-08-22 21:05
That is the strange thing. No, there is no error in the log. Can I increase the log level?

Am 22. August 2021 22:54:37 MESZ schrieb Andy Holmes ***@***.***>:

**Comment by andyholmes** [comment] 2021-08-22 22:07
Hmm, apparently real errors have been accidentally muted, sorry about that!

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/5d282f71fc3410f33438fd65d84379ba32d4d10a/src/service/plugins/share.js#L197-L208

I've opened #1158 which fixes that. If you can make that change to:

    ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/share.js

By adding `debug(e, this.device.name);` to `line #198` of `share.js`. Then run:

    touch ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js

That should restart the service without you needing to restart GNOME Shell. Then you should be able to get a proper error :)

**Comment by andyholmes** [comment] 2021-08-22 22:08
Alternatively, you can wait for the [CI to finish](https://github.com/GSConnect/gnome-shell-extension-gsconnect/actions/runs/1156643124) and install the Zip that creates :)

**Comment by mgrewe** [comment] 2021-08-23 06:40
Strange enough: After update of the extension it now works and the file is transferred successfully. However, I did a reset to the previous version and it also works now. I remember a similar situation some time ago where I thought the problem was solved after an update. It may be triggered after longer system uptime or by multiple suspends/resumes... I'll try to catch the error when it occurs again and open a new issue. Thanks a lot already!

**Comment by mgrewe** [comment] 2021-08-23 19:13
Ok, that was fast. I just got the error again after one day. Here is the relevant section from the log:

```
Aug 23 21:08:23 org.gnome.Shell.Extensions.GSConnect[1724]: [/service/device.js:_readLoop:338]: DEVICENAME: {
                                                              "id": 1629745701927,
                                                              "type": "kdeconnect.share.request",
                                                              "body": {
                                                                "filename": "IMG.jpg",
                                                                "lastModified": 1629705920000,
                                                                "numberOfFiles": 1,
                                                                "totalPayloadSize": 7254783
                                                              },
                                                              "payloadSize": 7254783,
                                                              "payloadTransferInfo": {
                                                                "port": 1750
                                                              }
                                                            }
Aug 23 21:08:25 org.gnome.Shell.Extensions.GSConnect[1724]: [/service/backends/lan.js:download:863]: DEVICENAME: Transfer incomplete
                                                            download@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:863:19
                                                            async*start@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:715:40
                                                            async*_handleFile@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/share.js:171:32
                                                            handlePacket@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/share.js:75:22
                                                            handlePacket@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:415:25
                                                            _readLoop@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:339:22
                                                            async*setChannel@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:320:18
                                                            _onChannel@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:225:20
                                                            channel@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                                                            _onIncomingChannel@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                                                            Async*@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2021-08-24 00:10
Okay, well that's more information at least :)

"Transfer incomplete" is our message error:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/c6e165a9d5bd5300aa223ab9b629d5e7ca30553a/src/service/backends/lan.js#L859-L867

So basically as a final check, we compare the number of bytes transferred with the number of bytes the device told us to expect. Here's what I'd recommend: keep the `if () {}` block, but replace the `throw ...` part (line 863-866) so that you have something like:

```js
if (transferredSize !== packet.payloadSize) { 
    debug(`Expected: ${packet.payloadSize}, Received: ${transferredSize}`);
}
```

This will ignore a size difference as an error, while still printing the numbers to the log. Then you can check the file by trying to open the image or using some JPEG corruption tester. If so that might indicate either GSConnect or KDE Connect is making a mistake regarding the size of the transfer.

You can do the same as before by just editing those lines in:

    ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js

And then using `touch` to restart the service:

    touch ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js

**Comment by mgrewe** [comment] 2021-08-25 14:28
Here is what I found:
The received file has 2692621 bytes which is exactly the same as the source on my mobile. I can also load and display it without problems using the Gnome Image viewer. 
And the relevant line from the log says
```Aug 25 16:21:23 org.gnome.Shell.Extensions.GSConnect[177252]: [/service/backends/lan.js:download:863]: "Expected: 2692205, Received: 2692621"```

Strange that it expected less.

**Comment by andyholmes** [comment] 2021-08-28 05:00
No, likely the cause is that Android is somehow getting an incorrect size.

The reason the error is being thrown is because GSConnect is being more careful than it has to be. Once it's done transferring the file, it double checks that the received size is what it was told to expect and any discrepancy is interpreted as corruption.

In reality KDE Connect clients just open a socket and dump whatever comes out into a file until the connection closes, so the "size" field is actually irrelevant. I guess the easiest way to deal with this is to just make it a warning instead of an error :thinking:

**Comment by andyholmes** [comment] 2021-08-28 05:23
Can you give this [test build](https://github.com/GSConnect/gnome-shell-extension-gsconnect/suites/3618719377/artifacts/87489976) a shot before I merge?

**Comment by mgrewe** [comment] 2021-08-30 18:44
Strange though that it first works after a fresh boot. Anyways, I'm currently testing and will let you know when the error appears again.

**Comment by mgrewe** [comment] 2021-09-01 19:02
This is now the second day without any error. I'm I right that your changes should report the "Extra Data"-Error into the log?

**Comment by andyholmes** [comment] 2021-09-01 23:05
I went ahead and merged; thanks for working through this! Feel free to re-open if we didn't fully squash the bug.

**Closed** 2021-09-01 23:04 UTC
Labels: needs info

**Comment by kowalcj0** [comment] 2021-09-25 20:57
Hi,
I'm having a similar problem, but in my case the size of received file actually do differ.

The size of file on the phone I chose for testing is **11677452** bytes
![Screenshot_20210925-212402_Total_Commander__01](https://user-images.githubusercontent.com/910451/134785430-06bead7d-d976-4549-a9fa-7040b8fdd2e0.png)

Same size shows up in the logcat:
```bash
sudo adb logcat --pid=$(adb shell pidof -s org.kde.kdeconnect_tp)
--------- beginning of main
09-25 21:27:42.864 20514 32110 D DirectShare: invoked
09-25 21:27:42.864 20514 32110 D DirectShare: carbon.local
09-25 21:27:45.897 20514  3584 I KDE/LanLink: Using port 1740
09-25 21:27:46.046 20514  3584 I KDE/LanLink: Beginning to send payload
09-25 21:27:47.506 20514  3584 I KDE/LanLink: Finished sending payload (11677452 bytes written)
09-25 21:30:34.766 20514 32107 W System  : A resource failed to call close. 
09-25 21:30:34.767 20514 32107 W System  : A resource failed to call close.
````

I've sent the same file couple of times and observed its size on receiving computer with:
```bash
watch -n 2 'stat --format="%s" PXL_20210920_155801865.jpg'
```
Every single time I've sent the file, its size was different:

- 11153408
- 9453568
- 9719808
- 10268672
- 10014720
- 9089024
- 10969088

That's anywhere from 500kB to 2.46MB difference.

I looked at the system log with `journalctl -f` and `journalctl /usr/bin/gnome-shell -f -o cat`, and not even a single entry for GSConnect, GJS, or gnome-shell was logged.

My setup:
* GSConnect 47 - I tried both the one from https://extensions.gnome.org/extension/1319/gsconnect/ and the latest version installed from git d0e66c5fe4e9b85f777feaa08dcaea93fd4b9163
* OnePlus 6 running LineageOS 18.1 Android 11
* Fedora 34 with Gnome 40.4.0
* gjs 1.68.4 (gjs-1.68.4-1.fc34.src.rpm)

**Comment by kowalcj0** [comment] 2021-09-25 21:56
After a bit more of reading I realised that I have to add extra iptables rules describe in Wiki  https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#iptables 
Once, I've added those rules to my Android firewall app `AFWall+` then everything started to work as expected :)

FYI: I you're using `AFWall+` then **PLEASE** read its tutorial on "Loading scripts from files" https://github.com/ukanth/afwall/wiki/CustomScripts#loading-scripts-from-files

In my case, I created a script called `gsconnect-iptables.sh` with following rules:

```shell
# Necessary at the beginning of each script!
IP6TABLES=/system/bin/ip6tables
IPTABLES=/system/bin/iptables
  # Open port 1714 to 1764 for GSConnect
$IPTABLES -I "afwall-wifi" -p udp --dport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
$IPTABLES -I "afwall-wifi" -p tcp --dport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
$IPTABLES -A "afwall-wifi" -p tcp --sport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
$IPTABLES -A "afwall-wifi" -p udp --sport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
```

Then I went to "Set custom script" option from the menu and specified the path to the script preceded by a dot command: 
```
. /path/to/gsconnect-iptables.sh
```

After going to airplane mode, I re-applied the firewall rules and turned the airplane mode off.
Since then, I haven't had any issues with file transfers :)
