### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by jcloss514** [GSConnect/gnome-shell-extension-gsconnect#1285] opened 2022-03-12 18:17 UTC
```
GSConnect: 47 (user)
GJS:       17190
Session:   x11
OS:        Ubuntu Jammy Jellyfish (development branch)

_loadBackends@/home/john/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/john/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/john/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/john/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/john/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-03-12 22:33
Duplicate of #1256

**Closed by andyholmes** 2022-03-12 22:33 UTC
Labels: duplicate, fixed in master
