### ISSUE TITLE
TLS support is not available

### ISSUE THREAD

**Issue by darth-crunchus** [GSConnect/gnome-shell-extension-gsconnect#1204] opened 2021-11-11 21:35 UTC
```
GSConnect: 47 (user)
GJS:       16702
Session:   x11
OS:        Pop!_OS 21.04

Gio.TlsCertificate.new_for_paths@/home/stephen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:352:31
_initCertificate@/home/stephen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:177:48
start@/home/stephen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/stephen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/home/stephen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/stephen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/stephen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/stephen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2021-12-01 23:15
Duplicate of #1057

**Closed by andyholmes** 2021-12-01 23:15 UTC
Labels: duplicate
