### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by Mariuszwb** [GSConnect/gnome-shell-extension-gsconnect#1429] opened 2022-07-31 12:23 UTC
```
GSConnect: 51 (user)
GJS:       17200
Session:   x11
OS:        Debian GNU/Linux 11 (bullseye)

_loadBackends@/home/maz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/maz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/maz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/maz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/maz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-08-02 22:03
Duplicate of #1256

**Closed by andyholmes** 2022-08-02 22:03 UTC
Labels: duplicate
