### ISSUE TITLE
Phone calls from PC

### ISSUE THREAD

**Issue by PrathamBhatTech** [GSConnect/gnome-shell-extension-gsconnect#1253] opened 2022-02-14 10:00 UTC
**Is your feature request related to a problem? Please describe.**
&emsp; It's frustrating to reach for my phone everytime I get a call while I'm wearing headphones.

**Describe the solution you'd like**
&emsp; Start and continue the call on PC similar to YourPhone on Windows

**Describe alternatives you've considered**
&emsp; There are alternatives like airdroid and siphon the call but it just looks like a pain for such a simple task and would like this feature to be integrated to gsconnect since it already has so many features making it look like its only missing the calling feature.

**System Details (please complete the following information):**
   - GSConnect version: 43
   - Installed from: extensions.gnome.org

**Comment by andyholmes** [comment] 2022-02-14 23:20
Duplicate of #575

**Closed by andyholmes** 2022-02-14 23:20 UTC
