### ISSUE TITLE
mount doesn't work

### ISSUE THREAD

**Issue by scalptob** [GSConnect/gnome-shell-extension-gsconnect#1731] opened 2024-01-21 04:40 UTC
### Describe the bug

clicking on mount in the menu fails. nothing happens the mount doesn't appear in nautilus 

### Steps to reproduce

click on the gnome menu
click on your connected device
new items appear in the menu
click on mount

### Expected behavior

a window to open with access to files of the device

### GSConnect version

50

### Installed from

OS package manager

### GNOME Shell version

42.9

### Paired device(s)

Samsung galaxy A5 2017

### KDE Connect app version

don't know, my screen is black

### Support log

```plain text
GSConnect: 50 (system)
GJS:       17202
Session:   wayland
OS:        Ubuntu 22.04.3 LTS
--------------------------------------------------------------------------------
janv. 21 05:00:37 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:00:37 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:00:37 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:00:37 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:00:37 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:00:37 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:00:37 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:00:39 dbus-daemon[1428]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.310' (uid=1000 pid=19054 comm="gjs /usr/share/gnome-shell/extensions/gsconnect@an" label="unconfined")
janv. 21 05:00:39 systemd[1]: Starting Hostname Service...
janv. 21 05:00:39 dbus-daemon[1428]: [system] Successfully activated service 'org.freedesktop.hostname1'
janv. 21 05:00:39 systemd[1]: Started Hostname Service.
janv. 21 05:01:05 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:01:05 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:01:05 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:01:05 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:01:05 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:01:05 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:01:05 gnome-shell[14755]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
janv. 21 05:01:08 org.gnome.Shell.Extensions.GSConnect[14840]: [/service/device.js:sendPacket:449]: Galaxy A5(2017): {
                                                                 "id": 1705809668151,
                                                                 "type": "kdeconnect.sftp.request",
                                                                 "body": {
                                                                   "startBrowsing": true
                                                                 }
                                                               }
janv. 21 05:01:08 org.gnome.Shell.Extensions.GSConnect[14840]: [/service/device.js:_readLoop:341]: Galaxy A5(2017): {
                                                                 "id": 1705809667946,
                                                                 "type": "kdeconnect.sftp",
                                                                 "body": {
                                                                   "ip": "192.168.1.85",
                                                                   "port": 1739,
                                                                   "user": "kdeconnect",
                                                                   "password": "YYAmVfpgcUGh6qxwK1976OyrqOV0",
                                                                   "path": "/WhatsApp_Media",
                                                                   "multiPaths": [
                                                                     "/WhatsApp_Media"
                                                                   ],
                                                                   "pathNames": [
                                                                     "WhatsApp_Media"
                                                                   ]
                                                                 }
                                                               }
janv. 21 05:01:08 gjs[14840]: JS ERROR: Galaxy A5(2017): Gio.IOErrorEnum: La connexion a échoué
                              _handleMount/</<@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                              @/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
janv. 21 05:01:09 systemd[1]: systemd-hostnamed.service: Deactivated successfully.
```

**Comment by EthanZeigler** [comment] 2024-02-01 15:06
I've had a similar issue with mounting. The device in my case does actually appear, but any attempt to read the contents of the mount leads to a permission denied error.
![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/9123320/f197b5e4-7db0-4afe-97da-b42c1949f746)

**Comment by retrixe** [comment] 2024-02-25 18:16
Possible duplicate of #1610 and/or #1203

**Comment by andyholmes** [comment] 2024-03-01 23:57
Closing as a duplicate of #1610

**Closed by andyholmes** 2024-03-01 23:57 UTC
Labels: duplicate
