### ISSUE TITLE
No JS module 'tweener' found in search path

### ISSUE THREAD

**Issue by frusanov** [GSConnect/gnome-shell-extension-gsconnect#1037] opened 2021-01-03 18:18 UTC
**Describe the bug**

Can't activate GSConnect installed from GNOME Extensions Website.
Shows error `No JS module 'tweener' found in search path`

**Steps To Reproduce:**

Just install extension from GNOME Extensions Website

**Screenshots**

![Screenshot from 2021-01-03 21-12-13](https://user-images.githubusercontent.com/16781326/103485582-666c2380-4e08-11eb-9c06-f3f72c5507f7.png)

**Support Log**

```

GSConnect: 44 (user)
GJS:       16601
Session:   x11
OS:        Ubuntu 20.10
--------------------------------------------------------------------------------
-- Logs begin at Sat 2021-01-02 14:22:21 MSK, end at Sun 2021-01-03 21:16:48 MSK. --
янв 03 21:16:45 dbus-daemon[1864]: [session uid=1000 pid=1864] Activating via systemd: service name='org.freedesktop.Tracker1' unit='tracker-store.service' requested by ':1.2' (uid=1000 pid=1860 comm="/usr/libexec/tracker-miner-fs " label="unconfined")
янв 03 21:16:45 systemd[1848]: Starting Tracker metadata database store and lookup manager...
янв 03 21:16:45 dbus-daemon[1864]: [session uid=1000 pid=1864] Successfully activated service 'org.freedesktop.Tracker1'
янв 03 21:16:45 systemd[1848]: Started Tracker metadata database store and lookup manager.
янв 03 21:16:45 dbus-daemon[1864]: [session uid=1000 pid=1864] Activating via systemd: service name='org.freedesktop.Tracker1.Miner.Extract' unit='tracker-extract.service' requested by ':1.2' (uid=1000 pid=1860 comm="/usr/libexec/tracker-miner-fs " label="unconfined")
янв 03 21:16:45 systemd[1848]: Starting Tracker metadata extractor...
янв 03 21:16:45 tracker-extract[12772]: Set scheduler policy to SCHED_IDLE
янв 03 21:16:45 tracker-extract[12772]: Setting priority nice level to 19
янв 03 21:16:45 dbus-daemon[1864]: [session uid=1000 pid=1864] Successfully activated service 'org.freedesktop.Tracker1.Miner.Extract'
янв 03 21:16:45 systemd[1848]: Started Tracker metadata extractor.
янв 03 21:16:46 dbus-daemon[1064]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.159' (uid=1000 pid=12756 comm="gjs /home/frusanov/.local/share/gnome-shell/extens" label="unconfined")
янв 03 21:16:46 systemd[1]: Starting Hostname Service...
янв 03 21:16:46 dbus-daemon[1064]: [system] Successfully activated service 'org.freedesktop.hostname1'
янв 03 21:16:46 systemd[1]: Started Hostname Service.
янв 03 21:16:48 gjs[12756]: ../../../gobject/gsignal.c:2731: instance '0x55a67dc25270' has no handler with id '8881'
янв 03 21:16:48 gjs[12756]: ../../../gobject/gsignal.c:2731: instance '0x55a67dc25270' has no handler with id '7021'
```

**System Details (please complete the following information):**

 - **GSConnect version:** 44
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.38
 - **Distro/Release:** Ubuntu 20.10

**Additional Notes:**

Extension built  from repo works fine

**Comment by andyholmes** [comment] 2021-01-16 04:45
Tweener usage was removed in v40, so you probably have some old files lying around or also have GSConnect installed from apt.

**Comment by locness3** [comment] 2021-03-07 13:23
Why is the apt version so out-of-date?

**Comment by andyholmes** [comment] 2021-03-07 23:46
The apt version is not maintained by the project, so you will have to ask your distribution.

**Comment by xpseudonym** [comment] 2021-08-18 07:14
Hi, I'm posting here because I'm guessing it's the right place - but, it may not be...
* GSConnect version is 28 (hmm, perhaps I should update...)
* GNOME version is 3.38.5

I have GSConnect installed manually as described here: https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1049#issuecomment-775576744 Thanks @andyholmes :)
And, I've just moved from Debian 10 to PureOS;
And, I *seem to be* getting this bug as the screenshot shows in the above OP.
So, the question is, is it the manual install to `/usr/local`, the move to PureOS or the removal of Tweener in v40 that might be causing this?
Or, perhaps is all of them...?

**Comment by xpseudonym** [comment] 2021-08-19 10:48
Updated to v47 and problem solved

**Comment by andyholmes** [comment] 2021-12-01 22:57
Closing since this bug seems to have been caused by a broken install and was reported against a now unsupported version.

**Closed by andyholmes** 2021-12-01 22:57 UTC
