### ISSUE TITLE
TLS support is not available

### ISSUE THREAD

**Issue by icymankr** [GSConnect/gnome-shell-extension-gsconnect#1226] opened 2021-12-27 23:47 UTC
```
GSConnect: 47 (user)
GJS:       16405
Session:   x11
OS:        Ubuntu 20.04.3 LTS

Gio.TlsCertificate.new_for_paths@/home/icyman/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:352:31
_initCertificate@/home/icyman/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:177:48
start@/home/icyman/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/icyman/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/home/icyman/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/icyman/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/icyman/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/icyman/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2021-12-28 03:33
Duplicate of #1054

**Closed by andyholmes** 2021-12-28 03:33 UTC
Labels: duplicate
