### ISSUE TITLE
Gio.TlsCertificate.new_from_files is not a function

### ISSUE THREAD

**Issue by sektorcoder** [GSConnect/gnome-shell-extension-gsconnect#1327] opened 2022-04-09 16:48 UTC
```
GSConnect: 49 (user)
GJS:       17002
Session:   x11
OS:        Arch Linux

Gio.TlsCertificate.new_for_paths@/home/sector/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:352:31
_initCertificate@/home/sector/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:177:48
start@/home/sector/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/sector/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:255:25
start@/home/sector/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:458:14
vfunc_startup@/home/sector/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/sector/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/sector/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-08-03 00:03
Probably yet another duplicate of #1209

**Closed by andyholmes** 2022-08-03 00:03 UTC
Labels: duplicate
