### ISSUE TITLE
File system mouting doesn't work at all from 1.31.1

### ISSUE THREAD

**Issue by realKarthikNair** [GSConnect/gnome-shell-extension-gsconnect#1827] opened 2024-06-18 08:24 UTC
### Describe the bug

Fs mount doesnt work at all from 1.31.1
https://f-droid.org/packages/org.kde.kdeconnect_tp/

### GSConnect version

57

### Installed from

GNOME Extensions website

### GNOME Shell version

GNOME 46.2

### Linux distribution/release

Fedora Linux 40 (Workstation Edition) x86_64

### Paired device(s)

RMX2193

### KDE Connect app version

1.31.1

**Comment by cleanerspam** [comment] 2024-06-19 06:51
I am also facing this issue on Arch Linux , problem is not with the Android or Wifi because it was working fine when i was using KDEConnect on Plasma , also kdeconnect is not installed so it cant be blamed for interfernce

**Comment by ferdnyc** [comment] 2024-06-21 06:13
Closing as duplicate of #1203 (which is pinned, and which I've just reopened). Mounting definitely still has known issues.

**Closed by ferdnyc** 2024-06-21 06:13 UTC
Labels: triage
