### ISSUE TITLE
Clipbaord sharing, presentation controller option and filesystem doesn't work

### ISSUE THREAD

**Issue by soumyaDghosh** [GSConnect/gnome-shell-extension-gsconnect#1691] opened 2023-10-16 12:09 UTC
### Describe the bug

Since I upgraded to my new phone with Android 13, MIUI 14, Kde Connect doesn't share the Clipboard any more, even it doesn't work when manually sending clipboard. And I have also lost the option to controll presentation from my phone. Also, when I mount my phone via sftp, I cannot open my file system, it says, I don't have access/permission to my `/` filesystem.
![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/72045785/df554385-6976-4160-bf00-ff0c5841f211)

### GSConnect version

55

### Installed from

GNOME Extensions website

### GNOME Shell version

GNOME Shell 44.3

### Linux distribution/release

Ubuntu 23.04 Lunar Lobster

### Paired device(s)

Poco X5 5G

### KDE Connect app version

1.29.0

### Plugin(s)

Presentation Control, Filesystem Expose

**Comment by soumyaDghosh** [comment] 2023-10-16 18:44
Thanks, the clipboard thing is working, but still I require to manually send the clipboard. It's not automatically sent. And yes, filesystem thing is working with the workaround. But can't find any thing on the presentation option.

**Comment by rezazarchi** [comment] 2023-11-12 08:39
I have same issues plus, Media control of mobile music player doesn't remain in ubuntu notifications (I mentioned [here](https://bugs.kde.org/show_bug.cgi?id=475955))

**Comment by SP-XD** [comment] 2024-02-11 08:38
I am on Android 14, and it works after Turning on keyboard receiver plugin and other kde connect permissions 

![Screenshot_2024-02-11-14-07-19-049_com miui securitycenter](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/69642436/25c2abac-ba77-435b-a337-2c920c0809bb)

**Comment by andyholmes** [comment] 2024-03-02 00:03
Please restrict reports to a single issue.

Closing as a duplicate of #1610, since this is the only issue I recognize.

**Closed by andyholmes** 2024-03-02 00:03 UTC
Labels: can't fix, needs info
