### ISSUE TITLE
GSConnect will not mount

### ISSUE THREAD

**Issue by jackmonty** [GSConnect/gnome-shell-extension-gsconnect#1174] opened 2021-09-24 02:38 UTC
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

When attempting to use the 'Mount' feature from either the system menu or the GSConnect extension dialog, nothing happens; the device remains unmounted and no indication that an error has occurred is displayed.

**Steps To Reproduce:**

1. Go to 'System Menu'
2. Click on 'Pixel 5'
3. Click on 'Mount'
4. Device remains unmounted and no error is displayed

**Expected behavior**

Gnome Files (a.k.a. Nautilus) opens and displays the mounted device files, as configured within 'Filesytem Expose'.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
GSConnect: 47 (system)
GJS:       16804
Session:   x11
OS:        Fedora 34
--------------------------------------------------------------------------------
-- Journal begins at Mon 2021-04-19 07:41:41 CDT, ends at Thu 2021-09-23 21:28:02 CDT. --
Sep 23 21:27:43 daemon.js[2734]: JS ERROR: Pixel 5: Gio.IOErrorEnum: Host key verification failed
                                 _handleMount/</<@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                                 @/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Sep 23 21:28:02 org.gnome.Shell.Extensions.GSConnect[2734]: [/service/device.js:sendPacket:446]: Pixel 5: {
                                                              "id": 1632450482671,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }
Sep 23 21:28:02 org.gnome.Shell.Extensions.GSConnect[2734]: [/service/device.js:_readLoop:338]: Pixel 5: {
                                                              "id": 1632450483094,
                                                              "type": "kdeconnect.sftp",
                                                              "body": {
                                                                "ip": "10.0.1.72",
                                                                "port": 1752,
                                                                "user": "kdeconnect",
                                                                "password": "FbQPTutH3HvUMQqSXkKhTyYsY2eD",
                                                                "path": "/",
                                                                "multiPaths": [
                                                                  "/Audiobooks",
                                                                  "/Download",
                                                                  "/Music_OGG"
                                                                ],
                                                                "pathNames": [
                                                                  "Audiobooks",
                                                                  "Download",
                                                                  "Music_OGG"
                                                                ]
                                                              }
                                                            }
Sep 23 21:28:02 daemon.js[2734]: JS ERROR: Pixel 5: Gio.IOErrorEnum: Host key verification failed
                                 _handleMount/</<@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                                 @/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**System Details (please complete the following information):**

 - **GSConnect version:** 47
   - **Installed from:** Fedora DNF
 - **GNOME/Shell version:** 40
 - **Distro/Release:** Fedora 34

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Pixel 5
 - **KDE Connect app version:** ?? (It is not installed by my package manager.)
 - **Plugin(s):** Filesystem Expose.

**Additional Notes:**

Nil.

**Comment by nttrock** [comment] 2021-10-03 07:53
I'm having the same identical issue.

OS: Arch Linux

Log is basically identical to the one seen here.

**Comment by morganhjk** [comment] 2021-10-03 13:23
@nttrock Since you're on Arch, you're probably using [OpenSSH 8.8](https://www.openssh.com/txt/release-8.8) which was released a week ago. This version disables the `ssh-rsa` host key signature algorithm by default (which uses SHA-1, now considered cryptographically broken).

It looks like the KDEConnect Android app is [using](https://github.com/KDE/kdeconnect-android/blob/master/build.gradle#L177) a version of the Apache SSHD java library from [2015](https://github.com/apache/mina-sshd/releases/tag/sshd-0.14.0), which I'm guessing only supports the `ssh-rsa` algorithm (or at least not supporting any of the current host key signature algorithms used by default in OpenSSH).

By adding the following to my `~/.ssh/config` I was able to mount via GSConnect again:
```
Host 10.94.0.*
    HostKeyAlgorithms +ssh-rsa
```
I didn't want to re-enable `ssh-rsa` for all hosts, so I limited it to the DHCP range in my home network.

I also tried with `Match user kdeconnect` instead of `Host 10.94.0.*`, but that only worked if I used `sftp` or `gio mount sftp://kdeconnect@<ip>:<port>/` manually and not with GSConnect.

**Comment by suchinton** [comment] 2021-10-17 10:41
Same issue on endeavour os gnome 40.5

**Comment by Archytino** [comment] 2021-10-18 09:53
Arch linux, 5.14.12-zen1-1-zen kernel, gnome 40.5 same issue.

I tried kdeconnect witch plasma desktop and works fine.

**Comment by S0llarCode** [comment] 2022-01-06 11:20
Go to `~/.ssh/config` and add :
```
Host *
	HostKeyAlgorithms +ssh-rsa
```
Mount your device :
```
1.     Go to 'System Menu'
2.     Click on 'my-device-name'
3.     Click on 'Mount'
```
Go to `~/.ssh/known_hosts` and get the IP of your phone, it's the same like displayed on nautilus when it's connected.
_It would be greet to display the name of the phone instead of his IP._

Go to `~/.ssh/config` and edit :
```
Host #YOUR_PHONE_IP
	HostKeyAlgorithms +ssh-rsa
```
It's works for me on Arch Linux (Manjaro Gnome).

**Comment by dudumartins** [comment] 2022-01-13 04:57
> Go to `~/.ssh/config` and add :
> 
> ```
> Host *
> 	HostKeyAlgorithms +ssh-rsa
> ```
> 
> Mount your device :
> 
> ```
> 1.     Go to 'System Menu'
> 2.     Click on 'my-device-name'
> 3.     Click on 'Mount'
> ```
> 
> Go to `~/.ssh/known_hosts` and get the IP of your phone, it's the same like displayed on nautilus when it's connected. _It would be greet to display the name of the phone instead of his IP._
> 
> Go to `~/.ssh/config` and edit :
> 
> ```
> Host #YOUR_PHONE_IP
> 	HostKeyAlgorithms +ssh-rsa
> ```
> 
> It's works for me on Arch Linux (Manjaro Gnome).

Thank you so much... It really works for me on Arch LInux

**Comment by ferdnyc** [comment] 2022-01-16 16:40
@S0llarCode 
> It would be greet to display the name of the phone instead of his IP.

No argument, unfortunately I think that would require the phone's name either be registered in the system's hostname list, or discoverable via Avahi. 

The latter is probably unworkable given Android's... everything. (It would _also_ require KDE Connect app support, but I don't think it's even worth pursuing really.) 

The former might be possible, if the user assigns a static IP for the device on their local network and manually adds it to `/etc/hosts`. 

(Right now the hostname wouldn't show up _even if_ that were done, because GSConnect always uses the IP to refer to the device. But that's something we theoretically have the ability to change, if we see that a hostname is available for the IP.)

I don't think there's any way we could _register_ a name on behalf of the user, though. (But I'm happy to be proved wrong about that, if someone can think of a way to do it via Gio/GNOME APIs.)

**Comment by andyholmes** [comment] 2022-08-02 22:17
Closing as a duplicate of #1203, which had the earliest comment with a solution. Thanks for reporting!

**Closed by andyholmes** 2022-08-02 22:17 UTC
Labels: duplicate
