### ISSUE TITLE
No JS module 'connectivity_report' found in search path

### ISSUE THREAD

**Issue by ajsenko5** [GSConnect/gnome-shell-extension-gsconnect#1474] opened 2022-09-30 04:33 UTC
```
GSConnect: 51 (user)
GJS:       16602
Session:   wayland
OS:        Debian GNU/Linux 11 (bullseye)

_loadPlugin@/home/adam/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:955:17
_loadPlugins@/home/adam/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:987:28
async*_init@/home/adam/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:125:18
_loadDevices@/home/adam/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:265:28
start@/home/adam/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:453:14
vfunc_startup@/home/adam/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/adam/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/adam/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-10-08 19:27
Duplicate of #1184

**Closed by andyholmes** 2022-10-08 19:27 UTC
Labels: duplicate
