### ISSUE TITLE
/(?:cn|CN) ?= ?([^,\n]*)/.exec(...) is null

### ISSUE THREAD

**Issue by hemi-SX** [GSConnect/gnome-shell-extension-gsconnect#1453] opened 2022-09-06 08:04 UTC
```
GSConnect: 50 (user)
GJS:       17202
Session:   x11
OS:        Ubuntu 22.04.1 LTS

get@/home/hemi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:393:64
_initCertificate@/home/hemi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:182:13
start@/home/hemi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/hemi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:255:25
start@/home/hemi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:458:14
vfunc_startup@/home/hemi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/hemi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/hemi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2024-03-03 17:50
Closing as a duplicate of #1209

**Closed by andyholmes** 2024-03-03 17:50 UTC
Labels: triage
