### ISSUE TITLE
requested SMS not displayed in window

### ISSUE THREAD

**Issue by jeff-zimmerman** [GSConnect/gnome-shell-extension-gsconnect#1388] opened 2022-06-10 23:03 UTC
Messages do not appear properly in messaging window, even when shown in support logs. The contacts shown in the messaging dialog are often different on each launch of the app and new messages are rarely shown. Sent messages rarely succeed in sending and are never shown in the dialog.

**Steps To Reproduce:**

1. Open messaging.
2. Send messages

**Expected behavior**

A view of all messages sent with all contacts.

**Screenshots**

![Screenshot from 2022-06-10 18-02-57](https://user-images.githubusercontent.com/66034858/173159016-0fe81077-b9a8-410c-a4cd-fb0aca49dfe4.png)

![Screenshot from 2022-06-10 18-38-37](https://user-images.githubusercontent.com/66034858/173159281-0481b8b4-dfa2-480d-a3d9-e998cccd3aad.png)

**Support Log**

Much has been left out, as this generated 9,500 lines over the course of 1 minute 30 seconds.

```
GSConnect: 50 (user)
GJS:       17200
Session:   wayland
OS:        Ubuntu 22.04 LTS
--------------------------------------------------------------------------------
Jun 10 18:00:13 dbus-daemon[1845]: [session uid=1000 pid=1845] Monitoring connection :1.233 closed.
Jun 10 18:00:13 gnome-shell[2005]: JS ERROR: TypeError: malformed UTF-8 character sequence at offset 0
Jun 10 18:00:13 gnome-shell[2005]: JS ERROR: TypeError: malformed UTF-8 character sequence at offset 0
Jun 10 18:00:13 dbus-daemon[1845]: [session uid=1000 pid=1845] Activating service name='org.gnome.Shell.Extensions.GSConnect' requested by ':1.37' (uid=1000 pid=2005 comm="/usr/bin/gnome-shell ")
Jun 10 18:00:13 dbus-daemon[1845]: [session uid=1000 pid=1845] Successfully activated service 'org.gnome.Shell.Extensions.GSConnect'
Jun 10 18:00:14 dbus-daemon[1845]: [session uid=1000 pid=1845] Connection :1.242 (uid=1000 pid=14861 comm="gjs /home/jazimmerman/.local/share/gnome-shell/ext") became a monitor.

Jun 10 18:00:23 gjs[14883]: ../../../gobject/gsignal.c:2731: instance '0x563b660e2140' has no handler with id '8676'
Jun 10 18:00:23 gjs[14883]: ../../../gobject/gsignal.c:2731: instance '0x563b660e2140' has no handler with id '6698'

Jun 10 18:00:38 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898438219,
                                                               "type": "kdeconnect.contacts.request_all_uids_timestamps",
                                                               "body": {}
                                                             }
Jun 10 18:00:38 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898438266,
                                                               "type": "kdeconnect.sms.request_conversations",
                                                               "body": {}
                                                             }
Jun 10 18:00:41 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898441130,
                                                               "type": "kdeconnect.contacts.request_all_uids_timestamps",
                                                               "body": {}
                                                             }
Jun 10 18:00:41 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898441139,
                                                               "type": "kdeconnect.sms.request_conversations",
                                                               "body": {}
                                                             }
Jun 10 18:00:43 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898443642,
                                                               "type": "kdeconnect.contacts.request_all_uids_timestamps",
                                                               "body": {}
                                                             }
Jun 10 18:00:43 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898443642,
                                                               "type": "kdeconnect.sms.request_conversations",
                                                               "body": {}
                                                             }

Jun 10 18:00:52 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898452031,
                                                               "type": "kdeconnect.contacts.request_all_uids_timestamps",
                                                               "body": {}
                                                             }
Jun 10 18:00:52 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898452078,
                                                               "type": "kdeconnect.sms.request_conversations",
                                                               "body": {}
                                                             }
Jun 10 18:00:55 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898454992,
                                                               "type": "kdeconnect.contacts.request_all_uids_timestamps",
                                                               "body": {}
                                                             }
Jun 10 18:00:55 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898455001,
                                                               "type": "kdeconnect.sms.request_conversations",
                                                               "body": {}
                                                             }
Jun 10 18:01:01 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898461145,
                                                               "type": "kdeconnect.sms.request",
                                                               "body": {
                                                                 "sendSms": true,
                                                                 "phoneNumber": "305-965-1125",
                                                                 "messageBody": "asdf"
                                                               }
                                                             }
Jun 10 18:01:02 systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Jun 10 18:01:07 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/backends/lan.js:_onIdentity:343]: {
                                                               "id": 1654898468159,
                                                               "type": "kdeconnect.identity",
                                                               "body": {
                                                                 "deviceId": "c28f247b5cbe07e7",
                                                                 "deviceName": "jeffsphone!",
                                                                 "protocolVersion": 7,
                                                                 "deviceType": "phone",
                                                                 "incomingCapabilities": [
                                                                   "kdeconnect.telephony.request_mute",
                                                                   "kdeconnect.notification",
                                                                   "kdeconnect.ping",
                                                                   "kdeconnect.notification.reply",
                                                                   "kdeconnect.notification.action",
                                                                   "kdeconnect.share.request",
                                                                   "kdeconnect.bigscreen.stt",
                                                                   "kdeconnect.clipboard.connect",
                                                                   "kdeconnect.runcommand",
                                                                   "kdeconnect.connectivity_report.request",
                                                                   "kdeconnect.contacts.request_all_uids_timestamps",
                                                                   "kdeconnect.sms.request_conversations",
                                                                   "kdeconnect.telephony.request",
                                                                   "kdeconnect.mpris",
                                                                   "kdeconnect.sms.request_conversation",
                                                                   "kdeconnect.findmyphone.request",
                                                                   "kdeconnect.sms.request_attachment",
                                                                   "kdeconnect.systemvolume",
                                                                   "kdeconnect.mousepad.keyboardstate",
                                                                   "kdeconnect.sftp.request",
                                                                   "kdeconnect.share.request.update",
                                                                   "kdeconnect.notification.request",
                                                                   "kdeconnect.mousepad.request",
                                                                   "kdeconnect.photo.request",
                                                                   "kdeconnect.sms.request",
                                                                   "kdeconnect.contacts.request_vcards_by_uid",
                                                                   "kdeconnect.mpris.request",
                                                                   "kdeconnect.battery.request",
                                                                   "kdeconnect.battery",
                                                                   "kdeconnect.clipboard"
                                                                 ],
                                                                 "outgoingCapabilities": [
                                                                   "kdeconnect.telephony",
                                                                   "kdeconnect.notification",
                                                                   "kdeconnect.contacts.response_uids_timestamps",
                                                                   "kdeconnect.ping",
                                                                   "kdeconnect.share.request",
                                                                   "kdeconnect.bigscreen.stt",
                                                                   "kdeconnect.clipboard.connect",
                                                                   "kdeconnect.connectivity_report",
                                                                   "kdeconnect.sftp",
                                                                   "kdeconnect.sms.attachment_file",
                                                                   "kdeconnect.systemvolume.request",
                                                                   "kdeconnect.sms.messages",
                                                                   "kdeconnect.mpris",
                                                                   "kdeconnect.findmyphone.request",
                                                                   "kdeconnect.mousepad.keyboardstate",
                                                                   "kdeconnect.contacts.response_vcards",
                                                                   "kdeconnect.notification.request",
                                                                   "kdeconnect.mousepad.echo",
                                                                   "kdeconnect.mousepad.request",
                                                                   "kdeconnect.presenter",
                                                                   "kdeconnect.photo",
                                                                   "kdeconnect.runcommand.request",
                                                                   "kdeconnect.mpris.request",
                                                                   "kdeconnect.battery.request",
                                                                   "kdeconnect.battery",
                                                                   "kdeconnect.clipboard"
                                                                 ],
                                                                 "tcpPort": 1716,
                                                                 "tcpHost": "192.168.1.233"
                                                               }
                                                             }
Jun 10 18:01:13 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:_readLoop:341]: jeffsphone!: {
                                                               "id": 1654898474553,
                                                               "type": "kdeconnect.notification",
                                                               "body": {
                                                                 "id": "0|xyz.klinker.messenger|-1823129367|null|10303",
                                                                 "isCancel": true
                                                               }
                                                             }
Jun 10 18:01:15 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:_readLoop:341]: jeffsphone!: {
                                                               "id": 1654898476563,
                                                               "type": "kdeconnect.sms.messages",
                                                               "body": {
                                                                 "messages": [
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+13059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Martha! We love you. ",
                                                                     "date": 1654898272331,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19696,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   }
                                                                 ],
                                                                 "version": 2
                                                               }
                                                             }

Jun 10 18:01:20 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:_readLoop:341]: jeffsphone!: {
                                                               "id": 1654898481343,
                                                               "type": "kdeconnect.sms.messages",
                                                               "body": {
                                                                 "messages": [
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+13059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Martha! We love you. ",
                                                                     "date": 1654898272331,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19696,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   }
                                                                 ],
                                                                 "version": 2
                                                               }
                                                             }
Jun 10 18:01:20 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:_readLoop:341]: jeffsphone!: {
                                                               "id": 1654898481668,
                                                               "type": "kdeconnect.sms.messages",
                                                               "body": {
                                                                 "messages": [
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+13059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Martha! We love you. ",
                                                                     "date": 1654898272331,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19696,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "3059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Actually Martha is an angel",
                                                                     "date": 1654898256123,
                                                                     "type": 2,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19695,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+15612034016"
                                                                       }
                                                                     ],
                                                                     "body": "My plans down south fell through. If you don't have anyone else to take you, i could throw you 10$for an uber? ",
                                                                     "date": 1654898192348,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 278,
                                                                     "_id": 19694,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+13059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Are they saying \"too bad, so sad?\" ",
                                                                     "date": 1654897982529,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19693,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "3059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Yep",
                                                                     "date": 1654897956047,
                                                                     "type": 2,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19692,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+13059651125"
                                                                       }
                                                                     ],
                                                                     "body": "For those blood tests? ",
                                                                     "date": 1654897671978,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19691,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   }
                                                                 ],
                                                                 "version": 2
                                                               }
                                                             }
Jun 10 18:01:20 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898480714,
                                                               "type": "kdeconnect.sms.request_conversation",
                                                               "body": {
                                                                 "threadID": "278"
                                                               }
                                                             }
Jun 10 18:01:21 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:_readLoop:341]: jeffsphone!: {
                                                               "id": 1654898482002,
                                                               "type": "kdeconnect.sms.messages",
                                                               "body": {
                                                                 "messages": [
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+15612034016"
                                                                       }
                                                                     ],
                                                                     "body": "Lol sure!",
                                                                     "date": 1654898481013,
                                                                     "type": 2,
                                                                     "read": 1,
                                                                     "thread_id": 278,
                                                                     "_id": 19697,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+13059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Martha! We love you. ",
                                                                     "date": 1654898272331,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19696,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   }
                                                                 ],
                                                                 "version": 2
                                                               }
                                                             }
Jun 10 18:01:21 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898481021,
                                                               "type": "kdeconnect.sms.request_conversation",
                                                               "body": {
                                                                 "threadID": "278"
                                                               }
                                                             }
Jun 10 18:01:21 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:_readLoop:341]: jeffsphone!: {
                                                               "id": 1654898482274,
                                                               "type": "kdeconnect.sms.messages",
                                                               "body": {
                                                                 "messages": [
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+15612034016"
                                                                       }
                                                                     ],
                                                                     "body": "Lol sure!",
                                                                     "date": 1654898481013,
                                                                     "type": 2,
                                                                     "read": 1,
                                                                     "thread_id": 278,
                                                                     "_id": 19697,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+13059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Martha! We love you. ",
                                                                     "date": 1654898272331,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19696,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "3059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Actually Martha is an angel",
                                                                     "date": 1654898256123,
                                                                     "type": 2,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19695,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+15612034016"
                                                                       }
                                                                     ],
                                                                     "body": "My plans down south fell through. If you don't have anyone else to take you, i could throw you 10$for an uber? ",
                                                                     "date": 1654898192348,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 278,
                                                                     "_id": 19694,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+13059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Are they saying \"too bad, so sad?\" ",
                                                                     "date": 1654897982529,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19693,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "3059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Yep",
                                                                     "date": 1654897956047,
                                                                     "type": 2,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19692,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+13059651125"
                                                                       }
                                                                     ],
                                                                     "body": "For those blood tests? ",
                                                                     "date": 1654897671978,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19691,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   }
                                                                 ],
                                                                 "version": 2
                                                               }
                                                             }

Jun 10 18:01:21 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:_readLoop:341]: jeffsphone!: {
                                                               "id": 1654898482548,
                                                               "type": "kdeconnect.sms.messages",
                                                               "body": {
                                                                 "messages": [
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+15612034016"
                                                                       }
                                                                     ],
                                                                     "body": "Lol sure!",
                                                                     "date": 1654898481013,
                                                                     "type": 2,
                                                                     "read": 1,
                                                                     "thread_id": 278,
                                                                     "_id": 19697,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+13059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Martha! We love you. ",
                                                                     "date": 1654898272331,
                                                                     "type": 1,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19696,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "3059651125"
                                                                       }
                                                                     ],
                                                                     "body": "Actually Martha is an angel",
                                                                     "date": 1654898256123,
                                                                     "type": 2,
                                                                     "read": 1,
                                                                     "thread_id": 16,
                                                                     "_id": 19695,
                                                                     "sub_id": -1,
                                                                     "event": 1
                                                                   },
                                                                   {
                                                                     "addresses": [
                                                                       {
                                                                         "address": "+15612034016"
                                                                       }
                                                                     ],
                                                                     "body": "My plans down south fell through. If you don't have anyone else to take you, i could throw you 10$for an uber? ",
Jun 10 18:01:33 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:_readLoop:341]: jeffsphone!: {
                                                               "id": 1654898494123,
                                                               "type": "kdeconnect.contacts.response_uids_timestamps",
                                                               "body": {
                                                                 "3884i12dd68a38cc76618.3789r427-3C2A2E405A4438464C504644": 1654856775079,
                                                                 "3884ib7bd2638ba5f6bc.3789r437-2E46524E3A445A464E3A": 1654856770684,
                                                                 "3884i5445623c0cff651d.3789r399-2A4032584E3A50522A3A44": 1654856773002,
                                                                 "3884i335aa197089fccff": 1654856764547,
                                                                 "3884i56a81e390a755e2a": 1654856776851,
                                                                 "3884i1f3f1d848b50f527.3789r522-5A463240402A484E2E38324C": 1654856767479,
                                                                 "3884i409e685b09a32c2c": 1654856776601,
                                                                 "3884i4454d9198e8f8b3a.3789r727-3E2A5A402A42464C362A44": 1654856775059,
                                                                 "3884i5846c4a8dea9562": 1654856771162,
                                                                 "3884ib8dab560e9be630.3789r409-3C46322E4644443240405A": 1654856775101,
                                                                 "3884i53fd488d8908ea91.3789r726-2A484C3A4038464630": 1654856778395,
                                                                 "3884i2919c0128ec82e6d.3789r472-36324C342A2E32": 1654856769703,
                                                                 "3884i62fa77098f6abb77.3789r500-2C4C3A2A44": 1654856778838,
                                                                 "3884i103d68418844576c": 1654856764313,
                                                                 "3884i7fea14f68f19931b.3789r517-3C522A442E3846464646464646464646": 1654856772961,
                                                                 ]
                                                               }
                                                             }
Jun 10 18:01:33 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898493126,
                                                               "type": "kdeconnect.sms.request_conversation",
                                                               "body": {
                                                                 "threadID": "10"
                                                               }
                                                             }
Jun 10 18:01:33 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898493127,
                                                               "type": "kdeconnect.sms.request_conversation",
                                                               "body": {
                                                                 "threadID": "11"
                                                               }
                                                             }
Jun 10 18:01:33 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898493127,
                                                               "type": "kdeconnect.sms.request_conversation",
                                                               "body": {
                                                                 "threadID": "12"
                                                               }
                                                             }
Jun 10 18:01:33 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898493128,
                                                               "type": "kdeconnect.sms.request_conversation",
                                                               "body": {
                                                                 "threadID": "13"
                                                               }
                                                             }
Jun 10 18:01:33 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898493128,
                                                               "type": "kdeconnect.sms.request_conversation",
                                                               "body": {
                                                                 "threadID": "14"
                                                               }
                                                             }

  
Jun 10 18:01:33 org.gnome.Shell.Extensions.GSConnect[14861]: [/service/device.js:sendPacket:449]: jeffsphone!: {
                                                               "id": 1654898493131,
                                       

```

**Ubuntu 22.04, linux kernel 5.18. Intel 12900K. Nvidia GeForce GPU, driver version 510.**

 - **GSConnect version:** 50
   - **Installed from:**Gnome extensions website
 - **GNOME/Shell version:**  42.1
 - **Distro/Release:** Ubuntu 22.04

**GSConnect environment (if applicable):**

 - **Paired Device(s):** OnePlus Nord N200
 - **KDE Connect app version:** 1.19.1

**Additional Notes:**

Gnome extensions website shows chrome-gnome-shell as not installed even though it is.

![Screenshot from 2022-06-10 18-14-38](https://user-images.githubusercontent.com/66034858/173160449-0a8c1c6a-0531-4198-8800-97413b402c5b.png)
![Screenshot from 2022-06-10 18-15-04](https://user-images.githubusercontent.com/66034858/173160472-363d227d-4d5b-4c0b-85b4-459c3cf227d3.png)

**Comment by andyholmes** [comment] 2022-06-11 02:41
All I can really tell from the logs here is that the message was never confirmed as sent by the Android device. To get more information about that, you'd have get logs from the Android device and report an [upstream bug](https://bugs.kde.org/buglist.cgi?product=kdeconnect&component=android-application&resolution=---). As for the missing messages, you'd need to provide logs showing errors for why this happened.

The SMS plugin needs quite a bit of love, since it basically hasn't been touched in almost two years. Unfortunately, without a contributor coming forward to help with this, it is unlikely to change at this point since the project lacks contributors with the necessary free time to commit to it.

> Gnome extensions website shows chrome-gnome-shell as not installed even though it is.

This is probably due to your web browser running in a sandbox, either Flatpak or Snap. If not, I'd suggest you report an issue with your distribution since this isn't something that can be fixed in GSConnect.

**Comment by andyholmes** [comment] 2022-08-02 23:20
Closing as an upstream bug, as GSConnect doesn't seem to be doing anything wrong here.

Feel free to re-open if you can provide logs showing GSConnect is encountering an error.

**Closed by andyholmes** 2022-08-02 23:20 UTC
Labels: can't fix, upstream
