### ISSUE TITLE
Notification and mounting is not working with Android 13, Miui 14

### ISSUE THREAD

**Issue by soumyaDghosh** [GSConnect/gnome-shell-extension-gsconnect#1732] opened 2024-01-21 15:29 UTC
### Describe the bug

Clicking the mount button doesn nothing. The notifications from my phone are also not showing up. Tried all the issues listed here, but none worked. Even support log is showing nothing.

### GSConnect version

56

### Installed from

GNOME Extensions website

### GNOME Shell version

45.2

### Linux distribution/release

Ubuntu 23.10

### Paired device(s)

Poco X5 5G

### KDE Connect app version

1.29.0

### Support log

```plain text
GSConnect: 56 (user)
GJS:       17800
Session:   x11
OS:        Ubuntu 23.10
--------------------------------------------------------------------------------
Jan 21 20:55:00 kernel: workqueue: pm_runtime_work hogged CPU for >10000us 8 times, consider switching to WQ_UNBOUND
Jan 21 20:55:08 systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Jan 21 20:55:36 org.gnome.Shell.Extensions.GSConnect[5956]: [/service/device.js:sendPacket:472]: Poco X5 5G: {
                                                              "id": 1705850736292,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_3__sink",
                                                                    "description": "HDMI / DisplayPort 1 Output (Tiger Lake-H HD Audio Controller HDMI / DisplayPort 1 Output)",
                                                                    "muted": false,
                                                                    "volume": 65536,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_4__sink",
                                                                    "description": "HDMI / DisplayPort 2 Output (Tiger Lake-H HD Audio Controller HDMI / DisplayPort 2 Output)",
                                                                    "muted": false,
                                                                    "volume": 65536,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_5__sink",
                                                                    "description": "HDMI / DisplayPort 3 Output (Tiger Lake-H HD Audio Controller HDMI / DisplayPort 3 Output)",
                                                                    "muted": false,
                                                                    "volume": 65536,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink",
                                                                    "description": "Headphones (Tiger Lake-H HD Audio Controller Speaker + Headphones)",
                                                                    "muted": false,
                                                                    "volume": 17039,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
Jan 21 20:55:36 org.gnome.Shell.Extensions.GSConnect[5956]: [/service/device.js:sendPacket:472]: Poco X5 5G: {
                                                              "id": 1705850736522,
                                                              "type": "kdeconnect.systemvolume",
                                                              "body": {
                                                                "sinkList": [
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_3__sink",
                                                                    "description": "HDMI / DisplayPort 1 Output (Tiger Lake-H HD Audio Controller HDMI / DisplayPort 1 Output)",
                                                                    "muted": false,
                                                                    "volume": 65536,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_4__sink",
                                                                    "description": "HDMI / DisplayPort 2 Output (Tiger Lake-H HD Audio Controller HDMI / DisplayPort 2 Output)",
                                                                    "muted": false,
                                                                    "volume": 65536,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_5__sink",
                                                                    "description": "HDMI / DisplayPort 3 Output (Tiger Lake-H HD Audio Controller HDMI / DisplayPort 3 Output)",
                                                                    "muted": false,
                                                                    "volume": 65536,
                                                                    "maxVolume": 65536
                                                                  },
                                                                  {
                                                                    "name": "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink",
                                                                    "description": "Headphones (Tiger Lake-H HD Audio Controller Speaker + Headphones)",
                                                                    "muted": false,
                                                                    "volume": 17039,
                                                                    "maxVolume": 65536
                                                                  }
                                                                ]
                                                              }
                                                            }
```

**Comment by soumyaDghosh** [comment] 2024-01-25 18:38
The connection is also getting unreliable day by day. Sometimes the mount stops working. Sometimes, something else happens.

**Comment by soumyaDghosh** [comment] 2024-02-13 18:39
Hii, any update on this? I am still not getting notifications. It doesn't work. Is this some kind of Android regression? I am on Android 14 now.

**Comment by andyholmes** [comment] 2024-03-01 23:54
Please open separate issues for each problem you encounter, thanks!

The mounting issue is a duplicate of #1203.

**Closed by andyholmes** 2024-03-01 23:54 UTC
Labels: triage
