### ISSUE TITLE
No PEM-encoded private key found. Can't connect. Fedora 38/39

### ISSUE THREAD

**Issue by chtholine** [GSConnect/gnome-shell-extension-gsconnect#1711] opened 2023-11-14 14:55 UTC
### Describe the bug

Both on fedora 38 and 39 I got this error when turning gsconnect on, also I am not able to connect devices.
I can connect between my phone and tablet using KDEconnect, but I can't see the laptop.
Port 1716 tcp/udp is public.

```
No PEM-encoded private key found

Gio.TlsCertificate.new_for_paths@/home/chtholine/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/utils/setup.js:378:31
_initCertificate@/home/chtholine/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:184:48
start@/home/chtholine/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:450:18
_loadBackends@/home/chtholine/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:259:25
start@/home/chtholine/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:462:14
vfunc_startup@/home/chtholine/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:263:22
vfunc_handle_local_options@/home/chtholine/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:660:18
@/home/chtholine/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:720:17
```

### Steps to reproduce

Turn gsconnect on
Error pops up

### GSConnect version

56

### Installed from

GNOME Extensions website

### GNOME Shell version

45

### Linux distribution/release

Fedora 39

### Paired device(s)

Galaxy TAB A, POCO X3 Pro

### KDE Connect app version

1.29

**Comment by andyholmes** [comment] 2024-03-02 00:46
Closing as a duplicate of #1209

See also: https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1209#issuecomment-974808691

**Closed by andyholmes** 2024-03-02 00:46 UTC
Labels: duplicate
