### ISSUE TITLE
alignment issue

### ISSUE THREAD

**Issue by cybbro** [GSConnect/gnome-shell-extension-gsconnect#1185] opened 2021-10-17 08:08 UTC
When I have one device added, alignment is good, but with two devices added, alignment is off, battery icon is gone:

![Screenshot from 2021-10-17 11-04-49](https://user-images.githubusercontent.com/10908092/137617947-d55c1b70-0468-4859-9a09-e573711d20a3.png)

Latest gnome extension on Ubuntu 21.10

Reproduce by adding two devices

**Comment by andyholmes** [comment] 2021-11-27 20:11
Thanks for reporting.

Duplicate of #1050

**Closed by andyholmes** 2021-11-27 20:11 UTC
Labels: duplicate
