### ISSUE TITLE
GSconnect not working Fedora 36

### ISSUE THREAD

**Issue by MertVaran** [GSConnect/gnome-shell-extension-gsconnect#1426] opened 2022-07-27 04:04 UTC
**Describe the bug**

Both android (OnePlus 7 running android 11) and iPhone (Xr running IOS 15.5) not connecting to Fedora 36 machine

**Steps To Reproduce:**

Open GSconnect

Open KDE connect on mobile device

Expect connection

No Connection

**Expected behavior**

Connects properly

**Screenshots**

![image](https://user-images.githubusercontent.com/61546499/181157950-99ed8a0b-0148-4d6c-81be-40cf8ff66e82.png)

**Support Log**

GSConnect: 50 (user)
GJS:       17201
Session:   wayland
OS:        Fedora Linux 36 (Workstation Edition)
--------------------------------------------------------------------------------
Jul 26 23:43:00 systemd[1784]: app-flatpak-org.fedoraproject.MediaWriter-22605.scope: Consumed 1.793s CPU time.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 35, 36, ... (displayed in the GSConnect "About" window)]
   - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
 - **GNOME/Shell version:** [e.g. 3.36, ...]
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

I did everything from reconfiguring every possible thing on the firewall to straight up disable it. I don't think the firewall is at fault. I also cannot ping both devices even with the firewall disabled. I ran "sudo netcat -z -v <device IP> 1714-1764" with no success. been going at this for 4 hours straight now so any help is much appreciated.

**Comment by derOedipus** [comment] 2022-07-29 22:40
I have the same problem on my fedora installation. The issue is that fedora 36 uses openSSL 1.1.1 and gsconnect only supports openSSL 1.0.x. As far as i know its the same issue as in #1209. Also i dont belive downgrading is an option, because the new fedora doesnt come bundled with the old openSSL.

**Comment by daknuett** [comment] 2022-07-31 06:28
You should probably try installing GSConnect version 53. You will have to install it from source but it is not that hard.

The latest releases (everything since 50) were not deployed. I don't know why.

**Comment by daknuett** [comment] 2022-07-31 06:29
You should probably try installing GSConnect version 53. You will have to install it from source but it is not that hard.

The latest releases (everything since 50) were not deployed. I don't know why.

Version 53 works on Fedora 36.

**Comment by andyholmes** [comment] 2022-08-02 22:43
Closing as a duplicate of #1209.

Please continue any discussion there and ,if possible, provide the verbatim output of the `openssl` command as used in GSConnect.

**Closed by andyholmes** 2022-08-02 22:43 UTC
Labels: duplicate

**Comment by santschi** [comment] 2023-04-22 16:27
I got the extension working on Fedora 38 by installing it via rpm
`dnf install gnome-shell-extension-gsconnet` 
which installed all the needed dependencies and then installing it via gnome extension manager.
