### ISSUE TITLE
cli support for received SMS

### ISSUE THREAD

**Issue by boblun** [GSConnect/gnome-shell-extension-gsconnect#1384] opened 2022-06-09 23:03 UTC
I need to be able to retrieve SMS messages received by the phone into a specific directory using the CLI, or allow a user defined handler to mange them. This would allow, for example a chatbot to handle SMS messages. In my case I just want to be able to forward the SMS to an e-mail recipient.

**Comment by andyholmes** [comment] 2022-06-10 22:46
This seems like a duplicate of your following report?

**Comment by boblun** [comment] 2022-06-11 11:34
Sorry, yes, the two things are related

On 11 June 2022 8:47:03 am AEST, Andy Holmes ***@***.***> wrote:
>This seems like a duplicate of your following report?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1384#issuecomment-1152785429
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andyholmes** [comment] 2022-08-02 23:18
Closing as this is addressed in #1385

**Closed by andyholmes** 2022-08-02 23:18 UTC
Labels: duplicate
