### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by CleoMenezesJr** [GSConnect/gnome-shell-extension-gsconnect#1307] opened 2022-03-20 19:45 UTC
```
GSConnect: 47 (user)
GJS:       17190
Session:   wayland
OS:        Fedora Linux 36.20220319.0 (Silverblue Prerelease)

_loadBackends@/var/home/cleomenezesjr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/var/home/cleomenezesjr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/var/home/cleomenezesjr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/var/home/cleomenezesjr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/var/home/cleomenezesjr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by ferdnyc** [comment] 2022-03-20 21:58
Duplicate of #1256.

**Closed by ferdnyc** 2022-03-20 21:58 UTC
Labels: duplicate
