### ISSUE TITLE
Can't mont my Samsung Galaxy s10 plus

### ISSUE THREAD

**Issue by GDL64** [GSConnect/gnome-shell-extension-gsconnect#1344] opened 2022-05-02 16:19 UTC
**Steps To Reproduce:**

1. Go to gnome trail icons
2. Click on 'Mont'
3. Nothing hapens

**Expected behavior**

I need to acess my archives of s10 by monting the smartphone in Linux. 

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

GSConnect: 50 (user)
GJS:       17200
Session:   wayland
OS:        Ubuntu 22.04 LTS
--------------------------------------------------------------------------------
mai 02 13:09:11 org.gnome.Shell.Extensions.GSConnect[1515]: [/service/device.js:sendPacket:449]: Galaxy S10+: {
                                                              "id": 1651507751961,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }
mai 02 13:09:11 org.gnome.Shell.Extensions.GSConnect[1515]: [/service/device.js:_readLoop:341]: Galaxy S10+: {
                                                              "id": 1651507752157,
                                                              "type": "kdeconnect.sftp",
                                                              "body": {
                                                                "ip": "192.168.15.36",
                                                                "port": 1739,
                                                                "user": "kdeconnect",
                                                                "password": "eK3lJsoE64xRLVpCE2t4LYESJ0t0",
                                                                "path": "/",
                                                                "multiPaths": [
                                                                  "/DCIM"
                                                                ],
                                                                "pathNames": [
                                                                  "DCIM"
                                                                ]
                                                              }
                                                            }
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Conexão falhou
                           _handleMount/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mai 02 13:09:12 gjs[1515]: JS ERROR: Galaxy S10+: Gio.IOErrorEnum: Erro desconhecido 255
                           Cannot stat /home/wsm64/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/home/wsm64/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17

```

**System Details (please complete the following information):**

 - **GSConnect version: 50 
   - **Installed from: GNOME Extensions Website
 - **GNOME/Shell version: 41.4
 - **Distro/Release: Ubuntu 22.04

**GSConnect environment (if applicable): Gnome

 - **Paired Device(s): Samsung Galaxy s10 plus [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

I'm a newbee, pls help me :(

**Comment by joshcangit** [comment] 2022-07-11 03:30
Same here.
This should be the same as #1294.

**Comment by andyholmes** [comment] 2022-08-02 23:53
Duplicate of #1203.

Feel free to open a new issue if the posted workaround does not solve the problem.

**Closed by andyholmes** 2022-08-02 23:53 UTC
Labels: duplicate
