### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by Agi-Developer** [GSConnect/gnome-shell-extension-gsconnect#1257] opened 2022-02-27 08:47 UTC
```
GSConnect: 47 (user)
GJS:       17101
Session:   x11
OS:        Ubuntu Jammy Jellyfish (development branch)

_loadBackends@/home/agilan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/agilan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/agilan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/agilan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/agilan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by aniketfuryrocks** [comment] 2022-03-01 08:10
Duplicate of #1259

**Comment by ferdnyc** [comment] 2022-03-01 14:15
As noted.

**Closed by ferdnyc** 2022-03-01 14:15 UTC
