### ISSUE TITLE
Mount does not work

### ISSUE THREAD

**Issue by peterjunior24** [GSConnect/gnome-shell-extension-gsconnect#1552] opened 2023-01-10 15:48 UTC
### Describe the bug

When clicking the mount option nothing happen

### Steps to reproduce
1- Click on Mount Option
2- Open Nautilus
### Expected behavior

A nautilus folder for each location folder mount point must appear 

### GSConnect version

50

### Installed from

GNOME Extensions website

### GNOME Shell version

42.5

### Linux distribution/release

Ubuntu 22.04.1 64 bits on Dell inspiron 5559

### Paired device(s)

Samsung Galaxy S7 Edge (SM-G935F) Android 8.0 Samsung Experience 9.0

### KDE Connect app version

1.22.1

### Support log

```plain text
GSConnect: 50 (user)
GJS:       17202
Session:   wayland
OS:        Ubuntu 22.04.1 LTS
--------------------------------------------------------------------------------
Jan 10 10:21:29 kernel: Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
Jan 10 10:21:31 gnome-shell[2317]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jan 10 10:21:31 gnome-shell[2317]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jan 10 10:21:31 gnome-shell[2317]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jan 10 10:21:31 gnome-shell[2317]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jan 10 10:21:31 gnome-shell[2317]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jan 10 10:21:31 gnome-shell[2317]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jan 10 10:21:31 gnome-shell[2317]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jan 10 10:21:31 gnome-shell[2317]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jan 10 10:21:33 gjs[9382]: JS ERROR: Galaxy S7 Edge: Gio.IOErrorEnum: Connection failed
                           _handleMount/</<@/home/pyxel-solutions/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                           @/home/pyxel-solutions/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by ejgutierrez74** [comment] 2023-01-11 10:47
Same here... i cant mount two different devices Samsung S9 and LG G6. Other things work fine.
Error log seems it gives no clues :


```
GSConnect: 50 (user)
GJS:       17202
Session:   wayland
OS:        Ubuntu 22.04.1 LTS
--------------------------------------------------------------------------------
ene 11 11:44:00 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:00 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:01 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:01 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:02 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:02 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:02 rtkit-daemon[2165]: Supervising 2 threads of 2 processes of 1 users.
ene 11 11:44:02 rtkit-daemon[2165]: Supervising 2 threads of 2 processes of 1 users.
ene 11 11:44:03 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:03 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:04 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:04 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:05 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:05 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:06 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:06 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:07 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:07 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:08 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:08 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:09 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:09 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:10 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:10 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:11 boinc[5729]: Authorization required, but no authorization protocol specified
ene 11 11:44:11 boinc[5729]: Authorization required, but no authorization protocol specified
```

**Comment by pktpls** [comment] 2023-01-18 01:29
Same here on Fedora - first time user, many of the other features work pretty nicely, especially the remote mousepad - cheers!

```
GSConnect: 54
GJS:       1.17.1
Session:   wayland
OS:        Fedora 37 / Gnome 43.2
----------------------------------------------------
Jan 18 02:23:34 user gjs[2535]: JS ERROR: Pixel 4A: Gio.IOErrorEnum: Connection failed
                                _handleMount/</<@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                                @/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17

```

**Comment by TimP4w** [comment] 2023-01-22 12:41
This looks like a duplicate of #1203 and #1535 

This seems unlikely to be patched upstream any time soon and it has been already discussed.
I thought about creating an automatic "patcher" to the ssh config file, which at every mount will check if the patch was already added, remove it, and reapply it with the current host (to account for dhcp) but said out loud this sounds really dumb.

@peterjunior24m, @ejgutierrez74, @pktpls just add this to your user ssh config file (`~/.ssh/config`)

```
# GSConnect accept RSA patch
Host 192.168.1.* # change with your host
  HostKeyAlgorithms +ssh-rsa
  PubkeyAcceptedKeyTypes +ssh-rsa
```

@andyholmes I guess you can close it as a duplicate, however it may make sense to provide this info to the user in case of a mount fail, since it doesn't even show a notification and just does nothing.

**Comment by andyholmes** [comment] 2023-01-25 01:53
> I guess you can close it as a duplicate, however it may make sense to provide this info to the user in case of a mount fail, since it doesn't even show a notification and just does nothing.

Unless I'm remembering wrong, there is no detailed error code passed through from GVfs. For historical reasons, GSConnect considers all mount failures to be host key errors, but doesn't show a notification about it since used to happen quite a bit I think.

Someone could poke around and see what GVfs actually passes through in [error conditions](https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/main/src/service/plugins/sftp.js#L274), I'm just not sure it will provide the necessary information.

**Comment by TimP4w** [comment] 2023-02-06 21:36
> Someone could poke around and see what GVfs actually passes through in [error conditions](https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/main/src/service/plugins/sftp.js#L274), I'm just not sure it will provide the necessary information.

Unfortunately nothing useful. However the KDEConnect app had to increase the `minSDKVersion` hopefully this will be fixed soon upstream.

**Comment by andyholmes** [comment] 2024-03-01 23:53
Closing as a duplicate of #1203.

**Closed by andyholmes** 2024-03-01 23:53 UTC
Labels: triage
