### ISSUE TITLE
GSConnect overfills systems log file

### ISSUE THREAD

**Issue by mugoh** [GSConnect/gnome-shell-extension-gsconnect#1206] opened 2021-11-15 19:17 UTC
GSConnect exponentially grows the `syslog` file. My storage was filling up and `/var/logs/` seemed to be the culprit. After checking the logs, they seem to be error messages from GSConnect -- same log message being done really fast to take up >180GB in a few minutes.

**Steps To Reproduce:**

1. My GSConnect was reading "turn off" at the gnome shortcut menu. I noticed this while trying to use it and realised it wasn't connected
2. I tried "turning off". But the option still remained "turn off". This is the last time I tried interacting with it. After ~1 hour, that's when I got the warning of my system storage being full.

This was the message filling up `syslog`:
```
The offending callback was SourceFunc().
Nov 15 18:27:56 heartly gjs[266207]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
```
3. I disabled GSConnect from the extensions menu. The message then turned to:
```
org.gnome.Shell.Extensions.GSConnect[266207]: == Stack trace for context 0x5617791af1a0 ==

org.gnome.Shell.Extensions.GSConnect[266207]: #0   56177925ef80 i   /home/username/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:729 (1143e1b8d178 @ 963)
```
and was still overfilling the logs rapidly.

**Expected behavior**

Clicking "turn off" would turn off GSConnect and give an option to "turn on". 

**Screenshots**

**Support Log**

[Log file](https://drive.google.com/file/d/12Gt0MhKoPooYMJmYG1DKGCPBTOcpJrjU/view?usp=sharing)

**System Details (please complete the following information):**

 - **GSConnect version:** 41
   - **Installed from:** GNOME Extensions Website,
 - **GNOME/Shell version:** 3.36.9
 - **Distro/Release:** Ubuntu 20.04

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Last succesful pair with Samsung A
 - **KDE Connect app version:** 1.17.0
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Comment by andyholmes** [comment] 2021-11-27 18:32
Thanks for reporting, but this seems like a duplicate of #988

**Closed** 2021-11-27 18:32 UTC
Labels: duplicate
