### ISSUE TITLE
SFTP mount not working in Gnome 42 Fedora 36

### ISSUE THREAD

**Issue by mspatil32** [GSConnect/gnome-shell-extension-gsconnect#1401] opened 2022-06-28 12:04 UTC
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

Hi,

I am using GSConnect in Fedora 36 with Gnome 42. The SFTP mount is not working, although the notifications from phone can be seen on PC. Please help to debug this issue.
I've posted the logs in the below mail.
Please let me know if you need any more information to debug.

Thanks,
Mallikarjun

**Steps To Reproduce:**

1. Login.
2. GSConnect connects to phone and the notifications show up, but SFTP mount doesn't work.
3. Errors can be seen in the logs as shown above.

**Expected behavior**

The GSConnect successfully mounts the phone filesystem and shows up in the file browser.

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
May 21 09:27:00 gnome-shell[9300]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
May 21 09:27:00 gnome-shell[9300]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
May 21 09:27:00 gnome-shell[9300]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
May 21 09:27:00 gnome-shell[9300]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
May 21 09:27:00 gnome-shell[9300]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
May 21 09:27:00 gnome-shell[9300]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
May 21 09:27:00 gnome-shell[9300]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
May 21 09:27:00 gnome-shell[9300]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
May 21 09:27:04 audit: BPF prog-id=120 op=LOAD
May 21 09:27:04 audit: BPF prog-id=121 op=LOAD
May 21 09:27:04 systemd[1]: Starting systemd-hostnamed.service - Hostname Service...
May 21 09:27:04 systemd[1]: Started systemd-hostnamed.service - Hostname Service.
May 21 09:27:04 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 21 09:27:04 systemd[1480]: dbus-:1.3-org.gnome.Nautilus@0.service: Consumed 5.489s CPU time.
May 21 09:27:04 wpa_supplicant[1400]: wlo1: CTRL-EVENT-SIGNAL-CHANGE above=0 signal=-83 noise=-95 txrate=65000
May 21 09:27:23 systemd[1480]: Started dbus-:1.3-org.gnome.Nautilus@1.service.
May 21 09:27:23 gnome-shell[9300]: Could not create transient scope for PID 0: GDBus.Error:org.freedesktop.systemd1.UnitExists: Unit app-gnome-org.gnome.Nautilus-0.scope already exists.
```

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 35, 36, ... (displayed in the GSConnect "About" window)]
   - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
 - **GNOME/Shell version:** [e.g. 3.36, ...]
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Add any additional information about the problem or your system.

**Comment by andyholmes** [comment] 2022-08-02 22:25
Probably another duplicate of #1203.

If the solution in that issue doesn't work, feel free to re-open with your results.

**Closed by andyholmes** 2022-08-02 22:25 UTC
Labels: duplicate
