### ISSUE TITLE
Run Command not working on GSConnect

### ISSUE THREAD

**Issue by Scientiac** [GSConnect/gnome-shell-extension-gsconnect#1120] opened 2021-05-24 05:02 UTC
The command option when clicked shows no response. It worked when I used KDE connect. Also on my phone there is no option to add command like I did have when using the KDE connect. 

**Steps To Reproduce:**

1. Go to 'Extensions'
2. Click on 'GSConnect setting option and on your connected device'
3. Go to 'Commads'
4. Click the + button, It shows no response.

**THERE IS NO DIALOGUE BOX, NO ERROR DIALOGUE, IT NEITHER ADDS THE COMMANDS NOR SHOW ERRORS**

**Screenshots**

![Screenshot from 2021-05-24 10-41-50](https://user-images.githubusercontent.com/58177655/119298493-db87aa80-bc7c-11eb-8968-2ccbd0094567.png)
![Screenshot_20210524-104340585](https://user-images.githubusercontent.com/58177655/119298540-f0fcd480-bc7c-11eb-9ecf-a9787fe4206b.jpg)

**System Details**

 - GSConnect version: 46
 - Installed from: GNOME Extensions Website
 - GNOME/Shell version: 40
 - Distro/Release: Arch

**GSConnect environment**

 - Paired Device: Redmi Note 9 Pro Max (excalibur) CORVUS OS - Android 11
 - KDE Connect app version: 1.17
 - Plugin(s): Run Command

**Additional Notes:**

My phone has a Custom Rom and is rooted.I don't think that can be a problem.

**Comment by tseleznev** [comment] 2021-05-28 21:20
same issue, same system details
error in CLI 
(gsconnect-preferences:5400): Gjs-CRITICAL **: 00:16:00.940: JS ERROR: TypeError: this.get_root is not a function
_onEditCommand@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/device.js:686:37
@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences:112:21

**Comment by p-tamkovich** [comment] 2021-06-07 20:46
The same issue. 
Fedora 34
GNOME 40
Kernel 5.12.8-300.fc34.x86_64

**Comment by andyholmes** [comment] 2021-06-08 03:39
Duplicate of #1105

**Closed by andyholmes** 2021-06-08 03:39 UTC
Labels: duplicate

**Comment by KonstantMan** [comment] 2021-06-13 13:30
I can confirm this bug remains on Arch Linux, Gnome Shell 40.1 X11 and gnome-shell-extension-gsconnect 46-1 from AUR

**Comment by KonstantMan** [comment] 2021-06-18 16:23
> Can confirm, it was fixed on master branch. Install from source or wait a new release
How did you install it from source 
I installed using  gnome-extensions install --force gsconnect@andyholmes.github.io.zip
but i still can't commands

**Comment by p-tamkovich** [comment] 2021-06-18 16:59
> > Can confirm, it was fixed on master branch. Install from source or wait a new release
> > How did you install it from source
> > I installed using  gnome-extensions install --force [gsconnect@andyholmes.github.io.zip](mailto:gsconnect@andyholmes.github.io.zip)
> > but i still can't commands

[Install from Git](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-git) I did it by this guide. You can have some missed dependencies, but sorry, I don't remember what exactly I had to install before. Maybe you won't meat this kind of problems :)
