### ISSUE TITLE
already in use for all keybinds

### ISSUE THREAD

**Issue by AbdesamedBendjeddou** [GSConnect/gnome-shell-extension-gsconnect#1304] opened 2022-03-20 13:15 UTC
**Can't set keybinds : already being used**

![Screenshot from 2022-03-20 14-10-45](https://user-images.githubusercontent.com/51114014/159163910-8b47077b-c1a0-4fb2-902f-3fd8c360efe6.png)

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
GSConnect: 49 (user)
GJS:       17001
Session:   wayland
OS:        Fedora Linux 35 (Workstation Edition)
--------------------------------------------------------------------------------
Mar 20 14:07:21 gnome-shell[2362]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Mar 20 14:07:21 gnome-shell[2362]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Mar 20 14:07:21 gnome-shell[2362]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
```

**System Details (please complete the following information):**

 - **GSConnect version: 49**
 - **Installed from: GNOME Extensions Website,**
 - **GNOME/Shell version: 41.3**
 - **Distro/Release: Fedora 35**
 - **Paired Device(s): Galaxy Note 8**

**Additional Notes:**
**installed extensions**:
![Screenshot from 2022-03-20 14-14-26](https://user-images.githubusercontent.com/51114014/159164025-7359e148-3f6e-418f-bfd2-0529cb93864e.png)

**Comment by ferdnyc** [comment] 2022-03-20 21:52
Duplicate of #1215.

**Closed by ferdnyc** 2022-03-20 21:52 UTC
Labels: duplicate
