### ISSUE TITLE
Duplicate GSConnect icon shows up in the tray

### ISSUE THREAD

**Issue by Scotty-Trees** [GSConnect/gnome-shell-extension-gsconnect#998] opened 2020-10-15 09:15 UTC
In Gnome, as is needed sometimes, I need to do ALT+F2+R to reset the gnome-shell. Recently when I do this now (probably do it maybe once a day), after the above command is run, there adds a duplicate GSConnect icon in the tray, so I have TWO GSConnect icons in the top tray. Now I do have another extension called [Status Area Horizontal Spacing](https://extensions.gnome.org/extension/355/status-area-horizontal-spacing/), which I originally brought up the issue to over on this tracker here [Gitlab](https://gitlab.com/p91paul/status-area-horizontal-spacing-gnome-shell-extension/-/issues/7), however they said: 

> The latest update just forces a redraw of the icons when spacing is changed in the settings.
> Did you try to open an issue on GSConnect as well? (I imagine that's another extension you have).
> Looks like it is doing something unusual if its icon is redrawn.

So I'm wondering if there needs to be a fix/edit/change or what have you in regards to when icons are redrawn, I'm not sure why it does the icon twice, but oddly enough both icons are functional btw. I have a screenshot below to show what I'm referring to. Hopefully this can be fixed, I'd very much appreciate it.

You'll notice two GSConnect icons that are shaped like phones. I don't need the one on the left to show, it works best when it's integrated into the main tray icon set. 

![Screenshot from 2020-10-14 12-18-55](https://user-images.githubusercontent.com/45135187/96100930-81c73280-0e9a-11eb-9035-4747c6aad21b.png)

GSConnect version: 45 installed from GNOME Extensions website
GNOME/Shell version: 3.36.3
Distro/Release: Pop!_OS 20.04

**Comment by andyholmes** [comment] 2020-10-15 23:21
Sorry, I can't reproduce this, but I doubt it has anything to do with "Status Area Horizontal Spacing".

It would help if you could find something in `journalctl` or GNOME Logs showing an error in the extension, and add the GSConnect version (since there is no v45).

**Comment by Scotty-Trees** [comment] 2020-10-15 23:35
This is just my most recent Gnome Log below. I enabled the Status Area extension, then Alt+F2+R, then the second icon popped up, and then I opened up Gnome Logs, and this is all I saw. Don't know if that's gonna be enough. Would you happen to know why type of `journalctl` I need to run to help? 

![Screenshot from 2020-10-15 18-33-25](https://user-images.githubusercontent.com/45135187/96196530-3aca5300-0f15-11eb-8611-f5e0fef3195f.png)

**Comment by andyholmes** [comment] 2020-10-15 23:50
`journalctl -f -o cat /usr/bin/gnome-shell` will show a running log of output from GNOME Shell. In the screenshot above you're just showing lines containing the string 'gsconnect', so that's unlikely to show any relevant errors from gnome-shell.

Since I can't reproduce this even with that other extension installed, there's not much I can do without some error or hint as to why it's happening.

**Comment by Scotty-Trees** [comment] 2020-10-16 00:02
Any help this time perhaps?

```
scott@pop-os:~$ journalctl -f -o cat /usr/bin/gnome-shell
GNOME Shell started at Thu Oct 15 2020 18:37:38 GMT-0500 (CDT)
Registering session with GDM
Received property Shuffle with type d does not match expected type b in the expected interface
Received property Shuffle with type d does not match expected type b in the expected interface
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3e00007
JS WARNING: [/home/scott/.local/share/gnome-shell/extensions/status-area-horizontal-spacing@mathematical.coffee.gmail.com/convenience.js 19]: reference to undefined property "gettext-domain"
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1590:32
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1560:39
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:73:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:149:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:236:16

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1590:32
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1560:39
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:73:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:149:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:236:16

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1590:32
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1560:39
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:73:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:149:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:236:16

Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 2
Telepathy is not available, chat integration will be disabled.
Usage of indicator.indicators is deprecated for Indicator
get indicators@resource:///org/gnome/shell/ui/panelMenu.js:213:25
enable@/home/scott/.local/share/gnome-shell/extensions/toggle-mute-on-middle-click@qwerty12.com/extension.js:46:9
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:599:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:574:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:608:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
start@resource:///org/gnome/shell/ui/main.js:146:5
@<main>:1:47

Some code accessed the property 'Settings' on the module 'settings'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'Logger' on the module 'utils'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Disabling Window Is Ready Notification
JS WARNING: [/home/scott/.local/share/gnome-shell/extensions/status-area-horizontal-spacing@mathematical.coffee.gmail.com/convenience.js 19]: reference to undefined property "gettext-domain"
gnome-shell-extension-system76-power: power profile was set: 'Balanced'
st_label_set_text: assertion 'text != NULL' failed
Received property Shuffle with type d does not match expected type b in the expected interface
Received property Shuffle with type d does not match expected type b in the expected interface
Window manager warning: Overwriting existing binding of keysym 71 with keysym 71 (keycode 18).
GNOME Shell started at Thu Oct 15 2020 19:00:05 GMT-0500 (CDT)
Registering session with GDM
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.

```

**Comment by andyholmes** [comment] 2020-10-16 01:50
Sorry, there don't seem to be any related errors here either. My suspicion is that this is some kind of conflict with another extension or some modifications to GNOME Shell in pop os, but I'm not familiar with that distribution.

**Comment by Scotty-Trees** [comment] 2020-10-16 06:05
Ok no worries, let me see if I can track down another journalctl or gnome-shell errors to help out just a bit more.

**Comment by NathanCorbin** [comment] 2020-10-31 00:59
Same issue on Arch Linux with Status Area Horizontal Spacing extension installed.

**Comment by AJJLagerweij** [comment] 2020-11-16 17:30
I get the same issue on ubuntu 20.04, I've tried reinstalling the plugin and resetting it though the dconf-editor but to no avail.
To be exact I see icons of all possible devices, even those that I've never connected with, appear in the status area. After restarting gnome or waking my laptop from sleep. This should not be the case, as I've set the display option to user menu.

I've tried disabling my other gnome extensions and that did the trick. I've found that disabling the "Status area horizontal spacing" extension does solve the problem. I'll try to see if downgrading to an older version of the status area horizontal spacing extension resolves the issue. Downgrading GSConnect did not fix it.

**Comment by AJJLagerweij** [comment] 2020-11-16 17:54
I've downgraded the "status area horizontal spacing' extension to version 14. (officially this supports up to gnome 3.34, however it seems to work on my Ubuntu 20.04 with gnome 3.36.

Follow the following steps:
1. Go to the status [area horizontal spacing gnome extension page](https://extensions.gnome.org/extension/355/status-area-horizontal-spacing/) and select gnome 3.34 and version 14 to download manually.
2. Follow the [appropriate steps](https://linuxconfig.org/install-gnome-shell-extensions-from-zip-file-using-command-line-on-ubuntu-20-04-linux) to install an extension manually.
3. The official UUID of the extension is `status-area-horizontal-spacing@mathematical.coffee.gmail.com`

Obviously this is not a permanent solution and I'm not sure what we can do about it. @Scotty-Trees created an [issue](https://gitlab.com/p91paul/status-area-horizontal-spacing-gnome-shell-extension/-/issues/7#related-issues) as well over at the "status area horizontal spacing" GitLab page. Clearly something is conflicting but I don't know what. Does anyone know the steps I could perform to check what is causing the issue?

**Comment by p91paul** [comment] 2021-01-31 16:53
Tanks to a merge request https://gitlab.com/p91paul/status-area-horizontal-spacing-gnome-shell-extension/-/merge_requests/1 this issue might have been fixed in status-area-horizontal-spacing. Can anyone confirm?

**Comment by andyholmes** [comment] 2022-08-03 00:46
Closing due to lack of activity and logs showing this is caused by GSConnect.

**Closed by andyholmes** 2022-08-03 00:46 UTC
Labels: can't fix

**Comment by Scotty-Trees** [comment] 2022-08-03 01:01
If it helps, I've been on EndeavourOS Gnome for the last year or more and haven't come across this issue again, I'm sorry this was long ago I don't remember much, but it didn't happen anymore on Gnome 42.

**Comment by andyholmes** [comment] 2022-08-03 01:44
Okay, thanks for checking back!
