### ISSUE TITLE
/(?:cn|CN) ?= ?([^,\n]*)/.exec(...) is null

### ISSUE THREAD

**Issue by larkoma** [GSConnect/gnome-shell-extension-gsconnect#1123] opened 2021-06-01 00:22 UTC
```
GSConnect: 46 (user)
GJS:       16801
Session:   wayland
OS:        openSUSE Tumbleweed

get@/home/larinpc/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:393:64
_initCertificate@/home/larinpc/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:182:13
start@/home/larinpc/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/larinpc/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/home/larinpc/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/larinpc/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/larinpc/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/larinpc/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2021-06-08 03:43
Duplicate of #1118

**Closed by andyholmes** 2021-06-08 03:43 UTC
Labels: duplicate
