### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by kmkinney** [GSConnect/gnome-shell-extension-gsconnect#1407] opened 2022-07-04 15:53 UTC
```
GSConnect: 47 (user)
GJS:       17200
Session:   wayland
OS:        Ubuntu 22.04 LTS

_loadBackends@/home/kevin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/kevin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/kevin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/kevin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/kevin/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-08-02 22:08
Duplicate of #1256

**Closed by andyholmes** 2022-08-02 22:08 UTC
Labels: duplicate
