### ISSUE TITLE
Child process exited with code 127

### ISSUE THREAD

**Issue by PaulWolfDE** [GSConnect/gnome-shell-extension-gsconnect#1400] opened 2022-06-23 12:51 UTC
I got the following error message in my gnome notifications after installing the GSConnect extension.

The computer isn't able to find any device to pair with, and my phone with KDE Connect also can't find the computer.

```
GSConnect: 51 (user)
GJS:       16602
Session:   wayland
OS:        Debian GNU/Linux 11 (bullseye)

Gio.TlsCertificate.new_for_paths@/home/luqus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:349:14
_initCertificate@/home/luqus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:177:48
start@/home/luqus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/luqus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/home/luqus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/luqus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/luqus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/luqus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-08-02 23:43
Seems like another duplicate of #1209.

Please continue discussion there, or re-open if it is a different issue.

**Closed by andyholmes** 2022-08-02 23:43 UTC
Labels: duplicate

**Comment by PaulWolfDE** [comment] 2022-08-03 12:59
Reinstalling OpenSSL worked for me. Even with in #1209 mentioned version 1.1.1n.
Some libraries were broken, so I had to uninstall it with force `dpkg` and then reinstall with `apt`.
```
$ openssl version
OpenSSL 1.1.1n 15 Mar 2022
```
