### ISSUE TITLE
Cannot mount since 22.04

### ISSUE THREAD

**Issue by aliris-schmidt** [GSConnect/gnome-shell-extension-gsconnect#1347] opened 2022-05-06 07:42 UTC
Sice updating to Ubuntu 22.04 I cannot mount my smartphone.

```
JS ERROR: Error: M2012K11AG: Authentication Failure
_authenticate@/home/schmidt/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:665:23
async*_encryptServer@/home/schmidt/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:707:21
open@/home/schmidt/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:806:43
async*_onIdentity@/home/schmidt/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:378:27
async*_onIncomingIdentity@/home/schmidt/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:325:18
@/home/schmidt/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17

JS ERROR: M2012K11AG: Gio.IOErrorEnum: Verbindung fehlgeschlagen
_handleMount/</<@/home/schmidt/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
@/home/schmidt/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17


```

**Comment by skoruppa** [comment] 2022-05-10 10:12
Same here. In comments on the extension's page, we can see more users affected

**Comment by stesind** [comment] 2022-05-17 17:34
Your openssh disabled ssh-rsa by default. Add your phone to your ~/.ssh/config:

Host ONEPLUS-A3003 
  HostName 192.168.178.21
  HostKeyAlgorithms +ssh-rsa

Use your phones Host and IP address accordingly.

**Comment by VladG1986** [comment] 2022-05-26 00:36
same here, no error, just wont mount.

**Comment by stesind** [comment] 2022-05-28 05:04
With latest updates gvfs (1.50.1-1 -> 1.50.2-1) and the ssh config above it works now for me.

**Comment by VladG1986** [comment] 2022-05-30 03:12
> With latest updates gvfs (1.50.1-1 -> 1.50.2-1) and the ssh config above it works now for me.

Thank you. It mounts fine now via files app but not via gsconnect menu. It's good enough. All my files are synced in the cloud via Tresorit.

**Comment by andyholmes** [comment] 2022-08-02 22:19
Closing as a duplicate of #1203.

The amount of duplicates makes it very difficult to track actual problems, so if there are additional problems please open a new issue with a subject more specific than "Can't mount". Thanks for reporting!

**Closed by andyholmes** 2022-08-02 22:19 UTC
