### ISSUE TITLE
Bigger text input for messaging

### ISSUE THREAD

**Issue by matthijskooijman** [GSConnect/gnome-shell-extension-gsconnect#1354] opened 2022-05-13 11:28 UTC
**Is your feature request related to a problem? Please describe.**
The messaging part of this extension is very useful when you want to write an SMS that is a bit longer - no fuss with slow on-screen keyboards on your phone, just use a real keyboard on your computer.

However, the input field for text messages is only a single line without wordwrapping, meaning it is still cumbersome if you write a message that is longer than what fits on a single line.

**Describe the solution you'd like**
A bigger (multi-line) input field for text messages.

Ideally, you would even be able to resize the input field by dragging the separator between the old messages and input field.

**Describe alternatives you've considered**
I could write the message in a text editor and then paste it into the messaging app, but that's not very convenient.

**System Details (please complete the following information):**
 - GSConnect version: 50
   - Installed from: extensions.gnome.org

**Additional context**
![image](https://user-images.githubusercontent.com/194491/168274208-5a3b4b33-f195-4801-913b-c7cbade3a85c.png)

**Comment by andyholmes** [comment] 2022-05-18 21:26
Thanks for reporting, seems like a duplicate of #771. Feel free to re-open if that's not the case.

**Closed by andyholmes** 2022-05-18 21:26 UTC

**Comment by matthijskooijman** [comment] 2022-05-19 11:56
Heh, not sure how I missed that one. I guess I searched for "messaging", rather than "SMS". Thanks for the pointer!
