### ISSUE TITLE
Clipboard test suite fails

### ISSUE THREAD

**Issue by sonnyp** [GSConnect/gnome-shell-extension-gsconnect#1133] opened 2021-06-18 21:49 UTC
ClipboardComponent test `pushes changes to the session clipboard` is failing on my computer.

```
 9/26 gsconnect:components / ClipboardComponent            ERROR          5.16s

--- command ---
21:14:15 NO_AT_BRIDGE='1' G_DEBUG='fatal-warnings,fatal-criticals' GSETTINGS_SCHEMA_DIR='/home/sonny/Projects/GNOME/gnome-shell-extension-gsconnect/_build/installed-tests' GJS_PATH='/home/sonny/Projects/GNOME/gnome-shell-extension-gsconnect/_build/installed-tests/src' GSCONNECT_TEST='1' GSETTINGS_BACKEND='memory' /home/sonny/Projects/GNOME/gnome-shell-extension-gsconnect/installed-tests/minijasmine /home/sonny/Projects/GNOME/gnome-shell-extension-gsconnect/_build/../installed-tests/suites/components/testClipboardComponent.js
--- stdout ---
1..2
ok 1 The Clipboard component pulls changes from the session clipboard
not ok 2 The Clipboard component pushes changes to the session clipboard
# Message: Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL) in /home/sonny/Projects/GNOME/gnome-shell-extension-gsconnect/installed-tests/jasmine.js (line 7049)
# Stack:
#   error properties: Object({ matches: Function })
--- stderr ---

(test program exited with status code 1)
-------
```

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/8a3bd7b05562360f86e22c2b3c268e9379fcee30/installed-tests/suites/components/testClipboardComponent.js#L40

`owner-change` is never emitted

**Comment by daniellandau** [comment] 2021-10-03 12:26
For me the clipboard test suite runs fine on Xorg, but fails on the first test on Wayland

**Comment by andyholmes** [comment] 2021-10-03 20:13
That would make sense to fail on wayland, since that's where we need the shell extension to serve as clipboard manager. The CI tests run through Xvfb + dbus-run-session where it *should* work, so a bug there would be something to be concerned about.

**Comment by andyholmes** [comment] 2022-08-03 01:21
Closing, since this is expected behavior on Wayland as the tests must be run in Xorg.

**Closed by andyholmes** 2022-08-03 01:21 UTC
