### ISSUE TITLE
Child process exited with code 1

### ISSUE THREAD

**Issue by asfhyb** [GSConnect/gnome-shell-extension-gsconnect#1505] opened 2022-11-01 15:23 UTC
```
GSConnect: 50 (user)
GJS:       17202
Session:   wayland
OS:        Fedora Linux 36 (Workstation Edition)

Gio.TlsCertificate.new_for_paths@/home/husaini0405/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:349:14
_initCertificate@/home/husaini0405/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:177:48
start@/home/husaini0405/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/husaini0405/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:255:25
start@/home/husaini0405/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:458:14
vfunc_startup@/home/husaini0405/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/husaini0405/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/husaini0405/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2024-03-03 17:58
Closing as duplicate of #1209

**Closed by andyholmes** 2024-03-03 17:58 UTC
Labels: triage
