### ISSUE TITLE
Sending SMS doesn't work.

### ISSUE THREAD

**Issue by Mick-MB** [GSConnect/gnome-shell-extension-gsconnect#1109] opened 2021-05-02 10:59 UTC
I can receive SMS-s but cannot send them.
Ubuntu 20.04.2 LTS

**Comment by andyholmes** [comment] 2021-05-13 00:41
You will have to provide logs to get help with this, in addition to information about your phone model, KDE Connect version and GSConnect version.

**Comment by Mick-MB** [comment] 2021-05-13 15:19
Hi,
I have no idea how to get log from gsconnect.
Regarding the other data - Phone model: SAMSUNG Galaxy J5/2016, Android
7.1.1
KDEConnect version 1.17.0
GSConnect version 43

When I'm typing SMS text the "send" button remains grey like this

[image: image.png]
Clicking on it or pressing Enter moves entered text to the message window,
but the message is not transmitted to the phone.
[image: image.png]

Incoming messages are transmitted correctly.

czw., 13 maj 2021 o 02:41 Andy Holmes ***@***.***> napisał(a):

**Comment by andyholmes** [comment] 2021-05-13 19:26
See [Generate Support Log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) in the wiki for guidance on collecting a log.

**Comment by Mick-MB** [comment] 2021-05-14 14:33
Hi,
Thanks for the advice. This is the log

czw., 13 maj 2021 o 21:26 Andy Holmes ***@***.***> napisał(a):

**Comment by piipes** [comment] 2021-06-19 13:06
If I understand OP's post I am having the same issue.

Oppo R9s - Color Os v3.0.0i
KDE 1.17

**Comment by andyholmes** [comment] 2021-06-19 20:18
> When sending from desktop messages will go into the chat history, but will remain greyed out as if still sending.
On closing the window the greyed out messages will remove themselves.

This probably means GSConnect is sending the message to KDE Connect Android, but the device is not responding with confirmation.

**Comment by piipes** [comment] 2021-06-20 09:57
Any idea on resolving this issue?

**Comment by andyholmes** [comment] 2021-06-20 11:56
Nope. Without logs there's nothing really to be done.

Since both reporters here are using v43 with GNOME 3.36 you probably wouldn't see a patch for your distribution until you upgrade, unless someone volunteers to maintain an older branch. It's possible your problem has even been fixed in a newer version.

**Comment by Filbuntu** [comment] 2021-07-01 08:02
Ay, sayang GSConnect will not be upgraded/updated with GNOME 3.36. This means a lot of people with Ubuntu 20.04 LTS (and its derivatives) will have bugs and won't be able to use this awesome tool  in full extend. As most people now have a smartphone this tool is critical and should be maintained for the long term support OS versions. 
Would there be somebody at Ubuntu or GNOME we could ask to consider this?

**Comment by daniellandau** [comment] 2021-07-01 09:27
If you can find someone to do the work we are happy to take patches and do releases.

**Comment by Filbuntu** [comment] 2021-07-01 09:28
I am just a normal user. Who or where could I ask?

**Comment by daniellandau** [comment] 2021-07-01 09:33
I don't have a good answer for that. If you have the means to pay someone to do it then that's one thing but in general getting others to volunteer is a hard problem.

What you can do yourself is to try to figure out more details on how a developer could reproduce your issue. Check the instructions linked earlier here https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1109#issuecomment-840780874

Without knowing what the problem is it's really really hard to fix.

**Comment by Filbuntu** [comment] 2021-07-01 09:39
I don't have the means 😀 😐. I think the features of the tool are essential for a modern OS and therefore I hope GNOME or Ubuntu would take this on ... But not sure how to initiate this ...

I could try to get a support log (like Mick-MB did) but I guess at the moment nobody would branch v43 for GNOME 3.36

**Comment by daniellandau** [comment] 2021-07-01 09:41
We can branch if there's a fix

**Comment by Filbuntu** [comment] 2021-07-01 09:46
If this issue has been fixed in a later version of GSConnect/KDEConnect, could the patch for a later version been used to fix v43 and be branched?

**Comment by daniellandau** [comment] 2021-07-01 10:00
Sure, if someone experiencing the issue verifies that it is indeed fixed by updating and preferably also finds the exact patch that does it.

All of this is a bunch of work and especially hard if you can't even make the problem happen on your end.

**Comment by Filbuntu** [comment] 2021-07-01 12:51
Let's start with a log. I experience the same mentioned above:  
When sending from the desktop app (GSConnect) in the messages window, the "sent" message will go into the chat history, but will remain greyed out as if still sending. On closing the window the greyed out messages will remove themselves. The message(s) are and will never be sent. 

Here is the log:

`
GSConnect: 43 (user)
GJS:       16405
Session:   x11
OS:        Ubuntu 20.04.2 LTS
--------------------------------------------------------------------------------
-- Logs begin at Wed 2021-06-30 08:30:42 CEST, end at Thu 2021-07-01 14:39:37 CEST. --
Jul 01 14:38:00 nemo[2245]: connect() failed
Jul 01 14:38:01 nemo[2245]: connect() failed
Jul 01 14:38:02 nemo[2245]: connect() failed
Jul 01 14:38:03 nemo[2245]: connect() failed
Jul 01 14:38:04 nemo[2245]: connect() failed
Jul 01 14:38:05 nemo[2245]: connect() failed
Jul 01 14:38:06 nemo[2245]: connect() failed
Jul 01 14:38:07 nemo[2245]: connect() failed
Jul 01 14:38:08 nemo[2245]: connect() failed
Jul 01 14:38:09 nemo[2245]: connect() failed
Jul 01 14:38:10 nemo[2245]: connect() failed
Jul 01 14:38:11 kernel: Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
Jul 01 14:38:11 nemo[2245]: connect() failed
Jul 01 14:38:12 nemo[2245]: connect() failed
Jul 01 14:38:13 kernel: Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
Jul 01 14:38:13 nemo[2245]: connect() failed
Jul 01 14:38:14 nemo[2245]: connect() failed
Jul 01 14:38:15 nemo[2245]: connect() failed
Jul 01 14:38:16 nemo[2245]: connect() failed
Jul 01 14:38:17 nemo[2245]: connect() failed
Jul 01 14:38:18 dbus-daemon[1300]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.247' (uid=1000 pid=25169 comm="gjs /home/.../.local/share/gnome-shell/extensions/" label="unconfined")
Jul 01 14:38:18 systemd[1]: Starting Hostname Service...
Jul 01 14:38:18 dbus-daemon[1300]: [system] Successfully activated service 'org.freedesktop.hostname1'
Jul 01 14:38:18 systemd[1]: Started Hostname Service.
Jul 01 14:38:18 nemo[2245]: connect() failed
Jul 01 14:38:19 nemo[2245]: connect() failed
Jul 01 14:38:20 nemo[2245]: connect() failed
Jul 01 14:38:21 nemo[2245]: connect() failed
Jul 01 14:38:22 nemo[2245]: connect() failed
Jul 01 14:38:23 nemo[2245]: connect() failed
Jul 01 14:38:24 nemo[2245]: connect() failed
Jul 01 14:38:25 nemo[2245]: connect() failed
Jul 01 14:38:26 nemo[2245]: connect() failed
Jul 01 14:38:27 nemo[2245]: connect() failed
Jul 01 14:38:28 nemo[2245]: connect() failed
Jul 01 14:38:29 nemo[2245]: connect() failed
Jul 01 14:38:29 kernel: Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
Jul 01 14:38:30 nemo[2245]: connect() failed
Jul 01 14:38:31 nemo[2245]: connect() failed
Jul 01 14:38:32 org.gnome.Shell.Extensions.GSConnect[9900]: [/service/device.js:sendPacket:446]: Smartphone: {
                                                              "id": 1625143112322,
                                                              "type": "kdeconnect.contacts.request_all_uids_timestamps",
                                                              "body": {}
                                                            }
Jul 01 14:38:32 org.gnome.Shell.Extensions.GSConnect[9900]: [/service/device.js:sendPacket:446]: Smartphone: {
                                                              "id": 1625143112477,
                                                              "type": "kdeconnect.sms.request_conversations",
                                                              "body": {}
                                                            }
Jul 01 14:38:32 nemo[2245]: connect() failed
Jul 01 14:38:33 nemo[2245]: connect() failed
Jul 01 14:38:34 org.gnome.Shell.Extensions.GSConnect[9900]: [/service/device.js:sendPacket:446]: Smartphone: {
                                                              "id": 1625143114749,
                                                              "type": "kdeconnect.contacts.request_all_uids_timestamps",
                                                              "body": {}
                                                            }
Jul 01 14:38:34 org.gnome.Shell.Extensions.GSConnect[9900]: [/service/device.js:sendPacket:446]: Smartphone: {
                                                              "id": 1625143114757,
                                                              "type": "kdeconnect.sms.request_conversations",
                                                              "body": {}
                                                            }
Jul 01 14:38:34 nemo[2245]: connect() failed
Jul 01 14:38:35 nemo[2245]: connect() failed
Jul 01 14:38:36 nemo[2245]: connect() failed
Jul 01 14:38:37 nemo[2245]: connect() failed
Jul 01 14:38:38 nemo[2245]: connect() failed
Jul 01 14:38:39 nemo[2245]: connect() failed
Jul 01 14:38:40 nemo[2245]: connect() failed
Jul 01 14:38:41 nemo[2245]: connect() failed
Jul 01 14:38:42 nemo[2245]: connect() failed
Jul 01 14:38:43 nemo[2245]: connect() failed
Jul 01 14:38:44 nemo[2245]: connect() failed
Jul 01 14:38:45 nemo[2245]: connect() failed
Jul 01 14:38:46 nemo[2245]: connect() failed
Jul 01 14:38:47 nemo[2245]: connect() failed
Jul 01 14:38:48 systemd[1]: systemd-hostnamed.service: Succeeded.
Jul 01 14:38:48 nemo[2245]: connect() failed
Jul 01 14:38:49 nemo[2245]: connect() failed
Jul 01 14:38:50 nemo[2245]: connect() failed
Jul 01 14:38:51 nemo[2245]: connect() failed
Jul 01 14:38:52 nemo[2245]: connect() failed
Jul 01 14:38:53 nemo[2245]: connect() failed
Jul 01 14:38:54 nemo[2245]: connect() failed
Jul 01 14:38:55 nemo[2245]: connect() failed
Jul 01 14:38:56 nemo[2245]: connect() failed
Jul 01 14:38:57 nemo[2245]: connect() failed
Jul 01 14:38:58 nemo[2245]: connect() failed
Jul 01 14:38:59 nemo[2245]: connect() failed
Jul 01 14:39:00 nemo[2245]: connect() failed
Jul 01 14:39:01 nemo[2245]: connect() failed
Jul 01 14:39:01 org.gnome.Shell.Extensions.GSConnect[9900]: [/service/device.js:sendPacket:446]: Smartphone: {
                                                              "id": 1625143141947,
                                                              "type": "kdeconnect.sms.request",
                                                              "body": {
                                                                "sendSms": true,
                                                                "phoneNumber": "xxxxxxxx",
                                                                "messageBody": "Hello! This should send!"
                                                              }
                                                            }
Jul 01 14:39:02 nemo[2245]: connect() failed
Jul 01 14:39:03 nemo[2245]: connect() failed
Jul 01 14:39:04 nemo[2245]: connect() failed
Jul 01 14:39:05 nemo[2245]: connect() failed
Jul 01 14:39:06 nemo[2245]: connect() failed
Jul 01 14:39:07 nemo[2245]: connect() failed
Jul 01 14:39:07 org.gnome.Shell.Extensions.GSConnect[9900]: [/service/device.js:sendPacket:446]: Smartphone: {
                                                              "id": 1625143147873,
                                                              "type": "kdeconnect.contacts.request_all_uids_timestamps",
                                                              "body": {}
                                                            }
Jul 01 14:39:07 org.gnome.Shell.Extensions.GSConnect[9900]: [/service/device.js:sendPacket:446]: Smartphone: {
                                                              "id": 1625143147880,
                                                              "type": "kdeconnect.sms.request_conversations",
                                                              "body": {}
                                                            }
Jul 01 14:39:08 nemo[2245]: connect() failed
Jul 01 14:39:09 nemo[2245]: connect() failed
Jul 01 14:39:10 nemo[2245]: connect() failed
Jul 01 14:39:11 nemo[2245]: connect() failed
Jul 01 14:39:12 nemo[2245]: connect() failed
Jul 01 14:39:13 nemo[2245]: connect() failed
Jul 01 14:39:14 nemo[2245]: connect() failed
Jul 01 14:39:15 nemo[2245]: connect() failed
Jul 01 14:39:16 nemo[2245]: connect() failed
Jul 01 14:39:17 nemo[2245]: connect() failed
Jul 01 14:39:18 nemo[2245]: connect() failed
Jul 01 14:39:19 nemo[2245]: connect() failed
Jul 01 14:39:20 nemo[2245]: connect() failed
Jul 01 14:39:21 nemo[2245]: connect() failed
Jul 01 14:39:22 nemo[2245]: connect() failed
Jul 01 14:39:23 nemo[2245]: connect() failed
Jul 01 14:39:24 nemo[2245]: connect() failed
Jul 01 14:39:24 org.gnome.Shell.Extensions.GSConnect[9900]: [/service/device.js:sendPacket:446]: Smartphone: {
                                                              "id": 1625143164906,
                                                              "type": "kdeconnect.sms.request",
                                                              "body": {
                                                                "sendSms": true,
                                                                "phoneNumber": "xxxxxx",
                                                                "messageBody": "Hello, this should send!"
                                                              }
                                                            }
Jul 01 14:39:25 nemo[2245]: connect() failed
Jul 01 14:39:26 nemo[2245]: connect() failed
Jul 01 14:39:27 nemo[2245]: connect() failed
Jul 01 14:39:28 nemo[2245]: connect() failed
Jul 01 14:39:29 nemo[2245]: connect() failed
Jul 01 14:39:30 nemo[2245]: connect() failed
Jul 01 14:39:31 nemo[2245]: connect() failed
Jul 01 14:39:32 nemo[2245]: connect() failed
Jul 01 14:39:33 nemo[2245]: connect() failed
Jul 01 14:39:34 nemo[2245]: connect() failed
Jul 01 14:39:35 nemo[2245]: connect() failed
Jul 01 14:39:36 nemo[2245]: connect() failed
Jul 01 14:39:37 nemo[2245]: connect() failed`

**Comment by andyholmes** [comment] 2021-07-02 03:19
From your logs it looks like GSConnect is doing what it's supposed to. You might want to check the Android settings and permissions.

**Comment by daniellandau** [comment] 2021-07-03 11:25
Does the message get sent if you wake up and unlock the phone? If it's a power saving issue on Android side then there's not much that can be done.

**Comment by Filbuntu** [comment] 2021-07-03 11:49
Thank you, Andy & Daniel, for your tips! 
I use LineageOS. I deactivated Privacy Guard for KDE Connect, paused Blokada and unlocked the phone but still it does not work. In the settings I gave the App permissions for SMS, Telephone, Contacts, Storage but not for Location and Microphone.
Interestingly with another LineageOS smartphone it works ...
Anything else I could try?

Again a log, it looks similar to before:
```
GSConnect: 43 (user)
GJS:       16405
Session:   x11
OS:        Ubuntu 20.04.2 LTS
--------------------------------------------------------------------------------
-- Logs begin at Wed 2021-06-30 09:12:21 CEST, end at Sat 2021-07-03 13:41:53 CEST. --
Jul 03 13:41:00 nemo[2259]: connect() failed
Jul 03 13:41:01 nemo[2259]: connect() failed
Jul 03 13:41:02 nemo[2259]: connect() failed
Jul 03 13:41:03 nemo[2259]: connect() failed
Jul 03 13:41:04 nemo[2259]: connect() failed
Jul 03 13:41:05 nemo[2259]: connect() failed
Jul 03 13:41:06 nemo[2259]: connect() failed
Jul 03 13:41:07 nemo[2259]: connect() failed
Jul 03 13:41:08 nemo[2259]: connect() failed
Jul 03 13:41:09 nemo[2259]: connect() failed
Jul 03 13:41:10 nemo[2259]: connect() failed
Jul 03 13:41:11 nemo[2259]: connect() failed
Jul 03 13:41:12 nemo[2259]: connect() failed
Jul 03 13:41:13 nemo[2259]: connect() failed
Jul 03 13:41:14 nemo[2259]: connect() failed
Jul 03 13:41:15 kernel: Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
Jul 03 13:41:15 gnome-shell[1952]: ../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
Jul 03 13:41:15 nemo[2259]: connect() failed
Jul 03 13:41:16 nemo[2259]: connect() failed
Jul 03 13:41:17 nemo[2259]: connect() failed
Jul 03 13:41:18 nemo[2259]: connect() failed
Jul 03 13:41:19 nemo[2259]: connect() failed
Jul 03 13:41:20 nemo[2259]: connect() failed
Jul 03 13:41:21 nemo[2259]: connect() failed
Jul 03 13:41:22 nemo[2259]: connect() failed
Jul 03 13:41:23 nemo[2259]: connect() failed
Jul 03 13:41:24 nemo[2259]: connect() failed
Jul 03 13:41:25 nemo[2259]: connect() failed
Jul 03 13:41:26 kernel: Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
Jul 03 13:41:26 gnome-shell[1952]: ../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
Jul 03 13:41:26 nemo[2259]: connect() failed
Jul 03 13:41:27 nemo[2259]: connect() failed
Jul 03 13:41:28 nemo[2259]: connect() failed
Jul 03 13:41:29 systemd-resolved[1270]: Grace period over, resuming full feature set (UDP+EDNS0) for DNS server 192.168.xxx.1.
Jul 03 13:41:29 nemo[2259]: connect() failed
Jul 03 13:41:30 nemo[2259]: connect() failed
Jul 03 13:41:31 nemo[2259]: connect() failed
Jul 03 13:41:32 nemo[2259]: connect() failed
Jul 03 13:41:33 nemo[2259]: connect() failed
Jul 03 13:41:34 nemo[2259]: connect() failed
Jul 03 13:41:35 nemo[2259]: connect() failed
Jul 03 13:41:36 nemo[2259]: connect() failed
Jul 03 13:41:37 nemo[2259]: connect() failed
Jul 03 13:41:38 nemo[2259]: connect() failed
Jul 03 13:41:39 nemo[2259]: connect() failed
Jul 03 13:41:40 org.gnome.Shell.Extensions.GSConnect[2346]: [/service/device.js:sendPacket:446]: Xiaomi: {
                                                              "id": 1625312500522,
                                                              "type": "kdeconnect.sms.request",
                                                              "body": {
                                                                "sendSms": true,
                                                                "phoneNumber": "+xxxx",
                                                                "messageBody": "test it again"
                                                              }
                                                            }
Jul 03 13:41:40 nemo[2259]: connect() failed
Jul 03 13:41:41 nemo[2259]: connect() failed
Jul 03 13:41:42 nemo[2259]: connect() failed
Jul 03 13:41:43 nemo[2259]: connect() failed
Jul 03 13:41:44 nemo[2259]: connect() failed
Jul 03 13:41:45 nemo[2259]: connect() failed
Jul 03 13:41:46 nemo[2259]: connect() failed
Jul 03 13:41:47 nemo[2259]: connect() failed
Jul 03 13:41:48 nemo[2259]: connect() failed
Jul 03 13:41:49 nemo[2259]: connect() failed
Jul 03 13:41:50 nemo[2259]: connect() failed
Jul 03 13:41:51 gnome-shell[1952]: ../clutter/clutter/clutter-actor.c:10558: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
Jul 03 13:41:51 nemo[2259]: connect() failed
Jul 03 13:41:52 nemo[2259]: connect() failed
Jul 03 13:41:53 nemo[2259]: connect() failed
```

**Comment by daniellandau** [comment] 2021-07-03 12:11
If it works on another phone then most probably there's nothing to be done on GSConnect side.

**Comment by Filbuntu** [comment] 2021-07-03 12:17
Any tip how I can try to make it happen?
The LineageOS has not been updated for a long time and also the settings not. Only GSConnect, KDE Connect and Ubuntu have seen updates. The sending of SMS has not worked for months. The Privacy Guard states that the last time it could allow to send an SMS was the 23th April although I thought it has not worked for a longer time and I just hoped it will be a temporary thing.

**Comment by andyholmes** [comment] 2022-08-03 00:50
Best advice is to open an upstream report at https://bugs.kde.org. It seems like GSConnect is not doing anything wrong here.

**Closed by andyholmes** 2022-08-03 00:50 UTC
Labels: needs info

**Comment by Filbuntu** [comment] 2022-08-04 14:57
Thank you for the feedback. I will do so!
