### ISSUE TITLE
cannot mount phone anymore

### ISSUE THREAD

**Issue by jpritikin** [GSConnect/gnome-shell-extension-gsconnect#1830] opened 2024-06-20 20:34 UTC
### Describe the bug

Mount using sshfs doesn't work

### Steps to reproduce

Select "Mount" -- nothing happens

### Expected behavior

Phone file system should show up in nautilus file browser.

### GSConnect version

57

### Installed from

GNOME Extensions website

### GNOME Shell version

46.0-0ubuntu5.1

### Linux distribution/release

Ubuntu 24.04

### Paired device(s)

OnePlus 7T

### KDE Connect app version

1.31.1

### Support log

```plain text
Jun 20 13:31:22 oilfree gjs[15815]: JS ERROR: OnePlus 7T: Gio.IOErrorEnum: Permission denied
                                    _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
                                    _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
                                    ### Promise created here: ###
                                    _handleMount@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:228:24
                                    async*handlePacket@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:121:26
                                    handlePacket@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:435:25
                                    _readLoop@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:359:22
                                    async*setChannel@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:340:18
                                    _onChannel@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:234:20
                                    channel@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:432:19
                                    _onIncomingChannel@file:///home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:252:18
                                    async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by ferdnyc** [comment] 2024-06-21 06:12
Closing as duplicate of #1203 (which is pinned, and which I've just reopened). Mounting definitely still has known issues.

**Closed by ferdnyc** 2024-06-21 06:12 UTC
Labels: triage
