### ISSUE TITLE
cannot detect devices + error notification

### ISSUE THREAD

**Issue by MARTINrichard05** [GSConnect/gnome-shell-extension-gsconnect#1571] opened 2023-02-26 13:13 UTC
### Describe the bug

cannot start gsconnect correctly

### Steps to reproduce

1. enable the extension (open your session, from the extension manager)
2. get the error notification

### Expected behavior

work and detect devices on the same network with kdeconnect app

### GSConnect version

54

### Installed from

OS package manager

### GNOME Shell version

43.0

### Linux distribution/release

Nobara project

### Paired device(s)

cannot pair

### KDE Connect app version

1.22.2

### Support log

```plain text
/(?:cn|CN) ?= ?([^,\n]*)/.exec(...) is null

get@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:393:64
_initCertificate@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:182:13
start@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:255:25
start@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:458:14
vfunc_startup@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

### Notes

the version from gnome extension's website just shows waiting for service

**Comment by eode** [comment] 2024-01-02 17:54
This issue seems to be specifically with first-time installation.  I ran into this as well, but after a reboot (I didn't check just a logout/login), things worked fine.

**Comment by andyholmes** [comment] 2024-03-03 17:40
Closing as a duplicate of #1209

**Closed by andyholmes** 2024-03-03 17:40 UTC
Labels: triage
