### ISSUE TITLE
Can't Share multiple files at the same time

### ISSUE THREAD

**Issue by Ex-Origin** [GSConnect/gnome-shell-extension-gsconnect#1809] opened 2024-05-19 03:51 UTC
### Describe the bug

When I Share multiple files to my phone, only the first file can be successfully transferred, and all other files fail. However, this problem does not occur when my phone Shares multiple files to my PC.

### Steps to reproduce

1. Click on 'Share'
2. Select multiple files
3. Click on 'Send'

### Expected behavior

All files can be successfully transferred.

### GSConnect version

57

### Installed from

GNOME Extensions website

### GNOME Shell version

46.0

### Linux distribution/release

Ubuntu 24.04 LTS

### KDE Connect app version

1.30.1

**Comment by ferdnyc** [comment] 2024-05-22 00:14
Duplicate of #1025.

**Closed by ferdnyc** 2024-05-22 00:14 UTC
Labels: duplicate
