### ISSUE TITLE
Gnome file transfer receive notification only has Open buttons on first popup.

### ISSUE THREAD

**Issue by eliotb** [GSConnect/gnome-shell-extension-gsconnect#1641] opened 2023-06-15 04:00 UTC
### Describe the bug

When I transfer a file from android to PC, a notification box appears that has two buttons: Open Folder, and Open File.
That notification is only visible for a second or two (too short to interact with it unless I prepare in advance)
Then it disappears into the notification list that can be seen by clicking the Date/Time.
Clicking on the notification in that list dismisses it, rather than opening it and offering the same 2 Open buttons.

### Steps to reproduce

Any file transfer from mobile to desktop

### Expected behavior

Clicking the notification in the notification list expands it to offer the Open File and Open Folder buttons.

I think all notifications already have a close button, or there is a Clear All button if one doesn't want to use this requested function.

### GSConnect version

54

### Installed from

GNOME Extensions website

### GNOME Shell version

43.4

### Linux distribution/release

Debian 12 bookworm

### Paired device(s)

Samsung running Murea OS

### KDE Connect app version

1.25.0

**Comment by andyholmes** [comment] 2024-03-02 03:50
See also #1747, which was a duplicate of this.

**Closed by andyholmes** 2024-03-02 03:50 UTC
Labels: duplicate, can't fix, UX
