### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by raushnn** [GSConnect/gnome-shell-extension-gsconnect#1455] opened 2022-09-07 18:16 UTC
```
GSConnect: 47 (user)
GJS:       17200
Session:   wayland
OS:        Ubuntu 22.04.1 LTS

_loadBackends@/home/raushan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/raushan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/raushan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/raushan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/raushan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-10-08 19:26
Duplicate of #1256

**Closed by andyholmes** 2022-10-08 19:26 UTC
Labels: duplicate
