### ISSUE TITLE
Still doesn't work with Ubuntu 24.04 and Gnome Shell 46.0

### ISSUE THREAD

**Issue by heynnema** [GSConnect/gnome-shell-extension-gsconnect#1825] opened 2024-06-14 00:18 UTC
### Describe the bug

Still doesn't work with Gnome Shell 46.0. Doesn't even appear in quick settings menu.

### GSConnect version

57

### Installed from

GNOME Extensions website

### GNOME Shell version

46.0

### Linux distribution/release

Ubuntu 24.04

### Paired device(s)

Samsung A23

### KDE Connect app version

1.30.1

**Comment by zjcz** [comment] 2024-06-17 12:01
Working fine for me now on Ubuntu 24.04 and Gnome 46.0, but I did have to configure the ufw firewall first.  I can't remember if this came enabled in the default install or if I enabled it while messing with something else but might be worth checking out.

https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#firewall-configuration

**Comment by ArthurKnoep** [comment] 2024-06-17 13:53
I don't think OP has a firewall issue. The issue is that all the shorcuts (currently connected phone, view/send text, ring the phone, etc) doesn't appear in the quick setting menu under Gnome 46/Ubuntu 24.04
![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/27413532/dbc93e8a-19bc-4eba-842b-5889956f3ca1)

I've finally been able to make it work by opening "gnome-extensions-app" and checking the main checkbox at the top of the list, for some reason it was turned off. After that, turn on GSConnect too if it is off.
This should look like this:
![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/27413532/3d6abe2b-4f71-42e6-b33b-46642762c41b)

**Comment by heynnema** [comment] 2024-06-17 14:15
My firewall is setup correctly for GSConnect. Extensions are enabled. I'm missing the GSConnect icon in the top panel. I'm missing the quick settings menus. The GSConnect settings show that it's connected to my phone... even if GSConnect is turned off.

**Comment by heynnema** [comment] 2024-06-17 14:17
I just uninstalled GSConnect, and reinstalled it, and it's all working now.

**Comment by ferdnyc** [comment] 2024-06-26 04:15
Thanks for the update @heynnema.

Not ideal, but since the issues both you and @ArthurKnoep had were ultimately transient, I'm going to close this as "just one of those things". Extension activation/upgrade isn't 100% reliable, unfortunately. And since it's not under our control, it's unlikely we could do much about this anyway.

**Closed by ferdnyc** 2024-06-26 04:15 UTC
Labels: triage

**Comment by twistedpiper** [comment] 2024-10-05 15:55
What does transient even mean in these regards. I just had the same issue, Ubuntu doesn't come with extension manger by default and GSConnect doesn't enable itself by default, missing instructions or bad user experience!

**Comment by ferdnyc** [comment] 2024-10-06 13:52
@twistedpiper 

How did you install GSConnect, and what instructions did you follow to do so?

If installing from extensions.gnome.org, the extension should be enabled immediately upon installation. (The process of installation is presented **as** enabling the extension, in fact. You literally "switch it on" at https://extensions.gnome.org/extension/1319/gsconnect/ to trigger the install.)

GSConnect can't _enable itself_; that's not a power GNOME Shell extensions have.


> Ubuntu doesn't come with extension manger by default

Really? Weird. There's no Extensions app in the application grid? (Extensions is different from Extension Manager, effectively it's the GNOME built-in version. It **should** be standard with any GNOME 46 install. Extension Manager is third-party, so yeah I don't think it's installed by _default_ in any distro.)

**Comment by twistedpiper** [comment] 2024-10-06 21:48
Installed through the Ubuntu app center, good to know I can use the extensions site, thanks, definitely on 46 and no extensions. Based on this post looks like it's not preinstalled in Ubuntu. Followed the instructions there, now I have both.

https://askubuntu.com/questions/1329463/how-did-i-obtain-the-extensions-app
