### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by Novaes2019** [GSConnect/gnome-shell-extension-gsconnect#1293] opened 2022-03-14 23:26 UTC
```
GSConnect: 47 (user)
GJS:       17190
Session:   wayland
OS:        Ubuntu Jammy Jellyfish (development branch)

_loadBackends@/home/novaes/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/novaes/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/novaes/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/novaes/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/novaes/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by adipginting** [comment] 2022-03-17 10:49
Duplicate of https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1256

**Comment by daniellandau** [comment] 2022-03-19 21:09
Fix released on extensions.gnome.org

**Closed by daniellandau** 2022-03-19 21:09 UTC
