### ISSUE TITLE
GSConnect keeps disconnecting every 5 a 10 minutes for 2 seconds

### ISSUE THREAD

**Issue by patricklibert** [GSConnect/gnome-shell-extension-gsconnect#1660] opened 2023-07-20 20:39 UTC
### Describe the bug

GSConnect: Ubuntu 22.04 connected by wire.
KDE Connect: Samsung S23

From this month something changed: GSConnect gets disconnected every 5 a 10 minutes just for two seconds and then reconnects automatically.

Please note that this is not a battery optimatisation problem on the samsung phone. The settings are correct on the phone.
"Do not optimize battery for KDE Connect".

### Steps to reproduce

Just install it on ubuntu and S23

### Expected behavior

Steady connection

### GSConnect version

50

### Installed from

Extension Manager

### Linux distribution/release

Ubuntu 22.04

### Paired device(s)

Samsung S23

### KDE Connect app version

1.27.0

### Support log

```plain text
jul 20 22:14:37 gjs[2496]: JS ERROR: Galaxy S23: Gio.IOErrorEnum: Unknown error 255
                           Cannot stat /home/redman/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/home/redman/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
```

### Notes

Disabling SFTP in GSConnect doesn't seems to help

**Comment by patricklibert** [comment] 2023-07-20 20:45
Support log:
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
jul 20 22:44:03 gnome-shell[2147]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed

**Comment by andyholmes** [comment] 2023-07-21 04:34
Could you provide a support log including the disconnect messages?

**Comment by patricklibert** [comment] 2023-07-21 09:53
It's driving me crazy.
I used all morning the "generate support" log button to find the disconnect messages and also gnome-logs.
There are sometimes gsconnect messages but they seems nothing to have to do with a "disconnect" message.
Mostly of the times, the generated support log is empty after a disconnect for two seconds.

Can I do more to analyse this problem?

**Comment by patricklibert** [comment] 2023-07-21 15:55
This bug report has maybe nothing to do with GSConnect.

I installed a Ping Tool on my Samsung S23 and pinged my ubuntu pc and it also loses for 2 seconds 'Pings'...

**Comment by andyholmes** [comment] 2023-07-21 18:27
> Can I do more to analyse this problem?

I'm not really a networking expert, trying to ping your device is a good smoke test, so that does imply there's something funky on your network. Is it possible you've set two device with the same static IP? I've done that before and weird things happen.

To use the support log feature, its important to note you have to leave the popup dialog open during the event you're trying to capture. The "debug mode" logs indiscriminately, and may contain SMS messages and other private information, so this information is only logged while the dialog is open.

If all that log says is "disconnected (IP Address)" etc, then that usually means its not GSConnect. I'm not aware of any "find network problems app" unfortunately, so all I really know of is Wireshark and that's a different kind of tool.

**Comment by daniellandau** [comment] 2023-07-21 18:32
Maybe WiFi issues? Could try to ping something on the internet (like 8.8.8.8 or 1.1.1.1, not commenting on those companies but they are available for pinging) to see if that drops too for 2 seconds.

**Comment by patricklibert** [comment] 2023-08-04 19:17
I'm really sorry  for the late response. I didn't know that you have to leave the log window open.

I think this is the 'disconnect' message every time:

`aug 04 21:09:36 org.gnome.Shell.Extensions.GSConnect[2147]: [/service/core.js:readPacket/</<:233]: Galaxy S23: Error receiving data: Connection timed out
                                                            readPacket/</<@/home/redman/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:233:45
                                                            @/home/redman/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
                                                            
                                                            `
                                                            
                                                            
Is it a network problem?

**Comment by andyholmes** [comment] 2023-08-04 19:31
Well, it is what it says: the connection timed out. So the device didn't respond to a keepalive packet or other communication.

It could be your network, your phone going into sleep mode, but that's not a bug :shrug:

**Comment by patricklibert** [comment] 2023-08-04 19:35
I'm doing an autoscan on my accesspoint for finding the right channels. This will take 10minutes.
Battery optimatisation for the KDE connect are off on the S23, so it can't be sleep mode I guess.

Anyway thanks for the help.

**Comment by andyholmes** [comment] 2023-09-20 01:05
Closing, since I believe this is not a bug in GSConnect. Feel free to re-open if there's evidence otherwise.

**Closed by andyholmes** 2023-09-20 01:05 UTC
Labels: needs info
