### ISSUE TITLE
GSConnect: TypeError

### ISSUE THREAD

**Issue by jcuretti** [GSConnect/gnome-shell-extension-gsconnect#1549] opened 2022-12-29 15:00 UTC
### Describe the bug

"GSConnect: TypeError" when turnning on. 

### GSConnect version

50

### Installed from

GNOME Extensions website

### Linux distribution/release

Ubuntu 22.04

### Support log

```plain text
/(?:cn|CN) ?= ?([^,\n]*)/.exec(...) is null

get@/home/julian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:393:64
_initCertificate@/home/julian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:182:13
start@/home/julian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/julian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:255:25
start@/home/julian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:458:14
vfunc_startup@/home/julian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/julian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/julian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

### Screenshots

![image](https://user-images.githubusercontent.com/26986209/209971005-4acdb3a0-5287-470f-b41f-7c4d49523eae.png)

**Comment by richou672005** [comment] 2023-02-26 13:15
same issue

**Comment by ferdnyc** [comment] 2023-04-19 21:55
This is most likely a duplicate of #1209 (involving updates to `openssl`), there's also more information in #1395. Please see those issues for details.

**Closed by ferdnyc** 2023-04-19 21:55 UTC
Labels: duplicate
