### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by onhao** [GSConnect/gnome-shell-extension-gsconnect#1295] opened 2022-03-15 10:07 UTC
```
GSConnect: 47 (user)
GJS:       17190
Session:   x11
OS:        Ubuntu Jammy Jellyfish (development branch)

_loadBackends@/home/wuhao/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/wuhao/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/wuhao/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/wuhao/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/wuhao/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by adipginting** [comment] 2022-03-17 10:49
Duplicate of https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1256

**Comment by daniellandau** [comment] 2022-03-19 21:09
Fix released on extensions.gnome.org

**Closed by daniellandau** 2022-03-19 21:09 UTC
