### ISSUE TITLE
Release Version 54 [Gnome Shell Extensions]

### ISSUE THREAD

**Issue by bevsxyz** [GSConnect/gnome-shell-extension-gsconnect#1412] opened 2022-07-09 09:47 UTC
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

The latest release version for GSConnect at  https://extensions.gnome.org/extension/1319/gsconnect/ for Gnome shell versions 40+ are as follows:

1. 42 - v50
2. 41 - v48, v49
3. 40 - v46, v47

The latest version, v53, is only shown for shell version 3.36. This could be in parts due to the version bump being updated in the meson build file months after the release of v53 https://github.com/GSConnect/gnome-shell-extension-gsconnect/commit/80c3d156fbc61c97d3a3a004172f41056d8ff316 .

Irrespective of that, at least one issue works with the latest commit in repo #1406. I think that is a good enough reason for a new release. If there are any others, feel free to mention them here.

**Comment by AlynxZhou** [comment] 2022-07-14 08:17
> I installed gsconnect from AUR, and because v53 is the biggest version number, now I have v53 with my gnome-shell 42, and after months I found this issue and have to do a manually downgrade. I am not sure why the latest version is not for latest gnome-shell, but I suggest to release a new version to solve all of these.

Or maybe I should ask AUR maintainer to add an epoch because he chose wrong version before.

**Comment by AlynxZhou** [comment] 2022-07-14 09:46
> What I have reported here is only for the packaging with the gnome-extension website. I think it is mentioned in the README that the developers support only the latest gnome-shell version moving forward. So you should be alright. No need to downgrade.

Nope, v53 does not work with GNOME Shell 42, I am not sure if this is by design or just a mistake of version in metadata.json.

**Comment by bevsxyz** [comment] 2022-07-14 11:46
> > What I have reported here is only for the packaging with the gnome-extension website. I think it is mentioned in the README that the developers support only the latest gnome-shell version moving forward. So you should be alright. No need to downgrade.
> 
> Nope, v53 release does not work with GNOME Shell 42, I am not sure if this is by design or just a mistake of version in metadata.json.

I had tried the release file for v53. It worked for me. I'm currently using the latest commit because the feature of a bug which was fixed after the v53.

**Comment by bevsxyz** [comment] 2022-07-14 11:52
@AlynxZhou you could try installing from the zip file directly. https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip

Or perhaps build from the git repo.

**Comment by andyholmes** [comment] 2022-07-14 22:08
> Due to this, even if you installed the v53 tag or release, you would end up with v50 in the GUI. This could have already caused a packaging issue with Gnome extensions.

Hmm, are you sure about this? It looks like the `53` bump did make it into the [v53 tag](https://github.com/GSConnect/gnome-shell-extension-gsconnect/compare/main...v53) and the Zip file I just downloaded from extensions.gnome.org seems to have `53` in the `metadata.json`.

It looks like the order of the releases (v50: 42, v51: 40, v52: 3.36-38, v53: 3.36) is what confused the Arch packaging system. [This comment](https://aur.archlinux.org/packages/gnome-shell-extension-gsconnect#comment-873869) seems to suggest there's a procedure for dealing with these situations in Arch, though.

**Comment by daniellandau** [comment] 2022-07-15 09:21
The supported method of installing gsconnect is through extensions.gnome.org, which uses your shell version to figure out what is the latest extension version that is compatible. The AUR maintainer blindly took the latest version, which was a bugfix backport release to fix a memory leak. Any issues specific to the AUR package including the proposed solution of including an epoch should be directed at the AUR package.

**Comment by AlynxZhou** [comment] 2022-07-15 09:23
> The supported method of installing gsconnect is through extensions.gnome.org, which uses your shell version to figure out what is the latest extension version that is compatible. The AUR maintainer blindly took the latest version, which was a bugfix backport release to fix a memory leak. Any issues specific to the AUR package including the proposed solution of including an epoch should be directed at the AUR package.

Thanks, already asked AUR maintainer to add epoch.

**Comment by bevsxyz** [comment] 2022-07-15 16:18
> > Due to this, even if you installed the v53 tag or release, you would end up with v50 in the GUI. This could have already caused a packaging issue with Gnome extensions.
> 
> Hmm, are you sure about this? It looks like the `53` bump did make it into the [v53 tag](https://github.com/GSConnect/gnome-shell-extension-gsconnect/compare/main...v53) and the Zip file I just downloaded from extensions.gnome.org seems to have `53` in the `metadata.json`.
> 
> It looks like the order of the releases (v50: 42, v51: 40, v52: 3.36-38, v53: 3.36) is what confused the Arch packaging system. [This comment](https://aur.archlinux.org/packages/gnome-shell-extension-gsconnect#comment-873869) seems to suggest there's a procedure for dealing with these situations in Arch, though.

I am sorry. I checked the release again, the versioning is alright for v53. Before, when I tried, there was an issue with the GUI version.

**Comment by andyholmes** [comment] 2022-07-15 20:49
> I am sorry. I checked the release again, the versioning is alright for v53. Before, when I tried, there was an issue with the GUI version.

No problem. There's a bug lingering around that stops the preferences window from properly exiting in some situations. I expect you might've been looking at the older version, even though you'd installed the latest :)

**Comment by ferdnyc** [comment] 2022-07-18 01:58
@andyholmes
> It looks like the order of the releases (v50: 42, v51: 40, v52: 3.36-38, v53: 3.36) is what confused the Arch packaging system. [This comment](https://aur.archlinux.org/packages/gnome-shell-extension-gsconnect#comment-873869) seems to suggest there's a procedure for dealing with these situations in Arch, though.

It should probably-maybe be made part of the release process to release things in the opposite order, if _possible_. (Sometimes it isn't, of course, like when there's a bug fix for an older shell.) e.g.o will do the right thing in all cases, we've  seen, but distro packagers will almost certainly want the latest version for the latest shell, and there's no sense in making it more difficult than it has to be for them to keep track of which one that is.

(The other thing we might consider — though it would've been a lot more helpful if I'd suggested this _before_ our version numbering got ahead of the Shell versions — is adopting a GitHub/package release numbering that's more informative than just the linear e.g.o release "counter". Like, for instance, we could define the release numbers as `${latest_comatible_shell_version}.${e.g.o_release_number}`, so that the newest release would have been `v42.50`, followed by `v40.51`, then `v38.52`, and finally `v36.53`.

Assuming versions are next released for only GNOME 40 and 42, those would be `v40.54` and `v42.55`. Everything lines up that way, **but** even if they were reversed it wouldn't change anything about the version number ordering: whether it's `v40.54` and `v42.55` or `v42.54` and `v40.55`, either way the GNOME 42 version is highest.)

Doing that now (with the Shell versions lower than our e.g.o versions) would require a one-time rewind of our version numbering for the distros' packaging, but all distros have some sort of epoch feature in their numbering for exactly that purpose.

**Comment by ferdnyc** [comment] 2022-07-18 01:58
cc: @daniellandau

**Comment by andyholmes** [comment] 2022-07-18 02:33
That's probably not a bad idea, assuming someone wants to keep rolling backported releases.

There's really no reason why the e.g.o version has to match our tags anyways, and really e.g.o will override those anyways since `version` is actually more like "submission number". `meson` has the string utils to split a version like `v42.55` into `42` and `55` as substitutions for `metadata.json`, so it's doable without too much manual intervention.

**Comment by jbicha** [comment] 2022-07-29 15:35
Could you reopen this bug?

There is value in having distros package this extension since distros can make sure the dependencies are installed for improved integration.

Using a non-linear version numbering system where the highest version number (53) is not an upgrade from older versions (50)  is unexpected and can easily lead to distros making mistakes and you getting bug reports when the extension no longer works.

I would have expected the bugfix version number for the older serious to add a suffix. So if you're making a bugfix release for 43, you could use 43.1. Then it wouldn't affect people using the latest series.

To fix this bug, could you do a new 54 release now?

**Comment by andyholmes** [comment] 2022-11-03 21:34
Closing since v54 was ultimately released for GNOME 43.

**Closed by andyholmes** 2022-11-03 21:34 UTC
