### ISSUE TITLE
gsconnect extension makes memory of gnome shell grow

### ISSUE THREAD

**Issue by g3blv** [GSConnect/gnome-shell-extension-gsconnect#1138] opened 2021-07-04 16:06 UTC
**Describe the bug**

The memory allocated to the gnome shell process grows to 1-2 GB after a full days use with gsconnect extension enabled. The CPU also spikes and makes the system freeze for a few seconds. This doesn't happen when the gsconnect extension is disabled.

**Support Log**

I'm not able to upload sysprof file here but it is available here https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4430.

**System Details (please complete the following information):**

 - **GSConnect version:** 47
 - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 40.1.0
 - **Distro/Release:** Fedora 34

**Comment by daniellandau** [comment] 2021-07-04 16:20
It's already reported on https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1028 but none of the devs have magaged to reproduce and we haven't been able to get it fixed. I'll definitely look closely on your findings on g.g.o as soon as I have time

**Comment by daniellandau** [comment] 2021-07-04 16:52
Couldn't make much out of it. Could you also try to move your `.cache/gsconnect` directory to a safe backup spot and see if you could narrow down what is needed for reproducing the issue? In the g.g.o syscap there was an indication that the GSConnect daemon was forking a couple of processes before the hangup, but I don't think it included any information about what the other processes were. More information is needed, but unfortunately I don't have a clear idea what it could be exactly.

**Comment by andyholmes** [comment] 2022-08-03 01:19
Closing since this issue was resolved in recent releases of GSConnect.

**Closed by andyholmes** 2022-08-03 01:19 UTC
