### ISSUE TITLE
can't ran on ubuntu 23.10 with gnome 45

### ISSUE THREAD

**Issue by AlexeyPogorelov** [GSConnect/gnome-shell-extension-gsconnect#1708] opened 2023-11-07 22:45 UTC
### Describe the bug

The daemon not starts after install

```
Child process exited with code 1

Gio.TlsCertificate.new_for_paths@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/utils/setup.js:375:14
_initCertificate@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:184:48
start@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:450:18
_loadBackends@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:259:25
start@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:462:14
vfunc_startup@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:263:22
vfunc_handle_local_options@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:660:18
@/home/alex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:720:17
```

### Steps to reproduce

1. install the extension
2. check the system message with error

### Expected behavior

should run without error

### GSConnect version

56

### Installed from

GNOME Extensions website

### GNOME Shell version

45.0

### Linux distribution/release

Ubuntu 23.10

### Paired device(s)

iPhone 8

### KDE Connect app version

0.3.0

### Screenshots

![image](https://github.com/GSConnect/gnome-shell-extension-gsconnect/assets/6617585/64deff71-edd8-4c07-9df2-a3c01ba93afe)

**Comment by sarowarhosen03** [comment] 2023-11-20 14:29
solved?

**Comment by AlexeyPogorelov** [comment] 2023-12-01 14:41
> solved?

No. Looks like the issue is not related to the extension. As far as I understand it's because of certs issue.

**Comment by andyholmes** [comment] 2024-03-02 00:46
Closing as a duplicate of #1209

See also: https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1209#issuecomment-974808691

**Closed by andyholmes** 2024-03-02 00:46 UTC
Labels: duplicate
