### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by xdequinze** [GSConnect/gnome-shell-extension-gsconnect#1451] opened 2022-09-01 13:27 UTC
```
GSConnect: 53 (user)
GJS:       17200
Session:   x11
OS:        Ubuntu 22.04.1 LTS

_loadBackends@/home/xdequinze/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:31
start@/home/xdequinze/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/xdequinze/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/xdequinze/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:666:18
@/home/xdequinze/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:729:17
```

**Comment by andyholmes** [comment] 2022-10-08 19:26
Duplicate of #1256

**Closed by andyholmes** 2022-10-08 19:26 UTC
Labels: duplicate
