### ISSUE TITLE
Messages window opens with exaggerated width

### ISSUE THREAD

**Issue by barondem** [GSConnect/gnome-shell-extension-gsconnect#1264] opened 2022-03-04 10:38 UTC
**Describe the bug**

When opening the Messages window it opens and loads SMSs correctly, but the window width is too big (from GTK Inspector I get 28161x569 on my 1920x1080 screen) for the screen and it's also unresizable, so this makes the window quite unusable, given that window becomes very slow and laggish; the biggest problem, though, is that the window is not resizable, so there is no workaround to the issue (the resize button is present but it doesn't actually minimize/maximize the window).

**Steps To Reproduce:**

1. Go to 'Device Settings' for a connected device
2. Click on 'Messages'
3. The window width is too big

**Expected behavior**
The window width is reasonable and the window is actually resizable.

**Screenshots**
![overview](https://user-images.githubusercontent.com/6568392/156747824-98cd80c5-42d9-4b3b-96d1-b832fe0cb25a.png)
This is the overiew when four other windows and the messages window are open (the two Chrome windows on the top-right are 1920x1080 so it should give an idea of how large the window is).

**Support Log**

No relevant log entries found :disappointed:

**System Details (please complete the following information):**

 - **GSConnect version:** 48
   - **Installed from:** dnf
 - **GNOME/Shell version:** 41
 - **Distro/Release:** Fedora 35

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Galaxy S8
 - **KDE Connect app version:** 1.19.1
 - **Plugin(s):** SMS plugin

**Comment by andyholmes** [comment] 2022-03-04 21:42
Duplicate of #1228

**Closed by andyholmes** 2022-03-04 21:42 UTC
Labels: duplicate
