### ISSUE TITLE
It's impossible to mount device

### ISSUE THREAD

**Issue by Xejonue** [GSConnect/gnome-shell-extension-gsconnect#1430] opened 2022-08-01 17:06 UTC
**Describe the bug**

**Steps To Reproduce:**

1. Go to menu (on the top-right)
2. Click on Device name -> 'Mount', then click 'Settings'
3. Click on three dots near the 'minimize' button
4. Generate logs
5. See errors

**Expected behavior**

I expected to see my device in explorer without connecting it within cable.

**Support Log**

```
GSConnect: 50 (system)
GJS:       17201
Session:   wayland
OS:        Manjaro Linux
--------------------------------------------------------------------------------
авг 01 19:27:03 touchegg.desktop[1328]: Error connecting to Touchégg daemon: Could not connect: Connection refused
авг 01 19:27:03 touchegg.desktop[1328]: Reconnecting in 5 seconds...
авг 01 19:27:17 gnome-shell[991]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
авг 01 19:27:18 gjs[1363]: JS ERROR: AMN-LX9: Gio.IOErrorEnum: Сбой подключения
                              _handleMount/</<@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                              @/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
авг 01 19:27:18 gjs[1363]: JS ERROR: AMN-LX9: Gio.IOErrorEnum: Неизвестная ошибка 255
                              Cannot stat /home/xejonue/.ssh/known_hosts: No such file or directory
                              _removeHostKey/</<@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                              @/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**System Details (please complete the following information):**

 - **GSConnect version:** 50
 - **Installed from:** Enabled from GNOME Extensions
 - **GNOME/Shell version:** 42.3
 - **Distro/Release:** Manjaro 21.3.6 (Ruah)

**GSConnect environment (if applicable):**

 - **Paired Device(s):** HUAWEI Y5 2019
 - **KDE Connect app version:** 1.19.1
 - **Plugin(s):** -

![Screenshot 1](https://user-images.githubusercontent.com/76466002/182204543-2ac91104-d255-4e9c-8e71-8165062efcb6.png)
![Screenshot 2](https://user-images.githubusercontent.com/76466002/182204177-9f4b38dd-2d41-46bf-8b6a-97079f887c6c.png)

**Comment by andyholmes** [comment] 2022-08-02 22:24
Seems like another duplicate of #1203.

If the solution there does not work, feel free to re-open.

**Closed by andyholmes** 2022-08-02 22:24 UTC
Labels: duplicate
