### ISSUE TITLE
unable to bind shortcutkey in ubunntu 22.04, says key already in use

### ISSUE THREAD

**Issue by ravi0900** [GSConnect/gnome-shell-extension-gsconnect#1386] opened 2022-06-10 19:08 UTC
GSConnect: 50 (user)
GJS:       17200
Session:   x11
OS:        Ubuntu 22.04 LTS
--------------------------------------------------------------------------------
Jun 11 00:34:06 kernel: sd 0:0:0:0: [sda] Synchronizing SCSI cache
Jun 11 00:34:06 kernel: sd 0:0:0:0: [sda] Stopping disk
Jun 11 00:34:22 systemd-timesyncd[586]: Initial synchronization to time server 91.189.91.157:123 (ntp.ubuntu.com).
Jun 11 00:34:40 gjs[431104]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: GrabAccelerator is not allowed
                             checkAccelerator/action</<@/home/ravi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/keybindings.js:226:42
                             @/home/ravi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences:115:21
Jun 11 00:34:40 gjs[431104]: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Jun 11 00:34:41 gjs[431104]: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

**Comment by andyholmes** [comment] 2022-06-10 22:41
Duplicate of #1215

**Closed by andyholmes** 2022-06-10 22:41 UTC
Labels: duplicate
