### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by taydy00** [GSConnect/gnome-shell-extension-gsconnect#1436] opened 2022-08-11 14:16 UTC
```
GSConnect: 53 (user)
GJS:       17200
Session:   wayland
OS:        Ubuntu 22.04.1 LTS

_loadBackends@/home/taydy/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:31
start@/home/taydy/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/taydy/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/taydy/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:666:18
@/home/taydy/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:729:17
```

**Comment by andyholmes** [comment] 2022-08-12 08:23
Duplicate of #1256

**Closed by andyholmes** 2022-08-12 08:23 UTC
Labels: duplicate
