### ISSUE TITLE
Bluetooth support for GSConnect?

### ISSUE THREAD

**Issue by AlphaRant9** [GSConnect/gnome-shell-extension-gsconnect#1671] opened 2023-09-04 01:54 UTC
### Describe your request

KDE Connect has supported bluetooth through a configuration of the android package and desktop application for a while now, and the last time the bluetooth channel for GSConnect was updated was 3 years ago. Is there any effort to bring this into the mainstream channel or a set of steps I can take to build it locally with bluetooth support enabled?

### GSConnect version

55

### Installed from

GNOME Extensions website

### GNOME Shell version

44.3

### Linux distribution/release

Debian Testing

**Comment by andyholmes** [comment] 2023-09-04 19:44
The original issue #17 was locked after several years of "me too" comments, although I'll be happy to re-open it if you're interested in working on the issue. There is a [description of the steps](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/17#issuecomment-594157159) in that issue, although I'd it expect it to be out of date.

It would probably be best to start from scratch, and possible just reference the old implementation. Unfortunately, without anyone actually testing the implementation at the time I don't have much confidence it works very well though.

**Comment by andyholmes** [comment] 2023-09-19 22:14
Closing as a duplicate of #17, which has a better summary of the current situation.

Feel free to comment if you'd like to pick up the issue.

**Closed by andyholmes** 2023-09-19 22:14 UTC
Labels: duplicate
