### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by andretisch** [GSConnect/gnome-shell-extension-gsconnect#1460] opened 2022-09-12 20:39 UTC
```
GSConnect: 53 (user)
GJS:       17200
Session:   wayland
OS:        Ubuntu 22.04.1 LTS

_loadBackends@/home/andrew/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:31
start@/home/andrew/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/andrew/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/andrew/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:666:18
@/home/andrew/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:729:17
```

**Comment by andyholmes** [comment] 2022-10-08 19:26
Duplicate of #1256

**Closed by andyholmes** 2022-10-08 19:26 UTC
Labels: duplicate
