### ISSUE TITLE
"Clipboard Push" menu option

### ISSUE THREAD

**Issue by alecpetrosky** [GSConnect/gnome-shell-extension-gsconnect#1349] opened 2022-05-08 22:11 UTC
**Is your feature request related to a problem? Please describe.**
As @andyholmes explained in #1215 currently there's no easy workaround/fix for global shortcuts on latest Gnome Wayland. On the other hand, the problem is some way similar to the Android 10+ path taken by Google restricting global clipboard access.  

**Describe the solution you'd like**
We have a nice and secure solution on Android side when we can manually send Clipboard content to another device:

![20220508_165828_Screenshots](https://user-images.githubusercontent.com/62790032/167317546-04b321cc-6b8e-4558-a923-6c766d96a7ba.png)

In my opinion, it could be great to have something similar in Gnome version of GSConnect (such as "Clipboard Push" menu option for each individual connected device):

![Screenshot from 2022-05-08 16-53-54](https://user-images.githubusercontent.com/62790032/167317604-295c15c2-fead-4950-9ea5-e87e996a93fb.png)

**Additional context**
It would be quite straightforward solution which shouldn't require much effort to implement and which fits in the current security paradigm offered by Android/Gnome. I have no experience with Gnome Extension development but I could try to implement it if you'd like me to do so.

**Comment by andyholmes** [comment] 2022-05-08 22:42
This seems like a duplicate of #1167.

The menu editor code was never completed, but `clipboardPull` and `clipboardPush` could be added to the GSettings default:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/07ef895ae5eb96c4ee55b900f4f6811a77aca7ad/data/org.gnome.Shell.Extensions.GSConnect.gschema.xml#L48-L50

**Comment by alecpetrosky** [comment] 2022-05-09 03:57
@andyholmes thanks for your valuable reply. Is the any global config for "stock" system-wide installed extension? If not, is downloading the source, changing defaults in `gschema.xml` and installing the extension the possible solution?

**Comment by andyholmes** [comment] 2022-05-09 04:56
That file is basically the source of defaults, but it is compiled into a shared file by the system (or session). If you're installing from RPM or something, I guess a [vendor override](https://docs.gtk.org/gio/class.Settings.html#vendor-overrides) would be the easiest way to change that downstream.

Alternatively you could submit a PR with the changes to the above file. I don't usually weigh in on user-visible changes anymore, but if say @ferdnyc or @daniellandau don't have a problem with it we could probably merge it.

**Comment by andyholmes** [comment] 2022-05-18 21:40
Going to close this as a duplicate of #1167 now, feel free to ask more questions if you need help with this.

**Closed by andyholmes** 2022-05-18 21:40 UTC
Labels: duplicate
