### ISSUE TITLE
/(?:cn|CN) ?= ?([^,\n]*)/.exec(...) is null

### ISSUE THREAD

**Issue by jacobzimmermann** [GSConnect/gnome-shell-extension-gsconnect#1129] opened 2021-06-15 00:23 UTC
```
GSConnect: 46 (user)
GJS:       16801
Session:   wayland
OS:        Fedora 34.20210614.0 (Silverblue)

get@/var/home/jzimm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:393:64
_initCertificate@/var/home/jzimm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:182:13
start@/var/home/jzimm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/var/home/jzimm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/var/home/jzimm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/var/home/jzimm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/var/home/jzimm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/var/home/jzimm/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by sonnyp** [comment] 2021-06-18 20:56
Duplicate of https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1118
Please report your version of OpenSSL there if you'd like to help.

**Closed by sonnyp** 2021-06-18 20:56 UTC
