### ISSUE TITLE
/(?:cn|CN) ?= ?([^,\n]*)/.exec(...) is null

### ISSUE THREAD

**Issue by jar127** [GSConnect/gnome-shell-extension-gsconnect#1498] opened 2022-10-26 22:15 UTC
```
GSConnect: 50 (user)
GJS:       17202
Session:   wayland
OS:        Fedora Linux 36 (Workstation Edition)

get@/home/jar/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:393:64
_initCertificate@/home/jar/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:182:13
start@/home/jar/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/jar/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:255:25
start@/home/jar/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:458:14
vfunc_startup@/home/jar/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/jar/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/jar/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by ferdnyc** [comment] 2022-11-21 03:49
Duplicate of #1453.

**Closed by ferdnyc** 2022-11-21 03:49 UTC
Labels: triage
