### ISSUE TITLE
Mount failure

### ISSUE THREAD

**Issue by venusuranus** [GSConnect/gnome-shell-extension-gsconnect#1422] opened 2022-07-20 17:15 UTC
**Description**

The Mount function doesn't seem to work. Nothing shows or happens when clicking mount, and the phone remains unmounted. The configuration of folder is complete, and I've tried resetting the settings.

**Expected behavior:** I expected for the phone folder to load via SFTP.

**Paired Device:** Galaxy S21 5G

**Support Log**

```
GSConnect: 50 (system)
GJS:       17201
Session:   x11
OS:        Manjaro Linux
--------------------------------------------------------------------------------
Jul 20 22:19:01 org.gnome.Shell.Extensions.GSConnect[1622]: [/service/device.js:sendPacket:449]: S21: {
                                                              "id": 1658335741110,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }
Jul 20 22:19:01 touchegg.desktop[1563]: Error connecting to Touchégg daemon: Could not connect: Connection refused
Jul 20 22:19:01 touchegg.desktop[1563]: Reconnecting in 5 seconds...
Jul 20 22:19:01 org.gnome.Shell.Extensions.GSConnect[1622]: [/service/device.js:_readLoop:341]: S21: {
                                                              "id": 1658335740765,
                                                              "type": "kdeconnect.sftp",
                                                              "body": {
                                                                "ip": "192.168.0.103",
                                                                "port": 1741,
                                                                "user": "kdeconnect",
                                                                "password": "f8ZJqhulpFGhjfL7XUhdGi6GMq4D",
                                                                "path": "/",
                                                                "multiPaths": [
                                                                  "/Documents"
                                                                ],
                                                                "pathNames": [
                                                                  "Documents"
                                                                ]
                                                              }
                                                            }
Jul 20 22:19:01 gjs[1622]: JS ERROR: S21: Gio.IOErrorEnum: Connection failed
                           _handleMount/</<@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                           @/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Jul 20 22:19:01 gjs[1622]: JS ERROR: S21: Gio.IOErrorEnum: Unknown error 255
                           Cannot stat /home/arnavp/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Jul 20 22:19:01 gjs[1622]: JS ERROR: S21: Gio.IOErrorEnum: Unknown error 255
                           Cannot stat /home/arnavp/.ssh/known_hosts: No such file or directory
                           _removeHostKey/</<@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:326:39
                           @/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Jul 20 22:19:03 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Connecting to Touchégg daemon
Jul 20 22:19:03 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Error connecting to Touchégg daemon: Could not connect: Connection refused
Jul 20 22:19:03 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Reconnecting to Touchégg daemon in 5 seconds
Jul 20 22:19:04 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Connecting to Touchégg daemon
Jul 20 22:19:04 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Error connecting to Touchégg daemon: Could not connect: Connection refused
Jul 20 22:19:04 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Reconnecting to Touchégg daemon in 5 seconds
Jul 20 22:19:04 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Connecting to Touchégg daemon
Jul 20 22:19:04 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Error connecting to Touchégg daemon: Could not connect: Connection refused
Jul 20 22:19:04 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Reconnecting to Touchégg daemon in 5 seconds
Jul 20 22:19:04 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Connecting to Touchégg daemon
Jul 20 22:19:04 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Error connecting to Touchégg daemon: Could not connect: Connection refused
Jul 20 22:19:04 gnome-shell[1247]: [x11gestures@joseexposito.github.io] Reconnecting to Touchégg daemon in 5 seconds
Jul 20 22:19:06 touchegg.desktop[1563]: Error connecting to Touchégg daemon: Could not connect: Connection refused
Jul 20 22:19:06 touchegg.desktop[1563]: Reconnecting in 5 seconds...
```

**Comment by andyholmes** [comment] 2022-08-02 22:28
Probably another duplicate of #1203

If the solution from that issue does not help, feel free to re-open with your results.

**Closed by andyholmes** 2022-08-02 22:28 UTC
Labels: duplicate
