### ISSUE TITLE
Not finding any devices, not connect with ip either

### ISSUE THREAD

**Issue by survivor303** [GSConnect/gnome-shell-extension-gsconnect#1042] opened 2021-01-08 09:19 UTC
GSConnect: 44 (user)
GJS:       16601
Session:   x11
OS:        Ubuntu Hirsute Hippo (development branch)

**Comment by andyholmes** [comment] 2021-01-09 01:52
Can you confirm that you can ping the device?

**Comment by survivor303** [comment] 2021-01-14 19:21
sorry for late reply, but yes, i can ping it.
also, when restarting gnome, it give me that "port is used by other application" but when i trying to check what application use it, the system dosnt find any.

**Comment by andyholmes** [comment] 2021-01-15 00:39
Sounds like a local networking problem then. If GSConnect can't bind to the default port it won't be able to open or accept connections. If `lsof -i UDP:1716` is not indicating another application using the port, then there is probably some security policy preventing it.

**Comment by ElonSatoshi** [comment] 2021-02-11 22:37
I'm getting this issue on Fedora 33. Do you have any idea what this local networking problem might be?

**Comment by andyholmes** [comment] 2021-12-01 22:59
Closing since this seems to have been caused by KDE Connect being installed at the same time as GSConnect. Feel free to reopen if the problem persists with a current version of GSConnect.

**Closed by andyholmes** 2021-12-01 22:59 UTC
