### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by dot-D69** [GSConnect/gnome-shell-extension-gsconnect#1399] opened 2022-06-23 05:13 UTC
```
GSConnect: 47 (user)
GJS:       17200
Session:   wayland
OS:        Pop!_OS 21.10

_loadBackends@/home/dhruv/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/dhruv/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/dhruv/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/dhruv/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/dhruv/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by prahal** [comment] 2022-06-25 18:31
https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1276 fixes this issue, ie 
```
                if (module.ChannelService === undefined)
                    continue;
```
I tried adding the fixes from the pull request and the issue vanished

**Comment by prahal** [comment] 2022-06-25 18:33
This is also a duplicate of closed issue https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1256

**Comment by andyholmes** [comment] 2022-08-02 22:10
Duplicate of #1256

**Closed by andyholmes** 2022-08-02 22:10 UTC
Labels: duplicate
