### ISSUE TITLE
GNOME 46

### ISSUE THREAD

**Issue by kozross** [GSConnect/gnome-shell-extension-gsconnect#1777] opened 2024-04-01 21:13 UTC
### Describe the bug

Currently, this extension does not work with GNOME 46, and gets disabled on it.

### Steps to reproduce

1. Update GNOME to 46.0
2. Check the Extensions window.
3. Note that GSConnect is disabled.

### Expected behavior

Should work on GNOME 46.

### GSConnect version

56

### Installed from

GNOME Extensions website

### GNOME Shell version

46.0

### Linux distribution/release

Arch

**Comment by andyholmes** [comment] 2024-04-01 22:42
Let's just make this the target issue, until we confirm support is complete and a release is done.

**Comment by daniellandau** [comment] 2024-04-02 04:21
This is the current blocker for a release: https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1775

**Comment by daniellandau** [comment] 2024-04-02 19:46
#1775 is now closed with https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1778, so I think I'll make a release tomorrow.

**Comment by ferdnyc** [comment] 2024-04-05 01:44
@daniellandau 

> #1775 is now closed with https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1778, so I think I'll make a release tomorrow.

As I just mentioned on #1776, since we're still finding (relatively minor, granted) changes for full compatibility, I'd suggest waiting until my WIP PR is merged (waiting on some not-strictly-necessary polyfill code), at which point the CI systems will be testing and packaging GSConnect under GNOME 46. If there are going to be any more surprises, that should shake them out.

**Comment by pesader** [comment] 2024-04-10 02:15
Hey everyone!

I just updated my computer to GNOME 46 so I can help with testing. Do you want me to test some specific feature/use-case, or just use the extension normally and see if something unexpected comes up?

**Comment by UtkarshDeoli** [comment] 2024-04-10 02:53
I too can help testing

**Comment by andyholmes** [comment] 2024-04-10 02:57
You can just do normal testing, or do systematic testing if you feel up to it :+1: 

Generally we should be looking for regressions of fixed issues, or brand new issues. I don't believe we expect any issues to have been indirectly solved by e.g. the port to ESModules.

**Comment by daniellandau** [comment] 2024-04-10 05:10
"Use extension normally" is good. I'll do still some testing myself in a couple if days and hopefully a release on the weekend.

**Comment by pesader** [comment] 2024-04-10 11:11
@UtkarshDeoli you can find the instructions to install the latest version of GSConnect in the Wiki, right [here](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-nightly-build).

**Comment by aminsaedi** [comment] 2024-04-11 16:15
I have been testing it on Gnome 46 (Fedora 40) for past few days and everything seems to work as expected :)

**Comment by InklingGirl** [comment] 2024-04-11 18:15
The latest LTS version of Ubuntu is launching w/ GNOME 46 this month, so I hope the update – if it is working well for testing users – can be pushed to https://extensions.gnome.org/extension/1319 in time for the launch! Thank you.

**Comment by UtkarshDeoli** [comment] 2024-04-11 18:25
@InklingGirl  i can confirm all features works fine in Gnome 46(arch) with the latest nightly build

**Comment by pesader** [comment] 2024-04-15 21:06
My experience with the extension has been smooth as well. From the [features listed in the Wiki](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Features), I most frequently used the following, without any issues so far:

Plugins

- [x] Battery
- [x] Clipboard
- [ ] Contacts
- [ ] Find My Phone
- [x] Mousepad
- [x] MPRIS
- [x] Notification
- [ ] Photo
- [ ] Ping
- [x] Presenter
- [ ] Run Commands
- [ ] SFTP
- [x] Share
- [ ] SMS
- [ ] SMS Input
- [ ] Telephony

Desktop Integration

- [ ] Desktop Contacts
- [ ] Keyboard Shortcuts
- [ ] URI Handlers

Extensions

- [x] Files Extension (Nautilus/Nemo)
- [ ] WebExtension (Chrome & Firefox)

Thanks again to all contributors for this awesome extension 👣📲

**Comment by daniellandau** [comment] 2024-04-17 13:02
New version in released now, so closing this.

**Closed by daniellandau** 2024-04-17 13:02 UTC
Labels: help wanted, needs testing

**Comment by ferdnyc** [comment] 2024-07-20 15:33
Unpinning.
