### ISSUE TITLE
GSConnect Mount Smartphone failed

### ISSUE THREAD

**Issue by 4444vlad4444** [GSConnect/gnome-shell-extension-gsconnect#1421] opened 2022-07-20 05:22 UTC
Hi Team,
I am using Fedora 36 with Gnome 42.
Installed GSConnection extention, Openssl, connected to my smartphone.
All funktions are working, sending files, ringing, media controll and so on.
Mounting smartphone from Fedora generates this output.

GSConnect: 50 (user)
GJS:       17201
Session:   wayland
OS:        Fedora Linux 36 (Workstation Edition)
--------------------------------------------------------------------------------
Jul 20 07:19:02 systemd[1696]: Started dbus-:1.2-org.gnome.TextEditor@6.service.
Jul 20 07:19:06 systemd[1696]: dbus-:1.2-org.gnome.TextEditor@6.service: Consumed 1.025s CPU time.
Jul 20 07:19:08 gnome-shell[1862]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 20 07:19:08 gnome-shell[1862]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 20 07:19:08 gnome-shell[1862]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 20 07:19:08 gnome-shell[1862]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 20 07:19:08 gnome-shell[1862]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 20 07:19:08 gnome-shell[1862]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 20 07:19:08 gnome-shell[1862]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 20 07:19:08 gnome-shell[1862]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Jul 20 07:19:10 gjs[2325]: JS ERROR: Mi 9T Pro: Gio.IOErrorEnum: Verbindung fehlgeschlagen
                           _handleMount/</<@/home/vvv/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                           @/home/vvv/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17

**Comment by andyholmes** [comment] 2022-08-02 22:26
Probably another duplicate of #1203.

If the solution from that issue does not help, feel free to re-open with your results.

**Closed by andyholmes** 2022-08-02 22:26 UTC
Labels: duplicate
