### ISSUE TITLE
Child process exited with code 127

### ISSUE THREAD

**Issue by machievizc** [GSConnect/gnome-shell-extension-gsconnect#1328] opened 2022-04-09 20:54 UTC
```
GSConnect: 47 (user)
GJS:       16804
Session:   x11
OS:        Ubuntu 21.10

Gio.TlsCertificate.new_for_paths@/home/mikael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:349:14
_initCertificate@/home/mikael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:177:48
start@/home/mikael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/mikael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/home/mikael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/mikael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/mikael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/mikael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-08-03 00:01
Duplicate of #1209

**Closed by andyholmes** 2022-08-03 00:01 UTC
Labels: duplicate
