### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by omarly666** [GSConnect/gnome-shell-extension-gsconnect#1346] opened 2022-05-04 15:36 UTC
```
GSConnect: 47 (user)
GJS:       17200
Session:   x11
OS:        Ubuntu 22.04 LTS

_loadBackends@/home/martinlyn/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/martinlyn/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/martinlyn/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/martinlyn/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/martinlyn/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-05-18 21:41
Duplicate of #1256

**Closed by andyholmes** 2022-05-18 21:41 UTC
Labels: duplicate
