### ISSUE TITLE
No JS module 'connectivity_report' found in search path

### ISSUE THREAD

**Issue by heckctor** [GSConnect/gnome-shell-extension-gsconnect#1258] opened 2022-02-27 17:24 UTC
```
GSConnect: 45 (user)
GJS:       16602
Session:   wayland
OS:        Debian GNU/Linux 11 (bullseye)

_loadPlugin@/home/hektor/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:955:17
_loadPlugins@/home/hektor/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:987:28
async*_init@/home/hektor/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:125:18
_loadDevices@/home/hektor/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:265:28
start@/home/hektor/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:453:14
vfunc_startup@/home/hektor/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/hektor/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/hektor/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-02-27 17:38
This plugin was added in v47, so it seems like you probably tried to install a version not supported for your version of GNOME Shell, then later downgraded.

I'd recommend you follow the steps in the Wiki for [resetting all settings](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#how-can-i-reset-the-settings), then re-install a version of GSConnect that supports your version of GNOME Shell.

**Comment by ferdnyc** [comment] 2022-03-01 14:18
As @andyholmes notes, this is almost certainly caused by a manual downgrade, and a clean reinstall should fix it. Closing, but feel free to reopen if that doesn't solve the problem for you, @heckctor .

**Closed by ferdnyc** 2022-03-01 14:18 UTC
