### ISSUE TITLE
Not mounting device in Archlinux 

### ISSUE THREAD

**Issue by duckies0** [GSConnect/gnome-shell-extension-gsconnect#1467] opened 2022-09-21 14:36 UTC
# After click on mounting Device is not mounted
 ## sshfs is also installed 

### os: Arcolinux (based on arch)
[gsconnect.274NS1.txt](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/9617621/gsconnect.274NS1.txt)

**Comment by NA0341** [comment] 2022-10-08 06:53
Same on Manjaro

**Comment by JeffreyFalgout** [comment] 2022-10-23 15:35
I'm running into a similar problem on ubuntu 22.04, but I think my root cause might be different.

@duckies0 your logs seem to be complaining about `Cannot stat /home/$USER/.ssh/known_hosts: No such file or directory`. Does that file exist on your system?

My logs are showing something else:

```
Oct 23 09:31:31 org.gnome.Shell.Extensions.GSConnect[2084]: [/service/device.js:sendPacket:449]: Pixel 5: {
                                                              "id": 1666539091695,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }
Oct 23 09:31:32 org.gnome.Shell.Extensions.GSConnect[2084]: [/service/device.js:_readLoop:341]: Pixel 5: {
                                                              "id": 1666539092151,
                                                              "type": "kdeconnect.sftp",
                                                              "body": {
                                                                "ip": "<redacted external IP>",
                                                                "port": 1739,
                                                                "user": "kdeconnect",
                                                                "password": "<redacted>",
                                                                "path": "/",
                                                                "multiPaths": [
                                                                  "/KDEConnect"
                                                                ],
                                                                "pathNames": [
                                                                  "KDEConnect"
                                                                ]
                                                              }
                                                            }
Oct 23 09:31:32 gjs[2084]: JS ERROR: Pixel 5: Gio.IOErrorEnum: Connection failed
                           _handleMount/</<@/home/jeffrey/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                           @/home/jeffrey/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by JeffreyFalgout** [comment] 2022-10-23 16:14
I think my problem might be in that `<redacted external IP>`.

My home's external IP is `107.XXX.XXX.XXX`. My phone's IP on the network is `192.168.3.XXX`. My computer's IP on the network is `192.168.3.XXX`. The IP being reported in that message is `100.XXX.XXX.XXX`

**Comment by JeffreyFalgout** [comment] 2022-10-23 16:38
Aha, looks like my problem is https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1203. Sorry for the noise

**Comment by andyholmes** [comment] 2022-11-03 21:39
Duplicate of #1203

**Closed by andyholmes** 2022-11-03 21:39 UTC
Labels: duplicate
