### ISSUE TITLE
Can't Mount

### ISSUE THREAD

**Issue by bennypowers** [GSConnect/gnome-shell-extension-gsconnect#1558] opened 2023-01-30 08:53 UTC
### Describe the bug

Clicking "Mount" in GSConnect GNOME panel menu has no effect.

### Steps to reproduce

Open Settings Panel
Open GSConnect disclosure widget
click "Mount"

### Expected behavior

FS mounts

### GSConnect version

54

### Installed from

GNOME Extensions website

### GNOME Shell version

43

### Linux distribution/release

Fedora 37

### Paired device(s)

OnePlus Nord CE2

### KDE Connect app version

1.22.1

### Support log

```plain text
Jan 30 10:50:15 gjs[85488]: JS ERROR: IV2201: Gio.IOErrorEnum: Connection failed
                            _handleMount/</<@/home/bennyp/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:253:38
                            @/home/bennyp/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by realKarthikNair** [comment] 2023-02-11 13:58
https://invent.kde.org/network/kdeconnect-kde/-/commit/204207f2e66e87e7696ff1c98d70ce41b3e2d396

**Comment by brianrho** [comment] 2023-03-11 05:31
Yes, this is likely the same as #1203.

With mounting effectively broken, there should really be a warning in the app to reduce frustration, let alone all these duplicate issues being raised.

GSConnect is capable of detecting when mounting fails, even if it doesn't know the exact reason.

```
            await new Promise((resolve, reject) => {
                file.mount_enclosing_volume(0, op, null, (file, res) => {
                    try {
                        resolve(file.mount_enclosing_volume_finish(res));
                    } catch (e) {
```

So, instead of failing silently:

* It should notify the user that mounting has failed, making sure to include the exact GIOError returned, so people can search online for clues, if they want (without needing to first trawl through syslog).
* Considering the great likelihood that "Connection Failed" (in this context) is caused by the SSH-RSA issue, GSConnect can simultaneously suggest that users check out #1203 for a workaround. 

Something along lines of `The mount failure *may* have been caused by #1203. Please check that page for a workaround.`

**Comment by andyholmes** [comment] 2024-03-02 00:33
Closing as a duplicate of #1203.

**Closed by andyholmes** 2024-03-02 00:33 UTC
Labels: duplicate
