### ISSUE TITLE
not compatible with gnome 45

### ISSUE THREAD

**Issue by elmhadji** [GSConnect/gnome-shell-extension-gsconnect#1697] opened 2023-10-26 15:01 UTC
### Describe the bug

it was working fin just after I upgrade my OS into gnome 45 it stopped working. 

### Steps to reproduce

1. upgrade your gnome to gnome 45 (or use directly gnome 45)

### Expected behavior

not working

### GSConnect version

1.29.0

### Installed from

GNOME Extensions website

### GNOME Shell version

45

### Linux distribution/release

arch

### Paired device(s)

poco x3

### KDE Connect app version

1.29.0

### Notes

please make it compatible with gnome 45

**Comment by sarowarhosen03** [comment] 2023-10-27 13:39
im aslo waiting for the next release . gsconnect dev team should harry up for the next release

**Comment by elmhadji** [comment] 2023-10-27 13:42
> im aslo waiting for the next release . gsconnect dev team should harry up for the next release

we all do the problem that when i get used to it broke Lamo. (when upgrade to gnome45)

**Comment by azmeuk** [comment] 2023-10-27 14:17
Duplicate of #1665

**Comment by sarowarhosen03** [comment] 2023-10-27 14:19
> Duplicate of #1665

So what? It's still not resolve. Duplicate is important to remember you that Ubuntu with gnome,  45 has been released

**Comment by andyholmes** [comment] 2023-10-27 15:10
Please don't intentionally open duplicate issues.

**Closed by andyholmes** 2023-10-27 15:10 UTC
Labels: duplicate

**Comment by elmhadji** [comment] 2023-10-28 10:29
@andyholmes can you please tell me how close this issus ?

**Comment by sarowarhosen03** [comment] 2023-10-28 10:33
> @andyholmes can you please tell me how close this issus ?

Already closed by admin
