### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by cr1ogen** [GSConnect/gnome-shell-extension-gsconnect#1408] opened 2022-07-04 23:43 UTC
```
GSConnect: 51 (user)
GJS:       17200
Session:   wayland
OS:        Debian GNU/Linux bookworm/sid

_loadBackends@/home/cr1ogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/cr1ogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/cr1ogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/cr1ogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/cr1ogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by prahal** [comment] 2022-07-23 20:26
This is fixed by https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1276 . Though I would not close this bug report per extensions.gnome.org does not seem to ship a fixed version.

**Comment by prahal** [comment] 2022-07-23 20:32
A hackish way to locally fix gsconnect (already installed):
```
cd ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
wget https://github.com/GSConnect/gnome-shell-extension-gsconnect/commit/8aa1c0559cca7b7744e684ce79d20872d490d115.diff
patch -p2 < ./8aa1c0559cca7b7744e684ce79d20872d490d115.diff
rm 8aa1c0559cca7b7744e684ce79d20872d490d115.diff
```

**Comment by andyholmes** [comment] 2022-08-02 22:07
Closing as a duplicate of #1256

The original reporter is using v51 with gjs-1.72 (GNOME 42), when they should be using v50.

**Closed by andyholmes** 2022-08-02 22:07 UTC
Labels: duplicate
