### ISSUE TITLE
GSConnect connecting but not mounting

### ISSUE THREAD

**Issue by mspatil32** [GSConnect/gnome-shell-extension-gsconnect#1536] opened 2022-12-05 02:39 UTC
Hi,

I upgraded to Fedora 37 Gnome 43.
Although GSConnect connects to my phone, it is not mounting the phone directories.
Any solutions please.

Please let me know if you need any other details.

Thanks,
Mallikarjun

**Comment by frikisama** [comment] 2022-12-19 08:00
I am experiencing the same behavior. GS Connect works (after installing openssl, of course), but mounting the phone doesn't work. This is consistent with other devices here at home: same behavior. Gnome Files is a system application installed as rpm, not via flatpak.

This is the only thing appearing in the support log:

`Dec 19 08:57:57 org.gnome.Shell.Extensions.GSConnect[1756]: [/service/device.js:sendPacket:449]: Device Name: {
                                                              "id": numbers,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }`

If you need some more information or logs please let me know. Thank you for this amazing piece of software!

**Comment by didierga** [comment] 2022-12-21 06:29
I confirm that I'm experiencing the same issue on Fedora 37 Workstation - Gnome 43

**Comment by andyholmes** [comment] 2022-12-22 04:18
This is almost certainly a duplicate of #1203.

To make things easier on everyone, please do fill out the issue template when reporting bugs. It really makes it easier to determine what the problem is and if the report is a duplicate. :slightly_smiling_face:

**Comment by qwertychouskie** [comment] 2022-12-26 21:14
https://invent.kde.org/network/kdeconnect-kde/-/commit/204207f2e66e87e7696ff1c98d70ce41b3e2d396

Sadly it seems there's no plans to update the app, since it would break support for older versions of Android.  The workaround needs to be client-side, so in this case in GSConnect itself.

**Comment by andyholmes** [comment] 2022-12-26 22:04
As I stated [here](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1203#issuecomment-1218582274) if someone wants to contribute a manual setting that enables RSA, I would accept it, but silently re-enabling insecure ciphers is not something I would support.

**Closed** 2022-12-26 22:08 UTC
Labels: duplicate
