### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by IGOR3K99** [GSConnect/gnome-shell-extension-gsconnect#1260] opened 2022-03-02 23:48 UTC
```
GSConnect: 48 (system)
GJS:       17101
Session:   x11
OS:        Ubuntu Jammy Jellyfish (development branch)

_loadBackends@/home/igor3k99/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/igor3k99/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/igor3k99/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/igor3k99/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/igor3k99/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by ferdnyc** [comment] 2022-03-03 05:05
Duplicate of #1256.

**Closed by ferdnyc** 2022-03-03 05:05 UTC
Labels: duplicate
