### ISSUE TITLE
TLS support is not available

### ISSUE THREAD

**Issue by hasntbeentaken** [GSConnect/gnome-shell-extension-gsconnect#1057] opened 2021-02-25 11:54 UTC
```
GSConnect: 43 (user)
GJS:       16403
Session:   x11
OS:        Ubuntu 20.04.2 LTS

Gio.TlsCertificate.new_for_paths@/home/nitrogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:352:31
_initCertificate@/home/nitrogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:177:48
start@/home/nitrogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/nitrogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/home/nitrogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/nitrogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/nitrogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:666:18
@/home/nitrogen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:729:17
```

**Comment by andyholmes** [comment] 2021-12-28 03:35
Seems like this is a recurring problem for Ubuntu users. You may want to try reinstalling `glib-networking` and `ca-certificates` and see if that helps.

**Comment by andyholmes** [comment] 2022-08-03 01:28
Duplicate of #1209

**Closed by andyholmes** 2022-08-03 01:28 UTC
Labels: duplicate
