### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by adipginting** [GSConnect/gnome-shell-extension-gsconnect#1262] opened 2022-03-04 03:54 UTC
```
GSConnect: 47 (user)
GJS:       17101
Session:   x11
OS:        Ubuntu Jammy Jellyfish (development branch)

_loadBackends@/home/apg/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/apg/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/apg/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/apg/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/apg/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-03-04 21:39
Duplicate of #1256

**Closed by andyholmes** 2022-03-04 21:39 UTC
Labels: duplicate
