### ISSUE TITLE
How to activate Do Not Disturb mode on Android when it's enabled in Gnome?

### ISSUE THREAD

**Issue by sojusnik** [GSConnect/gnome-shell-extension-gsconnect#1394] opened 2022-06-15 10:39 UTC
Is there currently a way to easily activate [Do Not Disturb](https://support.google.com/android/answer/9069335?hl=en) mode on Android when it's enabled in Gnome? Maybe through the [commands plugin](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Features#run-commands)?

In Gnome, you can turn on the Do Not Disturb mode by clicking on the corresponding button in the notifications area or use `settings set org.gnome.desktop.notifications show-banners false` (replace with `true` to deactivate).

**Comment by andyholmes** [comment] 2022-06-16 02:57
Unfortunately this isn't possible without changes to the KDE Connect protocol, which you would have to request from the upstream project. Sorry about that!

**Comment by andyholmes** [comment] 2022-08-03 01:26
Effectively a duplicate of #1112

**Closed by andyholmes** 2022-08-03 01:26 UTC
Labels: upstream, protocol
