### ISSUE TITLE
/(?:cn|CN) ?= ?([^,\n]*)/.exec(...) is null

### ISSUE THREAD

**Issue by abuhuraira0099** [GSConnect/gnome-shell-extension-gsconnect#1118] opened 2021-05-23 13:29 UTC
```
GSConnect: 46 (user)
GJS:       16801
Session:   wayland
OS:        openSUSE Tumbleweed

get@/home/mhmr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:393:64
_initCertificate@/home/mhmr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:182:13
start@/home/mhmr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/mhmr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/home/mhmr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/mhmr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/mhmr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/mhmr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by robwilkes** [comment] 2021-05-28 00:00
Same, been getting this for several days now, if not an entire week, tried uninstalling and reinstalling extension.

/(?:cn|CN) ?= ?([^,\n]*)/.exec(...) is null

get@/home/rob/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:393:64
_initCertificate@/home/rob/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:182:13
start@/home/rob/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/rob/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:251:25
start@/home/rob/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/rob/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/rob/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/rob/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17

**Comment by andyholmes** [comment] 2021-06-08 03:42
Which version of OpenSSL are you running? This seems like you are probably using `openssl >= 3.0` which may have different cli output.

**Comment by andyholmes** [comment] 2022-08-03 00:47
Closing as a duplicate of #1209

**Closed by andyholmes** 2022-08-03 00:47 UTC
Labels: duplicate
