### ISSUE TITLE
gsconnect / gjs / daemon.js listens only on IPv6 address ubuntu

### ISSUE THREAD

**Issue by spupuz** [GSConnect/gnome-shell-extension-gsconnect#1058] opened 2021-03-02 13:56 UTC
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

gsconnect on ubuntu listening only on IPV6

**Describe the bug**
spupuz@spupuz-VirtualBox:~$ lsof -i UDP:1716
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
gjs     34612 spupuz   16u  IPv6  60056      0t0  UDP *:1716 

**Steps To Reproduce:**

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** 44
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** [e.g. 3.36, ...]
 - **Distro/Release:** Ubuntu 21.04

**GSConnect environment (if applicable):**

**Additional Notes:**

**Comment by spupuz** [comment] 2021-03-02 16:39
this is the only service listening only on ipv6

pupuz@spupuz-VirtualBox:~$ netstat -an | grep LISTEN
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:7070            0.0.0.0:*               LISTEN     
tcp6       0      0 :::139                  :::*                    LISTEN     
tcp6       0      0 :::1716                 :::*                    LISTEN     
tcp6       0      0 :::445                  :::*                    LISTEN

**Comment by daniellandau** [comment] 2021-03-02 20:41
Is the connection to the phone not working for you?

**Comment by spupuz** [comment] 2021-03-02 20:56
Yes not working

Il Mar 2 Mar 2021, 21:41 Daniel Landau <notifications@github.com> ha
scritto:

**Comment by spupuz** [comment] 2021-03-03 09:18
Let me know if you need more info that can help in solving my problem

**Comment by daniellandau** [comment] 2021-03-03 11:43
On my computer the ports look similar to yours

```
% sudo netstat -nepal | grep 'LISTEN\b'
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          14021      683/sshd: /usr/bin/ 
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      0          22394      682/cupsd           
tcp6       0      0 :::22                   :::*                    LISTEN      0          14023      683/sshd: /usr/bin/ 
tcp6       0      0 ::1:631                 :::*                    LISTEN      0          22393      682/cupsd           
tcp6       0      0 :::1739                 :::*                    LISTEN      1000       3520688    1616/gjs            
tcp6       0      0 :::1740                 :::*                    LISTEN      1000       3520690    1616/gjs            
tcp6       0      0 :::1716                 :::*                    LISTEN      1000       25148      1616/gjs   
```

And the connection is working fine. Has GSConnect ever worked for you? Have you done something specific in your computers IPv6 configuration? The connection is local so it shouldn't matter whether or not you have IPv6 working out of your LAN or not.

**Comment by spupuz** [comment] 2021-03-03 13:20
All connection working fine except gsconnect, ipv6 disabled in this Linux installation, gsconnect had work before in another Linux I had

**Comment by ferdnyc** [comment] 2021-03-03 13:23
Yeah, really you "listen on" some port, for a certain protocol -- not an address space. GSConnect is listening for TCP connections on those ports, so any incoming connections will be made whether they're from IPv4 or IPv6 addresses. (IPv6 has translation mechanisms for interfacing with hosts that use IPv4 addresses.)

The most likely culprit is your firewall. Have you opened the necessary ports for incoming connections?

**Comment by ferdnyc** [comment] 2021-03-03 13:26
Also, you can test connectivity by telnetting to the port.

If any ONLY IF `telnet -6 localhost 1716` connects, but `telnet -4 localhost 1716` fails to connect, should you go down the road of thinking that the issue is how GSConnect is listening for connections.

**Comment by ferdnyc** [comment] 2021-03-03 13:50
> ipv6 disabled in this Linux installation

That's not correct. You know how I know?

> tcp6 0 0 :::139 :::* LISTEN
> tcp6 0 0 :::1716 :::* LISTEN
> tcp6 0 0 :::445 :::* LISTEN

If the IPv6 stack were truly disabled (which is almost impossible in modern Linux), there'd be no way for those port assignments to exist. You may not _use_ IPv6 between hosts, but the kernel's IPv6 is enabled and functioning, and GSConnect listening on `:::1716` for TCP connections from `:::*` will accept sessions from/to IPv4 addresses just fine.

**Comment by spupuz** [comment] 2021-03-03 13:52
spupuz@spupuz-VirtualBox:~$ telnet -6 localhost 1716
Trying ::1...
telnet: Unable to connect to remote host: Cannot assign requested address
spupuz@spupuz-VirtualBox:~$ telnet -4 localhost 1716
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^C^C^C^C^C^C^C^C^X^X^X^C^C^C^X^X^X


ipv4 effectively is on... but can't pair with my phone and can't find any device

**Comment by spupuz** [comment] 2021-03-03 14:26
is there any other log i can check?

**Comment by spupuz** [comment] 2021-03-03 14:55
`
GSConnect: 44 (user)
GJS:       16702
Session:   x11
OS:        Ubuntu Hirsute Hippo (development branch)
--------------------------------------------------------------------------------
-- Journal begins at Sat 2021-02-27 15:22:13 CET, ends at Wed 2021-03-03 15:54:52 CET. --
mar 03 15:54:01 dbus-daemon[11733]: [session uid=1000 pid=11733] Activating via systemd: service name='org.freedesktop.Tracker1' unit='tracker-store.service' requested by ':1.2' (uid=1000 pid=11729 comm="/usr/libexec/tracker-miner-fs " label="unconfined")
mar 03 15:54:01 systemd[11719]: Starting Tracker metadata database store and lookup manager...
mar 03 15:54:01 dbus-daemon[11733]: [session uid=1000 pid=11733] Successfully activated service 'org.freedesktop.Tracker1'
mar 03 15:54:01 systemd[11719]: Started Tracker metadata database store and lookup manager.
mar 03 15:54:01 dbus-daemon[11733]: [session uid=1000 pid=11733] Activating via systemd: service name='org.freedesktop.Tracker1.Miner.Extract' unit='tracker-extract.service' requested by ':1.2' (uid=1000 pid=11729 comm="/usr/libexec/tracker-miner-fs " label="unconfined")
mar 03 15:54:01 systemd[11719]: Starting Tracker metadata extractor...
mar 03 15:54:01 tracker-extract[28407]: Set scheduler policy to SCHED_IDLE
mar 03 15:54:01 tracker-extract[28407]: Setting priority nice level to 19
mar 03 15:54:01 dbus-daemon[11733]: [session uid=1000 pid=11733] Successfully activated service 'org.freedesktop.Tracker1.Miner.Extract'
mar 03 15:54:01 systemd[11719]: Started Tracker metadata extractor.
mar 03 15:54:11 systemd[11719]: tracker-extract.service: Succeeded.
mar 03 15:54:31 tracker-store[28368]: OK
mar 03 15:54:31 systemd[11719]: tracker-store.service: Succeeded.
mar 03 15:54:45 gjs[12227]: JS ERROR: Gio.TlsError: Error performing TLS handshake: No supported cipher suites have been found.
                            _handshake/</<@/home/spupuz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:595:44
                            @/home/spupuz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
mar 03 15:54:47 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:47 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: setup_framebuffers: assertion 'width > 0' failed
mar 03 15:54:52 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.
mar 03 15:54:52 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.
mar 03 15:54:52 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.
mar 03 15:54:52 gnome-shell[11996]: Can't update stage views actor StWidget is on because it needs an allocation.`

**Comment by andyholmes** [comment] 2021-03-04 04:51
> Gio.TlsError: Error performing TLS handshake: No supported cipher suites have been found.

That's your problem :) GSConnect is actually more permissive than KDE Connect at this point, since it still allows TLSv1.0:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/063d387cd6800cac64c959bb1a48a32182abe4f8/src/service/daemon.js#L5-L7

Maybe Ubuntu has dropped support for a version of TLS that the Android device requires. You can try fiddling with that env variable to see if it helps.

**Comment by spupuz** [comment] 2021-03-04 07:15
well can you be a little bit clear and guide me i haven't understood how do i change to disallow TLSv1.0 on gscconnect.

**Comment by andyholmes** [comment] 2021-03-04 22:01
If all you want to do is disallow TLSv1.0 you can just delete that whole line and restart GSConnect. I have no idea if that's the problem though.

I'm not really an expert in SSL/TLS, so I can't just give you a line to copy/paste that will solve your problem. You might have to ask someone experienced with Ubuntu if something has changed, especially since Ubuntu 21.04 has not been released yet.

> Gio.TlsError: Error performing TLS handshake: No supported cipher suites have been found.

This error could ultimately be coming from your android device, but you haven't mentioned anything about that. If it's using an older version of Android like 4.4, it may require key exchange algorithms or something else that Ubuntu now considers too insecure to support.

**Comment by spupuz** [comment] 2021-03-04 22:07
i moved back to ubuntu 20.04 just to be in line with all the stuff and it
works

>

**Comment by andyholmes** [comment] 2021-12-01 23:08
Closing since the issue seems to have been resolved.

**Closed by andyholmes** 2021-12-01 23:08 UTC
