### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by Pr0fess** [GSConnect/gnome-shell-extension-gsconnect#1330] opened 2022-04-16 04:09 UTC
```
GSConnect: 47 (user)
GJS:       17200
Session:   wayland
OS:        Ubuntu 21.10

_loadBackends@/home/kirkyagami/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/kirkyagami/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/kirkyagami/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/kirkyagami/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/kirkyagami/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by ferdnyc** [comment] 2022-04-25 04:23
Duplicate of #1256.

**Closed by ferdnyc** 2022-04-25 04:23 UTC
Labels: duplicate
