### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by alex-eri** [GSConnect/gnome-shell-extension-gsconnect#1103] opened 2021-04-21 11:23 UTC
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

Gnome-shell process eats all RAM while extension enabled after wakeup from sleep. 

**Steps To Reproduce:**

**Expected behavior**

**Screenshots**

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** 45
   - **Installed from:** https://extensions.gnome.org/extension/1319/gsconnect/
 - **GNOME/Shell version:** GNOME Shell 3.38.4
 - **Distro/Release:** Debian 11

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Nova 2
 - **KDE Connect app version:** 1.15.7
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

**Comment by darkdragon-001** [comment] 2021-04-21 11:29
Duplicate of #1028

**Closed** 2021-04-21 17:00 UTC
