### ISSUE TITLE
No SMS history for Signal, Samsung Messages

### ISSUE THREAD

**Issue by stratus-ss** [GSConnect/gnome-shell-extension-gsconnect#320] opened 2018-11-09 20:48 UTC
I have recently installed GS Connect on a fully up to date Arch Linux system.
The Phone is an up to date Honor 6x (or as up to date as the manufacturer allows)

I can send SMS from the desktop but the history is lost. On the phone I only have one side of the conversation (the received SMS). In the application, I can see my contacts but if I send an sms from the desktop and then go to the main contact list in the messaging window the history is lost.

On the phone I use signal as my SMS app. Is this an expected limitation?

**Comment by andyholmes** [comment] 2018-11-10 00:36
I have heard of similar problems, even with KDE Connect, although I don't know if it's because of the SMS app or not. Only the most recent version of the Android app (v1.10) has support for SMS history, but that is read from Android's [SMS database and API](https://developer.android.com/reference/android/provider/Telephony.Sms.Conversations).

Whether Signal uses that database, or it's own I don't know. I know there is a newer and older API for this and Signal may not support the newer API, possibly so it can support older phones. If you wanted to test, you can try using the stock app and send a few test messages.

This would be an upstream bug in the Android app (especially if the message is being "sent" properly), so the best thing to do is to open a bug in [KDE Connect's bugzilla](https://bugs.kde.org/buglist.cgi?quicksearch=kdeconnect&list_id=1505828), including a link to _this_ bug, and then add a link here to _that one_ so both projects can track it. You might find that it's a problem with Signal and you could see if they have a bug tracker too, and file a bug there :)

It might be a bit of work and waiting, but that's the best way to get things moving.

**Comment by andyholmes** [comment] 2018-11-14 13:29
Signal: [#5729 Signal doesn't store incoming SMS messages to Android's message store](https://github.com/signalapp/Signal-Android/issues/5729) [WONTFIX]

**Comment by pwd-github** [comment] 2018-11-14 13:35
It would seem the only solution would be to apply to Signal for accept to their encrypted message storage.

**Comment by andyholmes** [comment] 2018-11-22 04:12
Firstly, there are four relevant "packets" involved here:

* **Notifications** (*notification* plugin)
* **SMS send** & **SMS event** (*telephony* plugin)
* **SMS messages** (*sms* plugin)

*Long* before upstream KDE Connect had two-way SMS conversations or history of any kind, GSConnect used to fake it. The way this was done was by (1) collecting **SMS send** (outgoing) and (2) using flaky tests to match **SMS event** and **Notification** packets (incoming) to each other, because they were essentially duplicates.

When these could be matched to each other and collected, it was then attempted to match the name and phone number (if we got them) to an open SMS window that first sent the **SMS send** packet. When the window closed, it was all gone and if it wasn't open when Android received the message (ie. at that exact time) all you got was the desktop notification. This was a terrible hack that frequently didn't work, especially for anyone who wasn't using North American phone numbers.

The *sms* plugin was first released for Android with version v1.10 and provides **SMS messages** packet which contain history of both incoming and outgoing messages. These packets provide confirmation of sent messages with information about the sender, receiver, time, direction, full history and everything else you need to make a proper messaging app. We can query this at any time.

SMS apps like Google Messages, AOSP Messages, Textra and others, use the standard documented message database. Others like Samsung (proprietary) and Signal (encrypted) do not, however there is no way for us to tell what SMS app is being used and KDE Connect Android will still report that the phone supports **SMS messages**, even though we will never receive them.

The "legacy" **SMS send** and **SMS event** packets are still sent (for now until they are removed), but there is no way for us to know that we should fall back to them, and doing so will result in every message being duplicated for well-behaved SMS apps. The consequence is that GSConnect's SMS window can send messages, but you will receive no confirmation that they have been sent and incoming messages will never be displayed there.

You will receive **Notification** packets which may have an entry you can use to reply with, depending on the app, but you must have the *notification* plugin enabled on **both** devices. Additionally, neither KDE Connect nor GSConnect has ever supported MMS messages and it's unlikely these will be supported anytime soon. I'm not sure if they are repliable or if they correctly send desktop notifications.

**Comment by archmunky** [comment] 2018-11-29 21:38
If I'm readying this correctly, I should be seeing sms history if I'm using Google Messages?  I do have a Samsung S8 phone but Google is set as my SMS default and I'm still not seeing chat history in GSconnect.

**Comment by andyholmes** [comment] 2018-11-30 01:17
It's still a bit unclear what the extent of the problem is with Samsung phones. There are reports this also affects Contacts as well.

Can you check whether or not your messages are in `~/.cache/gsconnect/<device-id>/sms.json`? If there are no messages in there, it's likely a problem on the Android side. That might not mean it's a problem with the app though, it may just be modifications made by Samsung apply to all SMS apps.

You can also double check by [enabling debug logging](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Debugging) and see if Android is even sending you a list of `sms.messages` packets.

**Comment by coxackie** [comment] 2018-12-01 10:36
On Motorola G6 with Google Messages, the same problem appears - no sms history, no contacts. I use GSConnect v17. Arch Linux, Gnome 3.30.2.

**Comment by gabor-me** [comment] 2018-12-01 13:12
I use Huawei P10 Lite.  Same problem.  No SMS history, no sync of contacts either.

**Comment by archmunky** [comment] 2018-12-01 16:48
I don't have any sms.json file in .cache/gsconnect or any subfolder.  Also running v17 in Linux Mint 19, Gnome 3.28.2

**Comment by andyholmes** [comment] 2018-12-01 21:39
* Are there any errors in your logs?
* If you [enabe debug logging](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Debugging) is there any output containing `sms.messages` or further error messages?
* Can you confirm you are using KDE Connect Android v1.10+?
* Can you confirm you have given the Android app permissions to you SMS & Contacts?

![screenshot_20181114-043447](https://user-images.githubusercontent.com/1265208/49333129-671d9600-f56e-11e8-86d3-ba2940bde09c.png)

**Comment by coxackie** [comment] 2018-12-02 11:03
I can confirm I am using KDE Connect Android v1.10+ and have given the Android app permissions to you SMS & Contacts. Enabling debug logging, I see nothing specific on sms.messages in the terminal output:


g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_variant_new_string: assertion 'string != NULL' failed
AT-SPI: Error in GetItems, sender=(null), error=Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
WARNING: motorola: sshfs: Warning: Permanently added '[192.168.1.4]:1743' (RSA) to the list of known hosts.
WARNING: motorola: sshfs: Password authentication
Failed to fetch network locations: Timeout was reached
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed
g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by archmunky** [comment] 2018-12-02 18:39
- KDE Connect is version 1.10.1 and has all permissions on phone: contacts, phone, sms, storage
- SMS client is Google Messages 
- Phone is AT&T Samsung S8

One thing I did find: I didn't have sshfs installed; fixed.  

I tested everything from scratch by removing the extension and cache, clearing data from KDE Connect on phone then giving it all permissions again.  I then installed gsconnect and immediately started debugging to capture a full log including pairing, sending text, receiving, etc.  Will summarize logs below sanitizing ids/user names/contact info/phone numbers/etc.

GJS - reported capabilities:
```
"incomingCapabilities": [
   "kdeconnect.sms.request_conversations",
   "kdeconnect.telephony.request_mute",
   "kdeconnect.telephony.request",
   "kdeconnect.mpris",
   "kdeconnect.notification",
   "kdeconnect.sms.request_conversation",
   "kdeconnect.findmyphone.request",
   "kdeconnect.ping",
   "kdeconnect.systemvolume",
   "kdeconnect.notification.reply",
   "kdeconnect.share.request",
   "kdeconnect.sftp.request",
   "kdeconnect.notification.request",
   "kdeconnect.mousepad.request",
   "kdeconnect.contacts.request_vcards_by_uid",
   "kdeconnect.sms.request",
   "kdeconnect.runcommand",
   "kdeconnect.battery.request",
   "kdeconnect.clipboard",
   "kdeconnect.contacts.request_all_uids_timestamps"
],
"outgoingCapabilities": [
   "kdeconnect.sms.messages",
   "kdeconnect.telephony",
   "kdeconnect.notification",
   "kdeconnect.contacts.response_uids_timestamps",
   "kdeconnect.findmyphone.request",
   "kdeconnect.ping",
   "kdeconnect.mousepad.keyboardstate",
   "kdeconnect.share.request",
   "kdeconnect.contacts.response_vcards",
   "kdeconnect.notification.request",
   "kdeconnect.mousepad.echo",
   "kdeconnect.mousepad.request",
   "kdeconnect.sftp",
   "kdeconnect.runcommand.request",
   "kdeconnect.mpris.request",
   "kdeconnect.systemvolume.request",
   "kdeconnect.battery",
   "kdeconnect.clipboard"
],
```

GJS - Requests for contacts/sms data
```
DEBUG: [core.js:send:450]: Samsung SM-G950U: {
  "id": ###,
  "type": "kdeconnect.contacts.request_all_uids_timestamps",
  "body": {}
}
DEBUG: [core.js:send:450]: Samsung SM-G950U: {
  "id": ###,
  "type": "kdeconnect.sms.request_conversations",
  "body": {}
}
DEBUG: [core.js:receive/<:404]: Samsung SM-G950U: {
  "id": ###,
  "type": "kdeconnect.contacts.response_uids_timestamps",
  "body": {
    "uids": [
        (contacts list)
    ],
    (contacts data)
  }
}
DEBUG: [core.js:send:450]: Samsung SM-G950U: {
  "id": ###,
  "type": "kdeconnect.contacts.request_vcards_by_uid",
  "body": {
    "uids": [
        (contacts list)
    ]
  }
}
DEBUG: [core.js:receive/<:404]: Samsung SM-G950U: {
  "id": ###,
  "type": "kdeconnect.contacts.response_vcards",
  "body": {
    (vcards list)
    "uids": [
      (contacts list)
    ]
  }
}
JS WARNING: [/home/###/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/contacts.js 201]: reference to undefined property "type"
```
It looks like the phone is responding to the _kdeconnect.contacts.request_all_uids_timestamps_ requests but I don't see any responses to the _kdeconnect.sms.request_conversations_ requests.  There is a _kdeconnect.telephony_ response when receiving a text later though.

GJS - Sent a text message using gsconnect chat form and received response via notification; does not appear in chat area
```
DEBUG: [core.js:send:450]: Samsung SM-G950U: {
  "id": ###,
  "type": "kdeconnect.sms.request",
  "body": {
    "sendSms": true,
    "phoneNumber": "###",
    "messageBody": "Sending, test from gsconnect"
  }
}
DEBUG: [core.js:receive/<:404]: Samsung SM-G950U: {
  "id": ###,
  "type": "kdeconnect.notification",
  "body": {
    "payloadHash": "###",
    "requestReplyId": "###",
    "id": "0|com.google.android.apps.messaging|0|com.google.android.apps.messaging:sms:192|10445",
    "appName": "Messages",
    "isClearable": true,
    "ticker": "Recipient: Received, responding",
    "title": "Recipient",
    "text": "Received, responding",
    "time": "1543769479285"
  },
  "payloadSize": 2698,
  "payloadTransferInfo": {
    "port": 1739
  }
}
DEBUG: [core.js:receive/<:404]: Samsung SM-G950U: {
  "id": ###,
  "type": "kdeconnect.telephony",
  "body": {
    "event": "sms",
    "messageBody": "Received, responding",
    "contactName": "Recipient",
    "phoneThumbnail": "",
    "phoneNumber": "###"
  }
}
```

Looking in the Gnome-Shell logs, I see a few errors but not sure if they are related to gsconnect:
```
Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
JS WARNING: [resource:///org/gnome/shell/ui/keyboard.js 546]: reference to undefined property "_rect"
JS ERROR: Exception in callback for signal: position-changed: TypeError: this._rect is undefined
getCurrentRect@resource:///org/gnome/shell/ui/keyboard.js:546:22
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_onFocusPositionChanged@resource:///org/gnome/shell/ui/keyboard.js:611:20
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_emit@resource:///org/gnome/gjs/modules/signals.js:128:27
_setCurrentWindow/this._currentWindowPositionId<@resource:///org/gnome/shell/ui/keyboard.js:528:21

DEBUG: [extension.js:_onInterfaceAdded:321]: GSConnect: Adding Samsung SM-G950U
DEBUG: [notification.js:_closeGSConnectNotification/<:110]: Closing pair-request
Object .GSConnectShellIconButton (0x555fac1429b0), has been already finalized. Impossible to get any property from it.
== Stack trace for context 0x555fa956f340 ==
#0 0x555fa9a2b710 i   /home/###/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/gmenu.js:510 (0x7fef03addde0 @ 124)
#1 0x555fa9a2b650 i   self-hosted:922 (0x7fef3c0f12b8 @ 469)
Object Meta.Background (0x555fabd4bba0), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
```

Journalctl shows a single warning for contacts:
```
Dec 02 11:49:33 mint01 gjs[3032]: JS WARNING: [/home/###/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/contacts.js 201]: reference to undefined property "type"
```

**Comment by cascadingstyletrees** [comment] 2018-12-18 14:50
FYI In case anybody was wondering, I updated the KDE Connector to the debug version (12-17-2018) as suggested in the KDE bug report, but I still cannot see the history of text messages (Samsung S8) using the latest extension.

**Comment by andyholmes** [comment] 2018-12-26 22:48
For users with devices that still don't support SMS history, there is an experimental legacy-mode available in v19 that must be enabled manually:
  
  ```
  # List device id's
  dconf read /org/gnome/shell/extensions/gsconnect/devices

  # Enable legacy mode
  dconf write /org/gnome/shell/extensions/gsconnect/device/<device-id>/plugin/sms/legacy true
  ```

This will force the legacy packets to send desktop notifications and comes with a very basic dialog for sending SMS messages.

**Comment by didrocks** [comment] 2019-01-09 14:01
Hey! Having the same issue after udpating to today's version (last commit c182fdd84a411660c4b27432d2659473d4a83dbd). Switching to legacy mode, I can see the old "pick a contact" window. Then, picking one, composing the sms, I can't send it (clicking on Send or Ctrl + Enter doesn't do anything).

**Comment by ferdnyc** [comment] 2019-01-09 18:58
> Then, picking one, composing the sms, I can't send it (clicking on Send or Ctrl + Enter doesn't do anything).

I'm actually seeing that same issue myself, on Fedora 29 with legacy-SMS enabled in `v19`. (Er... maybe `v19` plus a couple of my local changes, come to think of it). Journal message logged when the "Send" button is pressed:
```
Jan 09 13:54:14 gjs[15664]: JS ERROR: TypeError: this.sms.sendMessage is not a function
                                      vfunc_response@$XTN_PATH/service/ui/telephony.js:103:13
                                      @$XTN_PATH/service/daemon.js:778:2
```

**Comment by andyholmes** [comment] 2019-01-09 21:11
> Then, picking one, composing the sms, I can't send it (clicking on Send or Ctrl + Enter doesn't do anything)

Oops! Fixed in fc4c953 and added <kbd>Ctrl</kbd>+<kbd>Enter</kbd> shortcut as a sorry gift :P

**Comment by andyholmes** [comment] 2019-01-17 15:14
I'm going to close this one up now, since it's clearly an upstream issue. I'll leave it pinned for now though, so people are aware.

Consider posting a `logcat` in the upstream bug report to help out the KDE Connect developers: https://bugs.kde.org/show_bug.cgi?id=401677

**Comment by andyholmes** [comment] 2019-01-17 16:09
This would still be an upstream issue. There's just nothing to be fixed on GSConnect's side and it would have to be fixed in Android.

**Comment by alexandrupetrini** [comment] 2019-01-23 13:21
I would like to also report Nokia 5 with Android 8.1 vanilla. In general Nokia 3 and above have Android  8.1 vanilla so mixing these 2 brands might be total No No.

**Comment by andyholmes** [comment] 2019-01-23 15:42
Hi, if you can please report this information upstream, preferrably with a logcat from Android. The bug has been reported for a number of phones and Android version, but still lacks the logs KDE Connect developers need to fix this in the Android app.

https://bugs.kde.org/show_bug.cgi?id=401677

**Comment by maxerbox** [comment] 2019-11-10 23:02
Xiami Phones are fixed with the last commit: https://invent.kde.org/kde/kdeconnect-android/commit/4a0c53610f5b8f82162bda0a2ac81d789f00e64a

**Comment by aaronSkar** [comment] 2020-02-17 22:44
This seems to be working now on my Samsung s9 with android 10. Software versions I am on listed below. I have commented this on the KDE site as well.  These versions were all taken through normal updates from Manjaro, Gnome Extensions and Google App store. I'm not running any custom stuff on my phone or PC.

Samsung Galexy S9
Android 10
Samsung Messages 11.0.00.291
KDEConnect Android App 1.13.7

Gnome Version: 3.34.2
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=19.0.0
DISTRIB_CODENAME=Kyria
DISTRIB_DESCRIPTION="Manjaro Linux"

GSConnect 31
Legacy Message Support = Disabled

**Comment by RicardoEPRodrigues** [comment] 2020-02-23 21:31
Hello, I'm using a Samsung S10e with a similar loadout of @aaronSkar, yet I'm unable to see the messages.

Samsung Galaxy S10e
Android 10
Samsung Messages 11.0.00.307
KDEConnect Android App 1.13.7

Gnome Version: 3.34.2
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Pop!_OS 19.10"

GSConnect 31
Legacy Message Support = Disabled

I did find someone that explored this issue a bit further here: https://invent.kde.org/kde/kdeconnect-android/issues/2

**Comment by ferdnyc** [comment] 2020-02-24 07:51
@aaronSkar 
> Samsung Galexy S9
> Android 10

That's not really sufficient detail in these cases, as Android releases have build numbers, and each carrier has their own build of the system software. (Which is first customized by Samsung for each model they offer — two different "Android 9" devices aren't really running the same OS, exactly, even if they're from the same manufacturer.) The excessive details are all listed in **Settings > About phone > Software information** on the device. 

For example, my Galaxy Note 8 (where SMS still, for the record, also does not work) is currently running Sprint's `SAOMC_SM-N950U_OYN_SPR_PP_0020`, a carrier-distributed package of Samsung's build number `PPR1.180610.011.N950USQS7DTA5` of Android 9. (Using version 1.0 of the One UI, their latest successor to the Experience UX, which replaced TouchWiz before it.)

![Screenshot_20200224-024021_Settings](https://user-images.githubusercontent.com/538020/75135377-5a271e00-56af-11ea-85c2-d44aafa3b840.jpg)

**Comment by ferdnyc** [comment] 2020-02-24 07:53
...And I should probably charge my battery.

**Comment by RicardoEPRodrigues** [comment] 2020-02-24 10:29
So what information is relevant to detail here? All that you showed?

What can we do to help on this issue?

**Comment by ferdnyc** [comment] 2020-02-24 15:50
> So what information is relevant to detail here? All that you showed?

Honestly, we have no idea. Having more data points _might_ help determine that, but it's not yet clear what the pattern is, or that there even is a pattern really.

> What can we do to help on this issue?

Here? Nothing. It's a KDE Connect Android bug, and can only be solved there. When it is, GSConnect will also benefit from the fix.

**Comment by bprfh** [comment] 2020-03-03 17:06
Just an FYI:
I have a samsung S9 with the newest updates(In Europe) and I see all messages now.
Using the default samsung sms manager.

**Comment by dmeltzer** [comment] 2020-06-12 18:08
For those not directly following along in the companion bug, there was a commit in kdeconnect-android a few days ago that fixes a lot of these issues (maybe all of them?) 

I don't think there is a released version of this yet, but keep an eye out the next time your kdeconnect android app updates and messages may work again.

https://invent.kde.org/network/kdeconnect-android/-/commit/876d1fa3db9a7f9a136ae2cabe38bc81194b6dfd

**Comment by ferdnyc** [comment] 2020-07-29 16:50
I guess this still hasn't been released, huh? Even as a beta tester 1.14.2 is the latest my phone finds, and that was released over three months ago now. (As @dmeltzer 's comment shows, the commit in question is only a month or so old.)

Oh well. I'm sure it'll find its way to us eventually. Probably accompanied by even more new features!

**Comment by andyholmes** [comment] 2020-07-29 18:54
> Oh well. I'm sure it'll find its way to us eventually. Probably accompanied by even more new features!

It should be eventua-soon-ly (a new word I invented for FOSS :wink:). KDE Connect is in their GSoC again and there's been some good work there so I decided to re-open. If all goes well we can hopefully rip out the legacy SMS code.

I'm working my way towards the UI, where we'll need to fix our a11y support that's especially bad in the Messaging UI. I think I'll have to put my foot down on fixing that before we add new features, otherwise it'll just be a nightmare later.

**Comment by pczekalski** [comment] 2020-09-15 13:11
I acknowledge, the problem still persists with Samsung Galaxy Note 8, KDE Connect 1.14.2, all permissions given. 
OS is Ubuntu 20.04

**Comment by EsrefEr** [comment] 2020-09-20 02:11
I also acknowledge that the problem still persists with Samsung Galaxy S8 running LineageOS,  KDE Connect 1.14.2 and OS is x86_64 Linux 5.8.9-arch2-1.

**Comment by EsrefEr** [comment] 2020-09-20 02:11
I also acknowledge that the problem still persists with Samsung Galaxy S8 running LineageOS, KDE Connect 1.14.2 and OS x86_64 Linux 5.8.9-arch2-1.

**Comment by andyholmes** [comment] 2020-09-20 02:39
Locking this thread for now.

This is an upstream issue that can't be fixed in GSConnect, and only exists to track the upstream bug.

**Comment by andyholmes** [comment] 2023-09-20 01:06
Closing, since this is not a bug in GSConnect and it's 2023 now :)

**Closed by andyholmes** 2023-09-20 01:06 UTC
Labels: can't fix, upstream
