### ISSUE TITLE
Gnome 43.beta broken

### ISSUE THREAD

**Issue by timocapa** [GSConnect/gnome-shell-extension-gsconnect#1437] opened 2022-08-11 23:14 UTC
With the new quick settings UI actually merged now, it's probably a good idea to track this here as GSConnect is now **broken**

gnome-extensions is starting with:

`AggregateMenu is undefined`

**Comment by andyholmes** [comment] 2022-08-12 08:23
Duplicate of #1428

**Closed by andyholmes** 2022-08-12 08:23 UTC
Labels: duplicate
