### ISSUE TITLE
Child process exited with code 1

### ISSUE THREAD

**Issue by jeffersonoh** [GSConnect/gnome-shell-extension-gsconnect#1361] opened 2022-05-22 09:59 UTC
```
GSConnect: 50 (user)
GJS:       17200
Session:   x11
OS:        Pop!_OS 22.04 LTS

Gio.TlsCertificate.new_for_paths@/home/jeffersonoh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:349:14
_initCertificate@/home/jeffersonoh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:177:48
start@/home/jeffersonoh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:440:18
_loadBackends@/home/jeffersonoh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:255:25
start@/home/jeffersonoh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:458:14
vfunc_startup@/home/jeffersonoh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/jeffersonoh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/jeffersonoh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by andyholmes** [comment] 2022-08-02 23:49
Closing as a duplicate of #1209.

Please continue discussion there, or re-open if it is a different issue.

**Closed by andyholmes** 2022-08-02 23:49 UTC
Labels: duplicate
