### ISSUE TITLE
mount filesystem not working

### ISSUE THREAD

**Issue by jpritikin** [GSConnect/gnome-shell-extension-gsconnect#1647] opened 2023-06-23 18:59 UTC
### Describe the bug

When I select `Mount` then nothing happens.

### Expected behavior

`mount |grep ssh` should report something.

### GSConnect version

55

### Installed from

GNOME Extensions website

### GNOME Shell version

44.2-0ubuntu1

### Linux distribution/release

Ubuntu 23.04

### Paired device(s)

OnePlus 7T

### KDE Connect app version

1.26.0

### Plugin(s)

Mount

### Support log

```plain text
GSConnect: 55 (user)
GJS:       17600
Session:   wayland
OS:        Ubuntu 23.04
--------------------------------------------------------------------------------
Jun 23 11:52:21 org.gnome.Shell.Extensions.GSConnect[10262]: [/service/plugins/sftp.js:_listDirectories/iter</<:165]: OnePlus 7T: Permission denied
                                                             _listDirectories/iter</<@/home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:165:38
                                                             @/home/joshua/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:731:17
```

### Notes

I already looked at issue #1203. I added `/etc/ssh/ssh_config.d/gsconnect.conf` with
```
Host 192.168.*.*
  HostKeyAlgorithms +ssh-rsa
```

And I tested with sftp:
```
joshua@oilfree ~> sftp -v -P 1739  kdeconnect@192.168.1.112
OpenSSH_9.0p1 Ubuntu-1ubuntu8.2, OpenSSL 3.0.8 7 Feb 2023
debug1: Reading configuration data /home/joshua/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/gsconnect.conf
debug1: /etc/ssh/ssh_config.d/gsconnect.conf line 2: Applying options for 192.168.*.*
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to 192.168.1.112 [192.168.1.112] port 1739.
debug1: Connection established.
debug1: identity file /home/joshua/.ssh/id_rsa type 0
debug1: identity file /home/joshua/.ssh/id_rsa-cert type -1
debug1: identity file /home/joshua/.ssh/id_ecdsa type -1
debug1: identity file /home/joshua/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/joshua/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/joshua/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/joshua/.ssh/id_ed25519 type 3
debug1: identity file /home/joshua/.ssh/id_ed25519-cert type -1
debug1: identity file /home/joshua/.ssh/id_ed25519_sk type -1
debug1: identity file /home/joshua/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/joshua/.ssh/id_xmss type -1
debug1: identity file /home/joshua/.ssh/id_xmss-cert type -1
debug1: identity file /home/joshua/.ssh/id_dsa type -1
debug1: identity file /home/joshua/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.0p1 Ubuntu-1ubuntu8.2
debug1: Remote protocol version 2.0, remote software version SSHD-CORE-0.14.0
debug1: compat_banner: no match: SSHD-CORE-0.14.0
debug1: Authenticating to 192.168.1.112:1739 as 'kdeconnect'
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: ecdh-sha2-nistp384
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-rsa SHA256:bWiw8uMnljGaNJOx4dHXc4mcYKyH3Y+6CKjj5j3kLp4
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: checking without port identifier
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
Warning: Permanently added '[192.168.1.112]:1739' (RSA) to the list of known hosts.
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 4294967296 blocks
debug1: get_agent_identities: bound agent to hostkey
debug1: get_agent_identities: agent returned 3 keys
debug1: Will attempt key: /home/joshua/.ssh/id_ed25519 ED25519 SHA256:vvUmyMe78rmzIeTPB55Z+ykVwVdPyXNxQNnYzScx/2c agent
debug1: Will attempt key: /home/joshua/.ssh/id_rsa RSA SHA256:/njPArQPWFeM84D5XMvuekTroj2a4dgTy5JVYJHeeRI agent
debug1: Will attempt key: /home/joshua/.config/gsconnect/private.pem RSA SHA256:HaEwPckkErmSkRRHF+q/UfDeq+w2h2DUJ6I3Bpk/khQ agent
debug1: Will attempt key: /home/joshua/.ssh/id_ecdsa 
debug1: Will attempt key: /home/joshua/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /home/joshua/.ssh/id_ed25519_sk 
debug1: Will attempt key: /home/joshua/.ssh/id_xmss 
debug1: Will attempt key: /home/joshua/.ssh/id_dsa 
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: password,keyboard-interactive,publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/joshua/.ssh/id_ed25519 ED25519 SHA256:vvUmyMe78rmzIeTPB55Z+ykVwVdPyXNxQNnYzScx/2c agent
debug1: Authentications that can continue: password,keyboard-interactive,publickey
debug1: Offering public key: /home/joshua/.ssh/id_rsa RSA SHA256:/njPArQPWFeM84D5XMvuekTroj2a4dgTy5JVYJHeeRI agent
debug1: send_pubkey_test: no mutual signature algorithm
debug1: Offering public key: /home/joshua/.config/gsconnect/private.pem RSA SHA256:HaEwPckkErmSkRRHF+q/UfDeq+w2h2DUJ6I3Bpk/khQ agent
debug1: send_pubkey_test: no mutual signature algorithm
debug1: Trying private key: /home/joshua/.ssh/id_ecdsa
debug1: Trying private key: /home/joshua/.ssh/id_ecdsa_sk
debug1: Trying private key: /home/joshua/.ssh/id_ed25519_sk
debug1: Trying private key: /home/joshua/.ssh/id_xmss
debug1: Trying private key: /home/joshua/.ssh/id_dsa
debug1: Next authentication method: keyboard-interactive
Password authentication
(kdeconnect@192.168.1.112) Password: 
```

**Comment by eathtespagheti** [comment] 2023-07-13 06:46
I have the same issue on Arch Linux and a Pixel 5

**Comment by eathtespagheti** [comment] 2023-07-13 06:53
Checking #1610 I've found as a workaround to press `CTRL + L` and add to the addess bar `storage/emulated/0`

**Comment by alexanderadam** [comment] 2023-08-07 21:51
In that case this issue here can probably be closed as a duplicate of #1610

**Comment by benyaminl** [comment] 2023-08-28 02:54
But in my location in Ubuntu 22.04, I can't even see any gvfs sftp mounted. Is there anyway to debug it? 

I'm really new, and I already expose the folder that I want to share to filesystem plugin in KDE Connect

**Comment by andyholmes** [comment] 2024-03-02 00:08
Closing as a duplicate of #1210

**Closed by andyholmes** 2024-03-02 00:08 UTC
Labels: triage
