### ISSUE TITLE
module.ChannelService is not a constructor

### ISSUE THREAD

**Issue by youssefchei** [GSConnect/gnome-shell-extension-gsconnect#1320] opened 2022-03-31 20:53 UTC
```
GSConnect: 47 (user)
GJS:       17200
Session:   wayland
OS:        Ubuntu Jammy Jellyfish (development branch)

_loadBackends@/home/youssef/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/youssef/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/youssef/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/youssef/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/youssef/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

**Comment by ferdnyc** [comment] 2022-04-01 01:29
@youssefchei This is fixed in the new releases, which are available on extensions.gnome.org. Please update GSConnect. If you find that you aren't able to update, please open a new issue with details of the problem.

Duplicate of #1256

**Closed by ferdnyc** 2022-04-01 01:29 UTC
Labels: duplicate, unsupported
