### ISSUE TITLE
GS connect

### ISSUE THREAD

**Issue by athak9** [GSConnect/gnome-shell-extension-gsconnect#1448] opened 2022-08-29 11:06 UTC
this app not work in ubuntu 22.04,after installation the program disappears.
It is impossible to connect wirelessly from my mobile even though I have it on KD connect.
Yours sincerely

**Comment by andyholmes** [comment] 2022-08-30 19:51
Sorry, but you will have to provide more information to get help with this problem.

See the wiki for [Generating a Support Log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log).

**Comment by yuexiangqianlong** [comment] 2022-09-01 06:33
![截图 2022-09-01 14-32-40](https://user-images.githubusercontent.com/26164678/187847315-b1746d4e-c73c-4692-95c7-ada68328cc14.png)
显示版本不兼容，启动不了看不到日志

**Comment by andyholmes** [comment] 2022-09-01 15:01
@yuexiangqianlong is this on GNOME 43? If not, what version of GNOME?

**Comment by yuexiangqianlong** [comment] 2022-09-02 01:39
![370706186](https://user-images.githubusercontent.com/26164678/188040388-75633d16-541f-4b7e-91a1-7fe41a9ce49d.jpg)
GNOME 是 42.2 版本，

**Comment by andyholmes** [comment] 2022-09-02 01:50
Ah, you should install [v50](https://github.com/GSConnect/gnome-shell-extension-gsconnect/releases/tag/v50).

* v53 => GNOME 3.36
* v51 => GNOME 3.38
* v50 => GNOME 42  :tada:

**Comment by yuexiangqianlong** [comment] 2022-09-02 01:55
![Screenshot from 2022-09-02 09-53-05](https://user-images.githubusercontent.com/26164678/188042265-171dcdf0-79f1-4e13-bb88-e4c25b3fcd45.png)

**Comment by yuexiangqianlong** [comment] 2022-09-02 02:17
solved

**Comment by DanielGlaas** [comment] 2022-09-05 06:42
> solved

Can you provide more details on how you solved this?

I updated from Ubuntu 20.04 to 22.04 and now GSConnect does not work anymore. I did not select any specific version and also did no upgrade on this extension and have now v53 installed.
![image](https://user-images.githubusercontent.com/58786395/188381468-7d3173f5-f801-41e8-9c6a-0aecba0cc958.png)

How can I do a downgrade of the extension?

**Comment by yuexiangqianlong** [comment] 2022-10-17 02:12
> > 解决了
> 
> 您能否提供有关如何解决此问题的更多详细信息？
> 
> 我从 Ubuntu 20.04 更新到 22.04，现在 GSConnect 不再工作了。我没有选择任何特定版本，也没有对此扩展进行升级，现在安装了 v53。 ![图片](https://user-images.githubusercontent.com/58786395/188381468-7d3173f5-f801-41e8-9c6a-0aecba0cc958.png)
> 
> 如何降级扩展？

To completely remove GSConnect, all files and settings run following commands in order from the command-line:
```
gnome-extensions uninstall gsconnect@andyholmes.github.io
rm -rf ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
rm -rf ~/.cache/gsconnect
rm -rf ~/.config/gsconnect
dconf reset -f /org/gnome/shell/extensions/gsconnect/
```
After executing the above command, you need to download the corresponding GNOME version on your computer
v53 => GNOME 3.36
v51 => GNOME 3.38
v50 => GNOME 42

**Comment by andyholmes** [comment] 2023-09-20 01:04
Closing since I believe the issue is solved.

**Closed by andyholmes** 2023-09-20 01:04 UTC
Labels: needs info
